Repository ethersphere/bee, pull requests merged in 2020-08, with the labels that each got.

#505 limit max http body size and detect it
  pkg/api/chunk.go
  pkg/api/router.go
  pkg/jsonhttp/handlers.go
  pkg/jsonhttp/handlers_test.go
Labels: ready for review

#439 Dynamic welcome message
  pkg/debugapi/debugapi.go
  pkg/debugapi/export_test.go
  pkg/debugapi/router.go
  pkg/debugapi/welcome_message.go
  pkg/debugapi/welcome_message_test.go
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/p2p/libp2p/internal/handshake/handshake_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/welcome_message_test.go
  pkg/p2p/mock/mock.go
  pkg/p2p/p2p.go
Labels: ready for review

#510 update golangci-lint to the latest release
  .github/workflows/go.yml
  Makefile
Labels: ready for review

#467 Accounting metrics
  pkg/accounting/accounting.go
  pkg/accounting/metrics.go
  pkg/node/node.go
Labels: ready for review

#500 return empty response when nothing is pinned
  pkg/debugapi/pin_test.go
  pkg/localstore/pin.go
  pkg/storage/mock/storer.go
Labels: ready for review

#427 Check for validity before concluding retrieving chunk
  pkg/content/mock/validator.go
  pkg/content/validator.go
  pkg/netstore/netstore.go
  pkg/netstore/netstore_test.go
  pkg/node/node.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
  pkg/soc/validator.go
  pkg/storage/mock/storer.go
  pkg/swarm/swarm.go
Labels: ready for review

#449 Reset in streamtest
  pkg/p2p/streamtest/streamtest.go
  pkg/p2p/streamtest/streamtest_test.go
Labels: ready for review

#514 streamtest record err flaky test fix
  pkg/netstore/netstore_test.go
  pkg/p2p/streamtest/streamtest.go
Labels: ready for review

#511 fix forever loop timeout issue
  pkg/trojan/message.go
  pkg/trojan/message_test.go
Labels: bug, ready for review

#519 readd server accounting check in retrieval test
  pkg/retrieval/retrieval_test.go
Labels: ready for review

#524 retrieval: return chunk not found if max peers reached
  pkg/retrieval/retrieval.go
Labels: ready for review

#503 api, jsonmanifest, manifest: getter for jsonmanifest entries
  pkg/api/bzz.go
  pkg/api/dirs.go
  pkg/api/dirs_test.go
  pkg/manifest/jsonmanifest/entry.go
  pkg/manifest/jsonmanifest/jsonmanifest_test.go
  pkg/manifest/jsonmanifest/manifest.go
  pkg/manifest/manifest.go
Labels: clean-up, ready for review

#540 node: remove var declaration for storer
  pkg/node/node.go
Labels: clean-up, ready for review

#516 hive: clean up tests, allow for unordered response
  pkg/hive/hive_test.go
Labels: flaky-test, ready for review

#465 settlement protocol and payment threshold
  cmd/bee/cmd/start.go
  pkg/accounting/accounting.go
  pkg/accounting/accounting_test.go
  pkg/node/node.go
  pkg/settlement/interface.go
  pkg/settlement/pseudosettle/doc.go
  pkg/settlement/pseudosettle/pb/doc.go
  pkg/settlement/pseudosettle/pb/pseudosettle.pb.go
  pkg/settlement/pseudosettle/pb/pseudosettle.proto
  pkg/settlement/pseudosettle/pseudosettle.go
  pkg/settlement/pseudosettle/pseudosettle_test.go
Labels: ready for review

#537 set retrieve chunk max peers log message level to trace
  pkg/retrieval/retrieval.go
Labels: ready for review

#547 fix lint and vet go github workflow condition
  .github/workflows/go.yml
Labels: ready for review

#550 Options struct usage
  cmd/bee/cmd/start.go
  cmd/internal/file/io_test.go
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/debugapi/debugapi_test.go
  pkg/node/node.go
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/headers_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/libp2p_test.go
  pkg/p2p/libp2p/protocols_test.go
  pkg/p2p/libp2p/tracing_test.go
  pkg/p2p/libp2p/welcome_message_test.go
Labels: ready for review

#551 Support multiple notifiers in 'libp2p.Service'
  pkg/node/node.go
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/libp2p_test.go
  pkg/p2p/libp2p/peer.go
  pkg/p2p/mock/mock.go
  pkg/p2p/p2p.go
Labels: enhancement, ready for review

#552 Peer added fix
  pkg/p2p/libp2p/peer.go
Labels: ready for review

#553 Remove invalid disconnected call
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/peer.go
Labels: ready for review

#556 expose remove chunk debug API
  pkg/debugapi/chunk.go
  pkg/debugapi/chunk_test.go
  pkg/debugapi/router.go
  pkg/storage/mock/storer.go
Labels: ready for review

#561 golangci-lint binary install
  .github/workflows/go.yml
  Makefile
Labels: ready for review

#466 trojan, pss, pss_test: pss port from Swarm
  pkg/pss/metrics.go
  pkg/pss/pss.go
  pkg/pss/pss_test.go
  pkg/trojan/export_test.go
  pkg/trojan/message.go
Labels: ready for review

#558 Fallback to bootnodes
  pkg/hive/hive.go
  pkg/kademlia/doc.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/mock/kademlia.go
  pkg/node/node.go
  pkg/topology/full/full.go
  pkg/topology/full/full_test.go
  pkg/topology/mock/mock.go
  pkg/topology/topology.go
Labels: ready for review

#560 Respect 'Writer' interface contract in 'ChunkPipe'
  pkg/file/buffer.go
  pkg/file/buffer_test.go
Labels: bug

#479 Chunk repair
  cmd/bee-split/stdout
  cmd/bee/cmd/start.go
  pkg/api/bzz.go
  pkg/api/chunk.go
  pkg/api/file.go
  pkg/localstore/mode_set.go
  pkg/netstore/netstore.go
  pkg/netstore/netstore_test.go
  pkg/node/node.go
  pkg/pss/pss.go
  pkg/pss/pss_test.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/recovery/repair.go
  pkg/recovery/repair_test.go
  pkg/sctx/sctx.go
  pkg/storage/mock/storer.go
  pkg/swarm/swarm.go
  pkg/trojan/message.go
Labels: ready for review

#566 Validate write operation expected result
  pkg/file/buffer.go
Labels: ready for review

#564 rename tests to not have fail word
  pkg/debugapi/welcome_message_test.go
  pkg/p2p/libp2p/welcome_message_test.go
  pkg/trojan/message.go
  pkg/trojan/message_test.go
Labels: clean-up, ready for review

#568 remove stdout file
  cmd/bee-split/stdout
Labels: clean-up, ready for review

#565 api: add pin on upload
  cmd/bee-file/main.go
  cmd/bee-split/main.go
  pkg/api/api.go
  pkg/api/bytes.go
  pkg/api/bzz_test.go
  pkg/api/chunk.go
  pkg/api/chunk_test.go
  pkg/api/dirs.go
  pkg/api/file.go
  pkg/debugapi/pin_test.go
  pkg/debugapi/tag_test.go
  pkg/file/file_test.go
  pkg/file/joiner/joiner_test.go
  pkg/file/splitter/internal/job.go
  pkg/file/splitter/internal/job_test.go
  pkg/file/splitter/splitter.go
  pkg/file/splitter/splitter_test.go
  pkg/localstore/localstore_test.go
  pkg/localstore/mode_put.go
  pkg/localstore/mode_put_test.go
  pkg/localstore/pin.go
  pkg/storage/mock/storer.go
  pkg/storage/mock/storer_test.go
  pkg/storage/store.go
Labels: clean-up, enhancement, ready for review

#567 remove disconnect threshold argument
  cmd/bee/cmd/start.go
  pkg/node/node.go
Labels: ready for review

#546 add balance debug api to openapi
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
Labels: ready for review

#570 Peer registry fix - multiple connections
  pkg/p2p/libp2p/peer.go
Labels: ready for review

#554 file: add seek functionality to joiner
  pkg/api/dirs_test.go
  pkg/api/file.go
  pkg/api/file_test.go
  pkg/file/file.go
  pkg/file/seekjoiner/internal/job.go
  pkg/file/seekjoiner/internal/job_test.go
  pkg/file/seekjoiner/joiner.go
  pkg/file/seekjoiner/joiner_test.go
  pkg/trojan/message.go
Labels: enhancement, ready for review

#557 api, debugapi, internal, sctx, tags: tags cleanup
  pkg/api/api.go
  pkg/api/bytes.go
  pkg/api/chunk.go
  pkg/api/dirs.go
  pkg/api/export_test.go
  pkg/api/file.go
  pkg/api/router.go
  pkg/api/tag.go
  pkg/api/tag_test.go
  pkg/debugapi/export_test.go
  pkg/debugapi/router.go
  pkg/debugapi/tag.go
  pkg/debugapi/tag_test.go
  pkg/file/splitter/internal/job.go
  pkg/jsonhttp/jsonhttp.go
  pkg/jsonhttp/jsonhttptest/jsonhttptest.go
  pkg/pushsync/pushsync.go
  pkg/sctx/sctx.go
  pkg/tags/tag.go
  pkg/tags/tags.go
Labels: clean-up, ready for review

#580 Always load balance from store
  pkg/accounting/accounting.go
Labels: ready for review

#584 call reserve in booking test correctly
  pkg/accounting/accounting_test.go
Labels: ready for review

#583 Options structs cleanup - part2
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/hive/hive.go
  pkg/hive/hive_test.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/node/node.go
  pkg/pingpong/pingpong.go
  pkg/pingpong/pingpong_test.go
  pkg/puller/puller.go
  pkg/puller/puller_test.go
  pkg/pullsync/pullsync.go
  pkg/pullsync/pullsync_test.go
  pkg/pusher/pusher.go
  pkg/pusher/pusher_test.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/recovery/repair_test.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
Labels: ready for review

#574 fix int conversion to string in statestore test
  pkg/statestore/test/store.go
Labels: ready for review

#577 cleanup jsonhttptest package
  pkg/api/bytes_test.go
  pkg/api/bzz_test.go
  pkg/api/chunk_test.go
  pkg/api/dirs_test.go
  pkg/api/file_test.go
  pkg/api/tag_test.go
  pkg/debugapi/balances_test.go
  pkg/debugapi/chunk_test.go
  pkg/debugapi/p2p_test.go
  pkg/debugapi/peer_test.go
  pkg/debugapi/pin_test.go
  pkg/debugapi/pingpong_test.go
  pkg/debugapi/status_test.go
  pkg/debugapi/topology_test.go
  pkg/debugapi/welcome_message_test.go
  pkg/jsonhttp/jsonhttptest/jsonhttptest.go
  pkg/jsonhttp/jsonhttptest/jsonhttptest_test.go
  pkg/jsonhttp/jsonhttptest/testing_mock_test.go
Labels: ready for review

#586 support api version path for tags api endpoints
  pkg/api/router.go
Labels: ready for review

#593 Config command
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/configurateoptions.go
  cmd/bee/cmd/start.go
  go.mod
Labels: ready for review

#594 Add basic metrics counters for total sent/recieved pseudosettle amounts
  pkg/node/node.go
  pkg/settlement/pseudosettle/metrics.go
  pkg/settlement/pseudosettle/pseudosettle.go
Labels: ready for review

#591 Add support for multiple manifest types
  go.mod
  go.sum
  pkg/api/bzz.go
  pkg/api/bzz_test.go
  pkg/api/dirs.go
  pkg/api/dirs_test.go
  pkg/api/file_test.go
  pkg/api/tag_test.go
  pkg/manifest/jsonmanifest/entry.go
  pkg/manifest/jsonmanifest/jsonmanifest_test.go
  pkg/manifest/jsonmanifest/manifest.go
  pkg/manifest/manifest.go
  pkg/manifest/simple.go
Labels: enhancement

#588 accounting in push sync
  pkg/node/node.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
Labels: ready for review

#603 pipeline splitter
  pkg/file/pipeline/bmt_writer.go
  pkg/file/pipeline/chunkfeeder_test.go
  pkg/file/pipeline/chunkfeeder_writer.go
  pkg/file/pipeline/hashtrie_writer.go
  pkg/file/pipeline/normal_test.go
  pkg/file/pipeline/pipeline.go
  pkg/file/pipeline/result_writer.go
  pkg/file/pipeline/store_writer.go
  pkg/file/pipeline/writer.go
  pkg/file/splitter/internal/job_test.go
  pkg/file/testing/vector.go
Labels: enhancement, ready for review

#617 Improve password creation UX
  cmd/bee/cmd/start.go
  cmd/bee/cmd/terminal.go
  pkg/keystore/file/service.go
  pkg/keystore/keystore.go
  pkg/keystore/mem/service.go
  pkg/keystore/test/test.go
  pkg/node/node.go
Labels: ready for review

#610 pipeline splitter integration
  pkg/api/bytes.go
  pkg/api/bzz_test.go
  pkg/api/dirs.go
  pkg/api/file.go
  pkg/file/pipeline/bmt_writer.go
  pkg/file/pipeline/chunkfeeder_test.go
  pkg/file/pipeline/chunkfeeder_writer.go
  pkg/file/pipeline/doc.go
  pkg/file/pipeline/hashtrie_writer.go
  pkg/file/pipeline/normal_test.go
  pkg/file/pipeline/pipeline.go
  pkg/file/pipeline/result_writer.go
  pkg/file/pipeline/store_writer.go
  pkg/manifest/simple.go
Labels: ready for review

#618 api: integrate encryption pipeline
  pkg/api/api.go
  pkg/api/bytes.go
  pkg/api/bzz_test.go
  pkg/api/dirs.go
  pkg/api/file.go
  pkg/api/file_test.go
  pkg/file/joiner/joiner_test.go
  pkg/file/pipeline/pipeline.go
  pkg/file/pipeline/pipeline_test.go
  pkg/manifest/simple.go
Labels: ready for review

#613 pipeline: add and integrate encryption pipeline
  pkg/api/api.go
  pkg/api/bytes.go
  pkg/api/bzz_test.go
  pkg/api/dirs.go
  pkg/api/file.go
  pkg/api/file_test.go
  pkg/file/joiner/joiner_test.go
  pkg/file/pipeline/encryption_writer.go
  pkg/file/pipeline/hashtrie_writer.go
  pkg/file/pipeline/pipeline.go
  pkg/file/pipeline/pipeline_test.go
  pkg/manifest/simple.go
Labels: enhancement, ready for review

#621 Add support for 'mantaray' manifest, and make it default
  go.mod
  go.sum
  pkg/api/dirs_test.go
  pkg/api/file_test.go
  pkg/api/tag_test.go
  pkg/manifest/manifest.go
  pkg/manifest/mantaray.go
Labels: enhancement, ready for review

#622 tags: remove anonymous field
  pkg/api/api.go
  pkg/api/tag.go
  pkg/localstore/mode_put.go
  pkg/localstore/mode_set.go
  pkg/localstore/mode_set_test.go
  pkg/pusher/pusher_test.go
  pkg/pushsync/pushsync_test.go
  pkg/resolver/multi_test.go
  pkg/tags/tag.go
  pkg/tags/tag_test.go
  pkg/tags/tags.go
  pkg/tags/tags_test.go
Labels: clean-up, ready for review

#582 seekjoiner: add pluggable decryption
  cmd/bee-file/main.go
  cmd/bee-join/main.go
  pkg/api/bytes_test.go
  pkg/api/bzz.go
  pkg/api/dirs_test.go
  pkg/api/file.go
  pkg/api/file_test.go
  pkg/collection/entry/entry.go
  pkg/encryption/encryption.go
  pkg/encryption/store/decrypt_store.go
  pkg/file/file.go
  pkg/file/file_test.go
  pkg/file/joiner/internal/job.go
  pkg/file/joiner/internal/job_test.go
  pkg/file/joiner/joiner.go
  pkg/file/joiner/joiner_test.go
  pkg/file/pipeline/encryption_writer.go
  pkg/file/seekjoiner/internal/job.go
  pkg/file/seekjoiner/internal/job_test.go
  pkg/file/seekjoiner/joiner.go
  pkg/file/seekjoiner/joiner_test.go
  pkg/file/splitter/internal/job.go
  pkg/manifest/mantaray.go
  pkg/manifest/simple.go
  pkg/storage/store.go
  pkg/swarm/swarm.go
Labels: clean-up, enhancement, ready for review

#627 add encryption mock
  pkg/encryption/mock/mock.go
  pkg/encryption/mock/mock_test.go
Labels: ready for review

#624 update openapi specifications
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
Labels: ready for review

#632 SplitThenJoinTest: switch to pipeline
  pkg/file/file_test.go
Labels: flaky-test

#597 Standalone flag option for bee
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  pkg/kademlia/kademlia.go
  pkg/node/node.go
  pkg/p2p/libp2p/libp2p.go
Labels: ready for review

#634 Resolver integration
  cmd/internal/file/io_test.go
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/bytes.go
  pkg/api/bzz.go
  pkg/api/chunk.go
  pkg/api/export_test.go
  pkg/api/file.go
  pkg/debugapi/debugapi_test.go
  pkg/node/node.go
  pkg/resolver/multi.go
  pkg/resolver/multi_test.go
Labels: builds on open pr, ready for review

#615 ENS Resolver client
  Makefile
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  cmd/internal/file/io_test.go
  go.mod
  go.sum
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/bytes.go
  pkg/api/bzz.go
  pkg/api/chunk.go
  pkg/api/export_test.go
  pkg/api/file.go
  pkg/debugapi/debugapi_test.go
  pkg/node/node.go
  pkg/resolver/client/client.go
  pkg/resolver/client/ens/ens.go
  pkg/resolver/client/ens/ens_integration_test.go
  pkg/resolver/client/ens/ens_test.go
  pkg/resolver/client/ens/errors.go
  pkg/resolver/client/ens/export_test.go
  pkg/resolver/client/ens/impl.go
  pkg/resolver/config.go
  pkg/resolver/config_test.go
  pkg/resolver/errors.go
  pkg/resolver/mock/resolver.go
  pkg/resolver/multi.go
  pkg/resolver/multi_test.go
  pkg/resolver/resolver.go
  pkg/resolver/service/service.go
Labels: ready for review

#639 add DomainName openapi component
  openapi/SwarmCommon.yaml
Labels: ready for review

#573 node: add tag persistence across sessions
  cmd/internal/file/io_test.go
  pkg/api/bytes.go
  pkg/api/bytes_test.go
  pkg/api/bzz_test.go
  pkg/api/chunk.go
  pkg/api/chunk_test.go
  pkg/api/dirs.go
  pkg/api/dirs_test.go
  pkg/api/file.go
  pkg/api/file_test.go
  pkg/api/tag.go
  pkg/api/tag_test.go
  pkg/debugapi/pin_test.go
  pkg/file/pipeline/store_writer.go
  pkg/file/splitter/internal/job.go
  pkg/localstore/mode_set.go
  pkg/localstore/mode_set_test.go
  pkg/node/node.go
  pkg/pusher/mock/mock.go
  pkg/pusher/pusher.go
  pkg/pusher/pusher_test.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/tags/tag.go
  pkg/tags/tag_test.go
  pkg/tags/tags.go
  pkg/tags/tags_test.go
Labels: enhancement, ready for review

#640 Fix loop break bug in discover
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/p2p/discover.go
Labels: ready for review

#643 update documentation links in readme file
  README.md
Labels: ready for review
