Repository ethersphere/bee, pull requests merged in 2020-11, with the labels that each got.

#906 api: increase pss test read timeout before mining
  pkg/api/pss_test.go
Labels: flaky-test, pull-request, ready for review

#907 beekeeper: update gc and localpinning tests
  .github/workflows/beekeeper.yml
  .github/workflows/slash-beekeeper.yml
Labels: pull-request, ready for review

#909 fix slash commands
  .github/workflows/slash-beekeeper.yml
Labels: pull-request

#908 set chunk as synced only by push sync
  pkg/localstore/gc_test.go
  pkg/localstore/index_test.go
  pkg/localstore/mode_get_test.go
  pkg/localstore/mode_set.go
  pkg/localstore/mode_set_test.go
  pkg/localstore/retrieval_index_test.go
  pkg/pullsync/pullsync.go
  pkg/pullsync/pullsync_test.go
  pkg/pusher/pusher.go
  pkg/pusher/pusher_test.go
  pkg/storage/store.go
Labels: pull-request, ready for review

#932 Add chunk addresses getter iterator
  pkg/file/addresses/addresses_getter.go
  pkg/file/addresses/addresses_getter_test.go
  pkg/swarm/swarm.go
Labels: pull-request, ready for review

#923 Add file joiner function for iterating through chunk addresses
  pkg/file/file.go
  pkg/file/joiner/joiner.go
  pkg/file/joiner/joiner_test.go
Labels: pull-request, ready for review

#886 api: add postage batch id header
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/bytes.go
  pkg/api/bzz_test.go
  pkg/api/dirs.go
  pkg/api/file.go
  pkg/file/file_test.go
  pkg/file/joiner/joiner_test.go
  pkg/file/pipeline/builder/builder.go
  pkg/file/pipeline/builder/builder_test.go
  pkg/manifest/manifest.go
  pkg/manifest/mantaray.go
  pkg/manifest/simple.go
Labels: pull-request, ready for review

#890 postage: new pkg for postage stamps, uploader stamping
  pkg/postage/export_test.go
  pkg/postage/service.go
  pkg/postage/service_test.go
  pkg/postage/stamp.go
  pkg/postage/stamp_test.go
  pkg/postage/stamper.go
  pkg/postage/stamper_test.go
  pkg/postage/stampissuer.go
  pkg/postage/stampissuer_test.go
  pkg/postage/testing/stamp.go
  pkg/swarm/swarm.go
Labels: pull-request, ready for review

#924 Chunk traversal
  go.mod
  go.sum
  pkg/collection/entry/entry.go
  pkg/file/joiner/joiner.go
  pkg/file/joiner/joiner_test.go
  pkg/manifest/manifest.go
  pkg/manifest/mantaray.go
  pkg/manifest/simple.go
  pkg/storage/mock/storer.go
  pkg/traversal/traversal.go
  pkg/traversal/traversal_test.go
Labels: pull-request, ready for review

#948 fix all set-env and add-path
  .github/workflows/beekeeper.yml
  .github/workflows/go.yml
  .github/workflows/schedule.yaml
  .github/workflows/slash-beekeeper.yml
Labels: pull-request

#944 add init command
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/init.go
  cmd/bee/cmd/start.go
  pkg/node/node.go
Labels: pull-request, ready for review

#940 Updates to API endpoints for pin and unpin
  cmd/internal/file/io_test.go
  openapi/Swarm.yaml
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/gatewaymode_test.go
  pkg/api/pin_bytes.go
  pkg/api/pin_bytes_test.go
  pkg/api/pin_bzz.go
  pkg/api/pin_bzz_test.go
  pkg/api/pin_chunks.go
  pkg/api/pin_chunks_test.go
  pkg/api/pin_files.go
  pkg/api/pin_files_test.go
  pkg/api/router.go
  pkg/node/node.go
Labels: pull-request, ready for review

#961 change ports in all places
  Dockerfile
  cmd/bee-file/main.go
  cmd/bee-join/main.go
  cmd/bee-split/main.go
  cmd/bee/cmd/cmd.go
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
  pkg/bzz/address_test.go
  pkg/debugapi/peer_test.go
  pkg/kademlia/kademlia_test.go
  pkg/p2p/libp2p/internal/handshake/handshake_test.go
  pkg/topology/full/full_test.go
Labels: pull-request

#966 api: dont write back empty header
  pkg/api/chunk.go
  pkg/api/file.go
Labels: pull-request, ready for review

#965 retry balance check
  pkg/settlement/swap/chequebook/init.go
Labels: pull-request, ready for review

#962 deb and rpm support
  .goreleaser.yml
  packaging/bee.service
  packaging/bee.yaml
  packaging/deb/postinst
  packaging/deb/postrm
  packaging/deb/preinst
  packaging/deb/prerm
  packaging/deb/templates
  packaging/default
  packaging/rpm/post
  packaging/rpm/postun
  packaging/rpm/pre
  packaging/rpm/preun
Labels: pull-request, ready for review

#976 disable chuckrepair test
  .github/workflows/beekeeper.yml
  .github/workflows/slash-beekeeper.yml
Labels: pull-request

#973 add to localstore gc index on ModePutSync
  pkg/localstore/mode_put.go
  pkg/localstore/mode_put_test.go
Labels: pull-request, ready for review

#942 validators/callbacks reorg to enable pss mailboxing
  pkg/api/pss_test.go
  pkg/netstore/netstore.go
  pkg/netstore/netstore_test.go
  pkg/node/node.go
  pkg/pss/pss.go
  pkg/pss/pss_test.go
  pkg/pullsync/pullsync.go
  pkg/pullsync/pullsync_test.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/recovery/repair.go
  pkg/recovery/repair_test.go
  pkg/retrieval/retrieval_test.go
  pkg/swarm/swarm.go
  pkg/swarm/validator.go
Labels: pull-request, ready for review

#979 localstore: dont store chunk when it already exists
  pkg/localstore/mode_put.go
  pkg/localstore/mode_put_test.go
Labels: pull-request, ready for review

#980 add PSS dedicated private key
  cmd/bee/cmd/start.go
  openapi/SwarmCommon.yaml
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/p2p.go
  pkg/debugapi/p2p_test.go
  pkg/node/node.go
Labels: pull-request

#975 Log ethereum address on bee init/start
  cmd/bee/cmd/start.go
  pkg/node/node.go
Labels: pull-request

#947 Pushsync retry next peer after error
  pkg/kademlia/kademlia.go
  pkg/kademlia/mock/kademlia.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/topology/full/full.go
  pkg/topology/mock/mock.go
  pkg/topology/topology.go
Labels: pull-request, ready for review

#981 remove unused arguments and options from node.NewBee
  cmd/bee/cmd/start.go
  pkg/node/node.go
Labels: pull-request, ready for review

#957 Add API for changing pin counter
  openapi/Swarm.yaml
  pkg/api/export_test.go
  pkg/api/pin_chunks.go
  pkg/api/pin_chunks_test.go
  pkg/api/router.go
Labels: pull-request, ready for review

#972 Surplus balances for peers, debug API addons
  openapi/SwarmDebug.yaml
  pkg/accounting/accounting.go
  pkg/accounting/accounting_test.go
  pkg/accounting/mock/accounting.go
  pkg/debugapi/balances.go
  pkg/debugapi/balances_test.go
  pkg/debugapi/router.go
Labels: pull-request, ready for review

#982 Packaging clef option
  cmd/bee/cmd/start.go
  packaging/bee.yaml
  packaging/deb/postinst
  packaging/deb/preinst
  packaging/deb/templates
  packaging/rpm/post
  packaging/rpm/pre
Labels: pull-request, ready for review

#986 don't hold global chequebook lock while sending cheque
  pkg/settlement/swap/chequebook/chequebook.go
Labels: pull-request, ready for review

#870 Surplus balances for peers
  openapi/SwarmDebug.yaml
  pkg/accounting/accounting.go
  pkg/accounting/accounting_test.go
  pkg/accounting/mock/accounting.go
  pkg/debugapi/balances.go
  pkg/debugapi/balances_test.go
  pkg/debugapi/router.go
Labels: pull-request, ready for review

#953 call notifypayment in go routine in swap and restore full close
  pkg/accounting/accounting.go
  pkg/node/node.go
  pkg/settlement/interface.go
  pkg/settlement/pseudosettle/mock/pseudosettle.go
  pkg/settlement/pseudosettle/pseudosettle.go
  pkg/settlement/pseudosettle/pseudosettle_test.go
  pkg/settlement/swap/mock/swap.go
  pkg/settlement/swap/swap.go
  pkg/settlement/swap/swap_test.go
  pkg/settlement/swap/swapprotocol/swapprotocol.go
Labels: pull-request, ready for review

#989 use correct payment threshold in final reserve check
  pkg/accounting/accounting.go
Labels: pull-request, ready for review

#991 fix post script for rpm
  packaging/rpm/post
Labels: pull-request

#990 fix pushsync logs
  pkg/pushsync/pushsync.go
Labels: pull-request

#988 api: add pss CORS check
  pkg/api/api.go
  pkg/api/pss.go
  pkg/api/router.go
Labels: pull-request, ready for review

#992 remove templates, unify deb and rpm install and add bee-get-addr wrapper
  .goreleaser.yml
  packaging/bee-get-addr
  packaging/deb/postinst
  packaging/deb/templates
  packaging/rpm/post
Labels: pull-request, ready for review

#994 initial homebrew publish support
  .goreleaser.yml
  packaging/homebrew/bee-get-addr
  packaging/homebrew/bee.yaml
Labels: pull-request, ready for review

#995 enable clef for tests
  .github/workflows/beekeeper.yml
Labels: pull-request, ready for review

#987 remove payment tolerance check
  pkg/accounting/accounting.go
  pkg/accounting/accounting_test.go
Labels: pull-request, ready for review

#1000 adjust link to faucet to autofill address
  pkg/settlement/swap/chequebook/init.go
Labels: pull-request, ready for review

#1008 dont retry retrieval when main context expires
  pkg/retrieval/retrieval.go
Labels: pull-request, ready for review

#1009 Revert "blocklist peer on retrieval timeout (#826)"
  pkg/recovery/repair_test.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
Labels: pull-request

#1004 forbid PSS API endpoints in the Gateway mode
  pkg/api/gatewaymode_test.go
  pkg/api/router.go
Labels: pull-request, ready for review

#1002 better error if insufficient funds for user action
  pkg/debugapi/chequebook.go
Labels: pull-request, ready for review

#1012 manifest: dont override mantaray.ErrNotFound
  pkg/manifest/mantaray.go
Labels: pull-request

#1003 rename folders for brew to swarm-bee
  .goreleaser.yml
  packaging/homebrew/bee-get-addr
  packaging/homebrew/bee.yaml
Labels: pull-request, ready for review

#1011 Pushsync should not blocklist peer
  pkg/pushsync/pushsync.go
Labels: pull-request

#1013 nicer package post install output
  .goreleaser.yml
  packaging/bee-get-addr
  packaging/deb/postinst
  packaging/homebrew/bee-get-addr
  packaging/rpm/post
Labels: pull-request, ready for review

#1016 pushsync: log more information on failure
  pkg/pushsync/pushsync.go
Labels: pull-request

#1015 Update 'dirs' API document headers descriptions
  openapi/Swarm.yaml
Labels: pull-request, ready for review

#998 Openapi update
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
Labels: pull-request

#1017 Remove period from log output
  pkg/settlement/swap/chequebook/init.go
Labels: pull-request

#1018 Typo fix
  openapi/SwarmCommon.yaml
Labels: pull-request

#1021 Homebrew token
  .github/workflows/release.yaml
Labels: pull-request

#1020 kademlia: hotfix for peer list inconsistency
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
Labels: bug, pull-request

#1014 version: bump to v0.4.0
  version.go
Labels: pull-request, ready for review

#1022 version: bump to v0.4.1
  version.go
Labels: pull-request
