Repository ethersphere/bee, pull requests merged in 2020-07, with the labels that each got.

#339 Use files join code in bytes
  pkg/api/bytes.go
Labels: clean-up, ready for review

#398 consistency in cli boolean flags
  cmd/bee/cmd/start.go
Labels: ready for review

#401 Handle zombie streams with fullclose - pingpong
  pkg/pingpong/pingpong.go
Labels: ready for review

#404 puller: fix live sync test flake
  pkg/puller/puller_test.go
Labels: ready for review

#405 Minor handshake refactor - streams
  pkg/p2p/libp2p/libp2p.go
Labels: ready for review

#407 Stream reset initial implementation
  pkg/p2p/libp2p/internal/handshake/mock/stream.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/p2p.go
  pkg/p2p/protobuf/protobuf_test.go
  pkg/p2p/streamtest/streamtest.go
Labels: ready for review

#252 p2p, kademlia: cleanup connect logic
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/peer.go
  pkg/debugapi/peer_test.go
  pkg/node/node.go
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/mock/mock.go
  pkg/p2p/p2p.go
  pkg/topology/topology.go
Labels: ready for review

#411 puller: extract maxpo and shallow bin peers
  pkg/node/node.go
  pkg/puller/export_test.go
  pkg/puller/puller.go
  pkg/puller/puller_test.go
  pkg/swarm/swarm.go
Labels: clean-up, ready for review

#414 puller: exit on nextInterval error
  pkg/puller/puller.go
Labels: clean-up, ready for review

#320 Porting Swarm encryption in Bee
  cmd/bee-file/main.go
  cmd/bee-join/main.go
  cmd/bee-split/main.go
  go.sum
  pkg/api/bytes.go
  pkg/api/file.go
  pkg/api/file_test.go
  pkg/encryption/encryption.go
  pkg/encryption/encryption_test.go
  pkg/file/file.go
  pkg/file/file_test.go
  pkg/file/joiner/internal/job.go
  pkg/file/joiner/internal/job_test.go
  pkg/file/joiner/joiner.go
  pkg/file/joiner/joiner_test.go
  pkg/file/splitter/internal/job.go
  pkg/file/splitter/internal/job_test.go
  pkg/file/splitter/splitter.go
  pkg/file/splitter/splitter_test.go
Labels: ready for review

#334 Fix getting tags by address in pusher
  pkg/node/node.go
  pkg/pusher/pusher.go
  pkg/pusher/pusher_test.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
Labels: ready for review

#412 Kademlia: use swarm.MaxBins
  pkg/kademlia/export_test.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
Labels: clean-up, ready for review

#410 group pull errors in node shutdown
  pkg/node/node.go
Labels: ready for review

#422 Pushsync - stream reset
  pkg/pushsync/pushsync.go
Labels: ready for review

#421 Retreival - stream reset
  pkg/retrieval/retrieval.go
Labels: ready for review

#420 Stream reset - hive
  pkg/hive/hive.go
Labels: ready for review

#424 pullsync, puller: add metrics
  pkg/puller/metrics.go
  pkg/puller/puller.go
  pkg/pullsync/metrics.go
  pkg/pullsync/pullsync.go
Labels: clean-up, ready for review

#436 Makefile: Added build for other binaries in BEE
  Makefile
Labels: feature, ready for review

#438 fix broken retrieval test to implement EachPeerRev instead of EachPeer
  pkg/retrieval/retrieval_test.go
Labels: ready for review

#429 Trojan chunk support
  pkg/crypto/crypto.go
  pkg/file/file.go
  pkg/file/splitter/internal/job.go
  pkg/swarm/swarm.go
  pkg/trojan/error.go
  pkg/trojan/export_test.go
  pkg/trojan/message.go
  pkg/trojan/message_test.go
Labels: global pinning, ready for review

#434 add initial accounting for retrieval
  cmd/bee/cmd/start.go
  pkg/accounting/accounting.go
  pkg/accounting/accounting_test.go
  pkg/accounting/mock/accounting.go
  pkg/accounting/mock/pricer.go
  pkg/accounting/pricer.go
  pkg/node/node.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
Labels: ready for review

#452 Support manifest traversal
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/bytes.go
  pkg/api/bzz.go
  pkg/api/bzz_test.go
  pkg/api/file.go
  pkg/api/router.go
  pkg/manifest/jsonmanifest/json.go
  pkg/manifest/manifest.go
  pkg/node/node.go
Labels: ready for review

#347 Introduce soc validator
  go.mod
  go.sum
  pkg/content/content.go
  pkg/content/content_test.go
  pkg/content/validator.go
  pkg/content/validator_test.go
  pkg/crypto/crypto.go
  pkg/node/node.go
  pkg/soc/export_test.go
  pkg/soc/soc.go
  pkg/soc/soc_test.go
  pkg/soc/validator.go
  pkg/soc/validator_test.go
  pkg/swarm/swarm.go
  pkg/validator/validator.go
Labels: feature, ready for review

#469 run lint and vet only for ubuntu
  .github/workflows/go.yml
Labels: ready for review

#470 Add soc validator to node
  pkg/content/validator.go
  pkg/content/validator_test.go
  pkg/node/node.go
  pkg/soc/validator.go
  pkg/soc/validator_test.go
Labels: feature, ready for review

#475 fix TestSocValidator test
  pkg/soc/validator_test.go
Labels: ready for review

#472 Fix file upload/download during encryption
  pkg/api/file_test.go
  pkg/collection/entry/entry.go
  pkg/encryption/encryption_test.go
  pkg/file/joiner/joiner.go
  pkg/file/splitter/internal/job.go
  pkg/jsonhttp/jsonhttptest/jsonhttptest.go
  pkg/swarm/swarm.go
Labels: ready for review

#430 api, file, netstore: add targets to query param on download path
  cmd/bee-file/main.go
  cmd/bee-join/main.go
  pkg/api/api.go
  pkg/api/bytes_test.go
  pkg/api/bzz.go
  pkg/api/chunk.go
  pkg/api/chunk_test.go
  pkg/api/file.go
  pkg/api/file_test.go
  pkg/file/file.go
  pkg/file/file_test.go
  pkg/netstore/netstore.go
  pkg/netstore/netstore_test.go
  pkg/node/node.go
Labels: ready for review

#484 file: disable hanging tests
  pkg/file/testing/vector.go
Labels: flaky-test, ready for review

#447 api: upload directory
  pkg/api/dirs.go
  pkg/api/dirs_test.go
  pkg/api/export_test.go
  pkg/api/file.go
  pkg/api/router.go
Labels: ready for review

#393 Add create tags in /files and /bytes API
  pkg/api/bytes.go
  pkg/api/chunk.go
  pkg/api/file.go
  pkg/debugapi/tag_test.go
  pkg/file/splitter/internal/job.go
  pkg/file/splitter/splitter.go
  pkg/netstore/netstore_test.go
  pkg/pusher/pusher_test.go
  pkg/storage/mock/validator/validator.go
  pkg/tags/tags.go
Labels: in progress, ready for review

#496 netstore: removed log from get
  pkg/netstore/netstore.go
Labels: bug

#487 github: add pullsync integration tests to ci flow
  .github/workflows/beekeeper.yaml
Labels: ready for review

#493 Fix panic in tags debug api
  pkg/api/bytes.go
  pkg/api/file.go
  pkg/file/splitter/internal/job.go
  pkg/node/node.go
Labels: bug, ready for review

#504 api: rename bzz: path segment to bzz
  pkg/api/bzz_test.go
  pkg/api/router.go
Labels: ready for review

#495 manifest, jsonmanifest, api, node: add encoding marshaling to manifest interface
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/bzz.go
  pkg/api/bzz_test.go
  pkg/api/dirs.go
  pkg/api/dirs_test.go
  pkg/manifest/jsonmanifest/entry.go
  pkg/manifest/jsonmanifest/json.go
  pkg/manifest/jsonmanifest/manifest.go
  pkg/manifest/manifest.go
  pkg/node/node.go
Labels: clean-up, ready for review
