Repository ethersphere/bee, pull requests merged in 2020-09, with the labels that each got.

#673 move chunks-pin endpoints from debugapi to api
  openapi/Swarm.yaml
  openapi/SwarmDebug.yaml
  pkg/api/export_test.go
  pkg/api/pin.go
  pkg/api/pin_test.go
  pkg/api/router.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/export_test.go
  pkg/debugapi/router.go
Labels: ready for review

#675 api gateway mode
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  cmd/internal/file/io_test.go
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/gatewaymode_test.go
  pkg/api/router.go
  pkg/node/node.go
Labels: ready for review

#628 Block potentially misbehaving peers
  pkg/node/node.go
  pkg/p2p/error.go
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/internal/blocklist/blocklist.go
  pkg/p2p/libp2p/internal/blocklist/blocklist_test.go
  pkg/p2p/libp2p/internal/blocklist/export_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/libp2p_test.go
  pkg/p2p/mock/mock.go
  pkg/p2p/p2p.go
Labels: ready for review

#672 add opentracing instrumentation to http package
  pkg/api/api.go
  pkg/api/bytes.go
  pkg/api/bzz.go
  pkg/api/dirs.go
  pkg/api/file.go
  pkg/api/router.go
Labels: ready for review

#684 add git commit to version and expose version in debugapi
  Makefile
  pkg/debugapi/status.go
  pkg/debugapi/status_test.go
Labels: ready for review

#601 settlement persistence and debug api
  pkg/accounting/accounting_test.go
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/export_test.go
  pkg/debugapi/router.go
  pkg/debugapi/settlements.go
  pkg/debugapi/settlements_test.go
  pkg/node/node.go
  pkg/settlement/interface.go
  pkg/settlement/pseudosettle/mock/pseudosettle.go
  pkg/settlement/pseudosettle/pseudosettle.go
  pkg/settlement/pseudosettle/pseudosettle_test.go
Labels: ready for review

#677 integrate clef signer
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  pkg/crypto/clef/clef.go
  pkg/crypto/clef/clef_test.go
  pkg/crypto/clef/export_test.go
  pkg/crypto/crypto.go
  pkg/crypto/signer.go
  pkg/crypto/signer_test.go
  pkg/node/node.go
Labels: ready for review

#685 blocklist peer on retrieval timeout
  pkg/node/node.go
  pkg/p2p/p2p.go
  pkg/p2p/streamtest/streamtest.go
  pkg/recovery/repair_test.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
Labels: ready for review

#692 Revert "blocklist peer on retrieval timeout (#685)"
  pkg/node/node.go
  pkg/p2p/p2p.go
  pkg/p2p/streamtest/streamtest.go
  pkg/recovery/repair_test.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
Labels: ready for review

#693 log pss error instead of stream reset
  pkg/pushsync/pushsync.go
Labels: ready for review

#690 implement swarm-index dirs api option as default path
  openapi/Swarm.yaml
  pkg/api/api.go
  pkg/api/bzz.go
  pkg/api/dirs.go
  pkg/api/dirs_test.go
  pkg/api/router.go
Labels: ready for review

#694 block peers on disconnect threshold
  pkg/accounting/accounting.go
  pkg/accounting/accounting_test.go
Labels: ready for review

#696 Distinguish no balance for peer
  pkg/accounting/accounting.go
  pkg/debugapi/balances.go
  pkg/debugapi/balances_test.go
  pkg/debugapi/export_test.go
Labels: ready for review

#695 trojan,pss: optimise trojan mining
  pkg/pss/pss.go
  pkg/pss/pss_test.go
  pkg/trojan/error.go
  pkg/trojan/export_test.go
  pkg/trojan/message.go
  pkg/trojan/message_test.go
  pkg/trojan/mining_test.go
Labels: enhancement, ready for review

#686 api: add pss websockets api
  cmd/internal/file/io_test.go
  go.mod
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/bytes_test.go
  pkg/api/bzz_test.go
  pkg/api/chunk_test.go
  pkg/api/dirs_test.go
  pkg/api/file_test.go
  pkg/api/gatewaymode_test.go
  pkg/api/pin_test.go
  pkg/api/pss.go
  pkg/api/pss_test.go
  pkg/api/router.go
  pkg/api/tag_test.go
  pkg/logging/http_access.go
  pkg/node/node.go
  pkg/pss/pss.go
  pkg/pss/pss_test.go
  pkg/pushsync/mock/mock.go
  pkg/recovery/export_test.go
  pkg/recovery/repair.go
  pkg/recovery/repair_test.go
Labels: ready for review

#642 Safety checks in accounting
  pkg/accounting/accounting.go
  pkg/accounting/accounting_test.go
  pkg/accounting/metrics.go
  pkg/accounting/pricer.go
Labels: ready for review

#707 kademlia: TestClosestPeer wait for peers to be added to the backing data structure
  pkg/kademlia/kademlia_test.go
Labels: flaky-test, ready for review

#700 pipeline hashing: refactor to different packages
  pkg/api/bytes.go
  pkg/api/bzz_test.go
  pkg/api/dirs.go
  pkg/api/file.go
  pkg/encryption/chunk_encryption.go
  pkg/encryption/mock/chunk_encryption.go
  pkg/file/file_test.go
  pkg/file/pipeline/bmt/bmt.go
  pkg/file/pipeline/bmt/bmt_test.go
  pkg/file/pipeline/bmt/export_test.go
  pkg/file/pipeline/builder/builder.go
  pkg/file/pipeline/builder/builder_test.go
  pkg/file/pipeline/encryption/encryption.go
  pkg/file/pipeline/encryption/encryption_test.go
  pkg/file/pipeline/encryption_writer.go
  pkg/file/pipeline/feeder/feeder.go
  pkg/file/pipeline/feeder/feeder_test.go
  pkg/file/pipeline/hashtrie/hashtrie.go
  pkg/file/pipeline/mock/writer.go
  pkg/file/pipeline/pipeline.go
  pkg/file/pipeline/store/export_test.go
  pkg/file/pipeline/store/store.go
  pkg/file/pipeline/store/store_test.go
  pkg/file/pipeline/writer.go
  pkg/file/seekjoiner/joiner_test.go
  pkg/manifest/mantaray.go
  pkg/manifest/simple.go
Labels: ready for review

#705 suggest only downstream peers in retrieval forwarding
  pkg/node/node.go
  pkg/recovery/repair_test.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
Labels: ready for review

#714 retrieval, pushsync: add tracing
  pkg/node/node.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/recovery/repair_test.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
Labels: ready for review

#703 chequebook deployment
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  go.mod
  go.sum
  pkg/crypto/clef/clef.go
  pkg/crypto/clef/clef_test.go
  pkg/crypto/signer.go
  pkg/crypto/signer_test.go
  pkg/node/node.go
  pkg/settlement/swap/chequebook/bindings.go
  pkg/settlement/swap/chequebook/chequebook.go
  pkg/settlement/swap/chequebook/chequebook_test.go
  pkg/settlement/swap/chequebook/common_test.go
  pkg/settlement/swap/chequebook/factory.go
  pkg/settlement/swap/chequebook/factory_test.go
  pkg/settlement/swap/chequebook/init.go
  pkg/settlement/swap/chequebook/transaction.go
  pkg/settlement/swap/chequebook/transaction_test.go
Labels: ready for review

#718 Chequebook endpoint
  pkg/debugapi/chequebook.go
  pkg/debugapi/chequebook_test.go
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/export_test.go
  pkg/debugapi/router.go
  pkg/node/node.go
  pkg/settlement/swap/chequebook/chequebook_test.go
  pkg/settlement/swap/chequebook/mock/chequebook.go
Labels: ready for review

#720 add cheque signing
  cmd/bee/cmd/start.go
  pkg/crypto/clef/clef.go
  pkg/crypto/clef/clef_test.go
  pkg/crypto/eip712/typeddata.go
  pkg/crypto/signer.go
  pkg/crypto/signer_test.go
  pkg/node/node.go
  pkg/settlement/swap/chequebook/cheque.go
  pkg/settlement/swap/chequebook/cheque_test.go
  pkg/settlement/swap/chequebook/chequebook.go
  pkg/settlement/swap/chequebook/chequebook_test.go
  pkg/settlement/swap/chequebook/common_test.go
  pkg/settlement/swap/chequebook/factory.go
  pkg/settlement/swap/chequebook/init.go
  pkg/settlement/swap/chequebook/mock/chequebook.go
  pkg/settlement/swap/chequebook/transaction.go
  pkg/settlement/swap/chequebook/transaction_test.go
Labels: ready for review

#729 pushsync: fix tracing
  pkg/pusher/pusher.go
  pkg/pushsync/pushsync.go
  pkg/retrieval/retrieval.go
  pkg/tracing/tracing.go
Labels: bug

#722 Granular notifiers in protocol spec
  pkg/debugapi/peer.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/node/node.go
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/libp2p_test.go
  pkg/p2p/libp2p/peer.go
  pkg/p2p/libp2p/protocols_test.go
  pkg/p2p/mock/mock.go
  pkg/p2p/p2p.go
  pkg/topology/topology.go
Labels: ready for review

#716 pushsync: remove some indirection and redundant error logging
  pkg/node/node.go
  pkg/pushsync/pushsync.go
Labels: clean-up, ready for review

#727 crypto: add ECDH shared secret support, in memory variant
  pkg/crypto/dh.go
  pkg/crypto/dh_test.go
  pkg/encryption/encryption.go
  pkg/encryption/encryption_test.go
Labels: ready for review

#743 include peer information in reserve error
  pkg/pushsync/pushsync.go
Labels: ready for review

#713 Add support for manifest metadata
  go.mod
  go.sum
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/bzz.go
  pkg/api/bzz_test.go
  pkg/api/dirs.go
  pkg/api/dirs_test.go
  pkg/api/export_test.go
  pkg/manifest/manifest.go
  pkg/manifest/mantaray.go
  pkg/manifest/simple.go
Labels: enhancement, ready for review

#742 allow first retrieval request to be upstream
  pkg/retrieval/retrieval.go
Labels: ready for review

#728 simple El-Gamal encryption for trojan chunks
  pkg/encryption/elgamal/encryption.go
  pkg/encryption/elgamal/encryption_test.go
  pkg/encryption/encryption.go
  pkg/encryption/mock/mock.go
Labels: builds on open pr, ready for review

#744 update smart contract bindings to latest version
  go.mod
  go.sum
Labels: ready for review

#746 pusher: add tracing
  pkg/node/node.go
  pkg/pusher/pusher.go
  pkg/pusher/pusher_test.go
Labels: ready for review

#732 swap cheque exchange protocol and settlement
  pkg/accounting/accounting_test.go
  pkg/crypto/crypto.go
  pkg/debugapi/settlements.go
  pkg/node/node.go
  pkg/settlement/interface.go
  pkg/settlement/pseudosettle/mock/pseudosettle.go
  pkg/settlement/pseudosettle/pseudosettle.go
  pkg/settlement/swap/addressbook.go
  pkg/settlement/swap/chequebook/bindings.go
  pkg/settlement/swap/chequebook/cheque.go
  pkg/settlement/swap/chequebook/chequebook.go
  pkg/settlement/swap/chequebook/chequebook_test.go
  pkg/settlement/swap/chequebook/chequestore.go
  pkg/settlement/swap/chequebook/chequestore_test.go
  pkg/settlement/swap/chequebook/common_test.go
  pkg/settlement/swap/chequebook/mock/chequebook.go
  pkg/settlement/swap/chequestore/mock/chequestore.go
  pkg/settlement/swap/metrics.go
  pkg/settlement/swap/swap.go
  pkg/settlement/swap/swap_test.go
  pkg/settlement/swap/swapprotocol/pb/doc.go
  pkg/settlement/swap/swapprotocol/pb/swap.pb.go
  pkg/settlement/swap/swapprotocol/pb/swap.proto
  pkg/settlement/swap/swapprotocol/swapprotocol.go
Labels: ready for review

#667 seekjoiner: fill read buffer, integrate langos
  go.mod
  go.sum
  pkg/api/api.go
  pkg/api/file.go
  pkg/file/file.go
  pkg/file/seekjoiner/internal/job.go
  pkg/file/seekjoiner/internal/job_test.go
  pkg/file/seekjoiner/joiner.go
Labels: ready for review

#736 add configuration for goerli
  pkg/node/node.go
  pkg/settlement/swap/chequebook/factory.go
Labels: ready for review

#747 api, netstore: dont set empty targets, return correct errors from netstore
  pkg/api/bzz.go
  pkg/api/chunk.go
  pkg/api/file.go
  pkg/netstore/netstore.go
  pkg/netstore/netstore_test.go
  pkg/recovery/repair_test.go
  pkg/sctx/sctx.go
Labels: clean-up, ready for review

#737 Pss encryption and topic matching, refactor, cleaner test
  go.sum
  pkg/api/pss.go
  pkg/api/pss_test.go
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
  pkg/encryption/elgamal/encryption.go
  pkg/encryption/elgamal/encryption_test.go
  pkg/netstore/netstore_test.go
  pkg/node/node.go
  pkg/pss/export_test.go
  pkg/pss/mining_test.go
  pkg/pss/pss.go
  pkg/pss/pss_test.go
  pkg/pss/trojan.go
  pkg/pss/trojan_test.go
  pkg/recovery/repair.go
  pkg/recovery/repair_test.go
  pkg/sctx/sctx.go
  pkg/trojan/error.go
  pkg/trojan/export_test.go
  pkg/trojan/message.go
  pkg/trojan/message_test.go
Labels: ready for review

#748 pusher: increase concurrent chunk jobs
  pkg/pusher/pusher.go
Labels: clean-up

#739 check available balance when issuing cheques
  pkg/debugapi/chequebook.go
  pkg/debugapi/chequebook_test.go
  pkg/settlement/swap/chequebook/bindings.go
  pkg/settlement/swap/chequebook/chequebook.go
  pkg/settlement/swap/chequebook/chequebook_test.go
  pkg/settlement/swap/chequebook/common_test.go
  pkg/settlement/swap/chequebook/mock/chequebook.go
  pkg/settlement/swap/swap.go
  pkg/settlement/swap/swap_test.go
Labels: ready for review

#749 fix goerli factory address
  pkg/settlement/swap/chequebook/factory.go
  pkg/settlement/swap/chequebook/init.go
Labels: ready for review

#751 add early payment to NewBee
  cmd/bee/cmd/start.go
Labels: ready for review

#750 expose swarm public key in logs and debugapi
  cmd/bee/cmd/start.go
  openapi/SwarmCommon.yaml
  pkg/crypto/crypto.go
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/p2p.go
  pkg/debugapi/p2p_test.go
  pkg/node/node.go
Labels: ready for review

#754 Pss trojan length check and no error return in delivery callback
  pkg/api/pss_test.go
  pkg/node/node.go
  pkg/pss/pss.go
  pkg/pss/pss_test.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
Labels: ready for review

#585 announce payment threshold through pricing protocol
  pkg/accounting/accounting.go
  pkg/accounting/accounting_test.go
  pkg/node/node.go
  pkg/pricing/pb/doc.go
  pkg/pricing/pb/pricing.pb.go
  pkg/pricing/pb/pricing.proto
  pkg/pricing/pricing.go
  pkg/pricing/pricing_test.go
Labels: ready for review

#755 remove duplicate log and demote to trace
  pkg/pricing/pricing.go
Labels: ready for review

#758 account for totalPaidOut in liquidity check
  pkg/settlement/swap/chequebook/bindings.go
  pkg/settlement/swap/chequebook/chequestore.go
  pkg/settlement/swap/chequebook/chequestore_test.go
  pkg/settlement/swap/chequebook/common_test.go
Labels: ready for review

#759 Enable geth infra tests
  .github/workflows/beekeeper.yaml
Labels: ready for review

#761 Swap ux improvements
  pkg/node/node.go
  pkg/settlement/swap/chequebook/common_test.go
  pkg/settlement/swap/chequebook/factory.go
  pkg/settlement/swap/chequebook/factory_test.go
  pkg/settlement/swap/chequebook/init.go
Labels: ready for review

#735 Lastcheque endpoints
  pkg/debugapi/chequebook.go
  pkg/debugapi/chequebook_test.go
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/export_test.go
  pkg/debugapi/router.go
  pkg/node/node.go
  pkg/settlement/swap/mock/swap.go
  pkg/settlement/swap/swap.go
Labels: ready for review

#740 cashout cheques
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
  pkg/debugapi/chequebook.go
  pkg/debugapi/chequebook_test.go
  pkg/debugapi/export_test.go
  pkg/debugapi/router.go
  pkg/node/node.go
  pkg/settlement/swap/chequebook/bindings.go
  pkg/settlement/swap/chequebook/cashout.go
  pkg/settlement/swap/chequebook/cashout_test.go
  pkg/settlement/swap/chequebook/common_test.go
  pkg/settlement/swap/chequebook/transaction.go
  pkg/settlement/swap/mock/swap.go
  pkg/settlement/swap/swap.go
  pkg/settlement/swap/swap_test.go
Labels: ready for review

#760 add withdraw and deposit endpoints
  openapi/SwarmDebug.yaml
  pkg/debugapi/chequebook.go
  pkg/debugapi/chequebook_test.go
  pkg/debugapi/export_test.go
  pkg/debugapi/router.go
  pkg/settlement/swap/chequebook/chequebook.go
  pkg/settlement/swap/chequebook/chequebook_test.go
  pkg/settlement/swap/chequebook/mock/chequebook.go
Labels: ready for review

#762 enable swap by default
  cmd/bee/cmd/cmd.go
Labels: ready for review

#771 add ethereum address to /addresses
  openapi/SwarmCommon.yaml
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/p2p.go
  pkg/debugapi/p2p_test.go
  pkg/node/node.go
Labels: ready for review

#767 retrieval: remove test that forbids upstream request
  pkg/retrieval/retrieval_test.go
Labels: bug

#770 chequebook and payment threshold logging fixes
  pkg/pricing/pricing.go
  pkg/settlement/swap/chequebook/init.go
Labels: ready for review

#772 Upgrade 'ethersphere/manifest' to v0.3.2
  go.mod
  go.sum
Labels: ready for review

#773 Oas fix
  openapi/Swarm.yaml
Labels: ready for review

#774 update resolver options cli flag help message
  cmd/bee/cmd/cmd.go
Labels: ready for review

#775 better error if no backend
  pkg/node/node.go
Labels: ready for review

#776 Bump version in OpenAPI specification to 0.3.0
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
Labels: ready for review

#777 Goerli-specific logs
  pkg/node/node.go
  pkg/settlement/swap/chequebook/init.go
Labels: ready for review

#778 default initial deposit
  cmd/bee/cmd/cmd.go
Labels: ready for review

#779 fix warning log message format it hive
  pkg/hive/hive.go
Labels: ready for review
