Repository ethersphere/bee, pull requests merged in 2020-04, with the labels that each got.

#44 add debugapi /addresses endpoint to expose libp2p mutiaddresses
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/export_test.go
  pkg/debugapi/p2p.go
  pkg/debugapi/p2p_test.go
  pkg/debugapi/router.go
  pkg/p2p/mock/mock.go
  pkg/p2p/p2p.go
Labels: ready for review

#46 bootnode init improvement + libp2p incoming connection addr fix
  pkg/addressbook/inmem/inmem.go
  pkg/hive/hive.go
  pkg/node/node.go
  pkg/p2p/libp2p/libp2p.go
  pkg/topology/full/full.go
Labels: ready for review

#32 api, storage: add http interface to accept chunks
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/bzzchunk.go
  pkg/api/bzzchunk_test.go
  pkg/api/router.go
  pkg/node/node.go
  pkg/storage/mock/storer.go
  pkg/storage/mock/storer_test.go
  pkg/storage/store.go
Labels: ready for review

#76 set golangci-lint timeout to 10m
  .golangci.yml
Labels: ready for review

#68 statestore: add initial implementation
  go.mod
  go.sum
  pkg/statestore/store.go
  pkg/statestore/test/store_test.go
  pkg/storage/store.go
Labels: ready for review

#54 add CODING.md
  CODING.md
  README.md
Labels: documentation, ready for review

#80 fix metrics names in logging and pingpong
  pkg/logging/metrics.go
  pkg/pingpong/metrics.go
Labels: ready for review

#78 add debug api overlay address endpoint
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/p2p.go
  pkg/debugapi/p2p_test.go
  pkg/node/node.go
Labels: ready for review

#74 P4 - Replace log from ethereum to bee's own log library
  pkg/shed/db.go
  pkg/shed/db_test.go
  pkg/shed/example_store_test.go
  pkg/shed/field_string.go
  pkg/shed/field_string_test.go
  pkg/shed/field_struct.go
  pkg/shed/field_struct_test.go
  pkg/shed/field_uint64.go
  pkg/shed/field_uint64_test.go
  pkg/shed/index.go
  pkg/shed/index_test.go
  pkg/shed/vector_uint64.go
  pkg/shed/vector_uint64_test.go
Labels: ready for review

#85 add p2p.Peer json tag to Address field as it is returned by debug api
  pkg/p2p/p2p.go
Labels: ready for review

#75 P5 - Replace levelDB with badgerDB in shed
  .gitignore
  go.mod
  go.sum
  pkg/shed/db.go
  pkg/shed/example_store_test.go
  pkg/shed/field_string.go
  pkg/shed/field_string_test.go
  pkg/shed/field_struct.go
  pkg/shed/field_struct_test.go
  pkg/shed/field_uint64.go
  pkg/shed/field_uint64_test.go
  pkg/shed/index.go
  pkg/shed/index_test.go
  pkg/shed/metrics.go
  pkg/shed/vector_uint64.go
  pkg/shed/vector_uint64_test.go
Labels: ready for review

#86 Flacky tests - NewStream
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/p2p/libp2p/libp2p.go
Labels: ready for review

#82 P6 - get the locastore from swarm to bee
  Makefile
  go.mod
  go.sum
  pkg/storage/localstore/doc.go
  pkg/storage/localstore/export.go
  pkg/storage/localstore/export_test.go
  pkg/storage/localstore/gc.go
  pkg/storage/localstore/gc_test.go
  pkg/storage/localstore/index_test.go
  pkg/storage/localstore/localstore.go
  pkg/storage/localstore/localstore_test.go
  pkg/storage/localstore/migration.go
  pkg/storage/localstore/migration_test.go
  pkg/storage/localstore/mode_get.go
  pkg/storage/localstore/mode_get_multi.go
  pkg/storage/localstore/mode_get_multi_test.go
  pkg/storage/localstore/mode_get_test.go
  pkg/storage/localstore/mode_has.go
  pkg/storage/localstore/mode_has_test.go
  pkg/storage/localstore/mode_put.go
  pkg/storage/localstore/mode_put_test.go
  pkg/storage/localstore/mode_set.go
  pkg/storage/localstore/mode_set_test.go
  pkg/storage/localstore/retrieval_index_test.go
  pkg/storage/localstore/schema.go
  pkg/storage/localstore/subscription_pull.go
  pkg/storage/localstore/subscription_pull_test.go
  pkg/storage/localstore/subscription_push.go
  pkg/storage/localstore/subscription_push_test.go
  pkg/storage/localstore/testdata/sanctuary/000002.log
  pkg/storage/localstore/testdata/sanctuary/CURRENT
  pkg/storage/localstore/testdata/sanctuary/CURRENT.bak
  pkg/storage/localstore/testdata/sanctuary/LOCK
  pkg/storage/localstore/testdata/sanctuary/LOG
  pkg/storage/localstore/testdata/sanctuary/MANIFEST-000003
Labels: ready for review

#87 9/12: localstore migration - remove legacy migration code
  pkg/storage/localstore/export.go
  pkg/storage/localstore/migration.go
  pkg/storage/localstore/migration_test.go
  pkg/storage/localstore/schema.go
  pkg/storage/localstore/testdata/sanctuary/000002.log
  pkg/storage/localstore/testdata/sanctuary/CURRENT
  pkg/storage/localstore/testdata/sanctuary/CURRENT.bak
  pkg/storage/localstore/testdata/sanctuary/LOCK
  pkg/storage/localstore/testdata/sanctuary/LOG
  pkg/storage/localstore/testdata/sanctuary/MANIFEST-000003
Labels: ready for review

#89 10/12: replace ethersphere/swarm/chunk and related types with bee ones
  pkg/shed/example_store_test.go
  pkg/storage/localstore/export.go
  pkg/storage/localstore/export_test.go
  pkg/storage/localstore/gc_test.go
  pkg/storage/localstore/index_test.go
  pkg/storage/localstore/localstore.go
  pkg/storage/localstore/localstore_test.go
  pkg/storage/localstore/mode_get.go
  pkg/storage/localstore/mode_get_multi.go
  pkg/storage/localstore/mode_get_multi_test.go
  pkg/storage/localstore/mode_get_test.go
  pkg/storage/localstore/mode_has.go
  pkg/storage/localstore/mode_has_test.go
  pkg/storage/localstore/mode_put.go
  pkg/storage/localstore/mode_put_test.go
  pkg/storage/localstore/mode_set.go
  pkg/storage/localstore/mode_set_test.go
  pkg/storage/localstore/retrieval_index_test.go
  pkg/storage/localstore/subscription_pull.go
  pkg/storage/localstore/subscription_pull_test.go
  pkg/storage/localstore/subscription_push.go
  pkg/storage/localstore/subscription_push_test.go
  pkg/storage/store.go
  pkg/storage/testing/chunk.go
  pkg/swarm/proximity.go
  pkg/swarm/proximity_test.go
  pkg/swarm/swarm.go
  pkg/tags/tag.go
  pkg/tags/tag_test.go
  pkg/tags/tags.go
  pkg/tags/tags_test.go
  pkg/tags/testing/tag.go
Labels: ready for review

#91 10/12 part 2: remove spancontext dependency, remove mockstore, migrate sctx
  Makefile
  go.mod
  pkg/sctx/sctx.go
  pkg/storage/localstore/localstore.go
  pkg/tags/tag.go
  pkg/tags/tag_test.go
  pkg/tags/tags.go
Labels: ready for review

#92 11/12 integrate bee shed in localstore
  Makefile
  go.mod
  go.sum
  pkg/shed/db.go
  pkg/shed/db_test.go
  pkg/shed/example_store_test.go
  pkg/shed/field_string.go
  pkg/shed/field_string_test.go
  pkg/shed/field_struct.go
  pkg/shed/field_struct_test.go
  pkg/shed/field_uint64.go
  pkg/shed/field_uint64_test.go
  pkg/shed/index.go
  pkg/shed/index_test.go
  pkg/shed/vector_uint64.go
  pkg/shed/vector_uint64_test.go
  pkg/storage/localstore/doc.go
  pkg/storage/localstore/export.go
  pkg/storage/localstore/gc.go
  pkg/storage/localstore/gc_test.go
  pkg/storage/localstore/localstore.go
  pkg/storage/localstore/localstore_test.go
  pkg/storage/localstore/mode_get.go
  pkg/storage/localstore/mode_get_multi.go
  pkg/storage/localstore/mode_put.go
  pkg/storage/localstore/mode_put_test.go
  pkg/storage/localstore/mode_set.go
  pkg/storage/localstore/mode_set_test.go
  pkg/storage/localstore/subscription_pull.go
  pkg/storage/localstore/subscription_pull_test.go
  pkg/storage/localstore/subscription_push.go
  pkg/storage/localstore/subscription_push_test.go
Labels: ready for review

#94 Integrate localstore to bee
  pkg/api/bzzchunk.go
  pkg/localstore/localstore.go
  pkg/node/node.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
  pkg/storage/mock/storer.go
  pkg/storage/mock/storer_test.go
  pkg/storage/store.go
Labels: ready for review

#90 Tests time improvement
  pkg/hive/hive_test.go
  pkg/p2p/libp2p/libp2p_test.go
  pkg/p2p/protobuf/protobuf_test.go
Labels: ready for review

#96 Init topology driver
  pkg/addressbook/addressbook.go
  pkg/hive/hive_test.go
  pkg/node/node.go
Labels: ready for review

#95 Add in-memory support for testing using DB
  Makefile
  pkg/localstore/localstore_test.go
  pkg/localstore/mode_put_test.go
  pkg/node/node.go
  pkg/shed/db.go
  pkg/shed/db_test.go
  pkg/shed/example_store_test.go
Labels: ready for review

#101 fix errors reported by deepsource
  cmd/bee/cmd/cmd_test.go
  pkg/hive/hive.go
  pkg/localstore/localstore.go
  pkg/shed/example_store_test.go
  pkg/statestore/test/store.go
  pkg/storage/testing/chunk.go
Labels: ready for review

#98 Add chunk validation interface and content addressed validator
  go.mod
  go.sum
  pkg/api/bzzchunk_test.go
  pkg/storage/mock/storer.go
  pkg/storage/mock/storer_test.go
  pkg/storage/mock/validator/validator.go
  pkg/storage/store.go
  pkg/swarm/swarm.go
  pkg/validator/validator.go
  pkg/validator/validator_test.go
Labels: enhancement, ready for review

#97 [bee #48] upload syncs to closest - add SyncPeer method
  pkg/node/node.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/swarm/distance.go
  pkg/swarm/distance_test.go
  pkg/topology/full/full.go
  pkg/topology/full/full_test.go
  pkg/topology/topology.go
Labels: ready for review

#111 Add omitted test for mock validator
  pkg/storage/mock/validator/validator.go
  pkg/storage/mock/validator/validator_test.go
Labels: enhancement, ready for review

#109 [bee #49]: get closest peer
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
  pkg/topology/full/full.go
  pkg/topology/full/full_test.go
  pkg/topology/topology.go
Labels: ready for review

#102 disable race detector on windows github actions
  .github/workflows/go.yml
  Makefile
Labels: ready for review

#114 add debug api to expose localstore Has
  pkg/debugapi/chunk.go
  pkg/debugapi/chunk_test.go
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/router.go
  pkg/node/node.go
  pkg/storage/mock/storer.go
  pkg/storage/mock/storer_test.go
Labels: ready for review

#110 Introduce interface for file join and simple implementation
  pkg/file/error.go
  pkg/file/file.go
  pkg/file/joiner/internal/job.go
  pkg/file/joiner/internal/job_test.go
  pkg/file/joiner/joiner.go
  pkg/file/joiner/joiner_test.go
  pkg/file/testing/chunk.go
  pkg/storage/testing/chunk.go
  pkg/swarm/swarm.go
Labels: enhancement, ready for review

#121 Connection Breaker
  pkg/p2p/libp2p/internal/breaker/breaker.go
  pkg/p2p/libp2p/internal/breaker/breaker_test.go
  pkg/p2p/libp2p/internal/breaker/export_test.go
  pkg/p2p/libp2p/libp2p.go
Labels: ready for review

#123 Correct validator hash, bump bmt dep version
  go.mod
  go.sum
  pkg/validator/validator.go
  pkg/validator/validator_test.go
Labels: bug, ready for review

#120 add raw data upload api
  pkg/api/bzz.go
  pkg/api/bzz_test.go
  pkg/api/bzzchunk_test.go
  pkg/api/export_test.go
  pkg/api/router.go
Labels: ready for review

#115 [bee #48] pushsync: initial pushsync implementation
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/peer_test.go
  pkg/p2p/streamtest/streamtest.go
  pkg/pushsync/export_test.go
  pkg/pushsync/metrics.go
  pkg/pushsync/pb/doc.go
  pkg/pushsync/pb/pushsync.pb.go
  pkg/pushsync/pb/pushsync.proto
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/storage/mock/storer.go
  pkg/storage/store.go
  pkg/topology/mock/mock.go
Labels: ready for review
