Repository ethersphere/bee, pull requests merged in 2020-10, with the labels that each got.

#786 actually disconnect on no swap beneficiary
  pkg/node/node.go
  pkg/settlement/swap/swap.go
  pkg/settlement/swap/swap_test.go
Labels: ready for review

#788 puller: fix test flake
  pkg/puller/puller_test.go
Labels: flaky-test, ready for review

#790 api/tag: cleanup tests
  pkg/api/tag_test.go
Labels: clean-up, ready for review

#793 api: standardize error codes
  pkg/api/bytes.go
  pkg/api/bzz.go
  pkg/api/chunk.go
  pkg/api/file.go
Labels: clean-up, ready for review

#795 include rejecting if cheque rejected plus metric
  pkg/settlement/swap/metrics.go
  pkg/settlement/swap/swap.go
Labels: ready for review

#791 accounting: settle in reserve
  pkg/accounting/accounting.go
  pkg/accounting/accounting_test.go
  pkg/accounting/mock/accounting.go
  pkg/pushsync/pushsync.go
  pkg/retrieval/retrieval.go
  pkg/settlement/pseudosettle/mock/pseudosettle.go
Labels: ready for review

#796 fix disconnect non-swap node log
  pkg/settlement/swap/swap.go
Labels: ready for review

#805 decouple retrieval forwarding from netstore
  pkg/node/node.go
  pkg/recovery/repair_test.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
Labels: ready for review

#806 add proper backend mock
  go.sum
  pkg/settlement/swap/chequebook/cashout_test.go
  pkg/settlement/swap/chequebook/chequebook_test.go
  pkg/settlement/swap/chequebook/chequestore_test.go
  pkg/settlement/swap/chequebook/common_test.go
  pkg/settlement/swap/chequebook/factory_test.go
  pkg/settlement/swap/chequebook/transaction_test.go
  pkg/settlement/swap/transaction/backendmock/backend.go
Labels: ready for review

#809 Export additional metrics
  pkg/localstore/metrics.go
  pkg/node/node.go
Labels: ready for review

#817 bump version to 0.3.2
  version.go
Labels: ready for review

#811 propagate context in pushsync receipt message exchange
  pkg/pushsync/pushsync.go
Labels: ready for review

#810 puller, pullsync: fix outstanding tasks
  pkg/puller/puller.go
  pkg/pullsync/mock/pullsync.go
Labels: clean-up, ready for review

#830 fix GitHub actions Beekeeper Get PR Branch step
  .github/workflows/slash-beekeeper.yml
Labels: ready for review

#821 localstore/pin: refactor and add paging
  pkg/api/pin.go
  pkg/localstore/pin.go
  pkg/localstore/pin_test.go
  pkg/storage/mock/storer.go
  pkg/storage/store.go
Labels: clean-up, enhancement, ready for review

#826 blocklist peer on retrieval timeout
  pkg/p2p/p2p.go
  pkg/p2p/streamtest/streamtest.go
  pkg/recovery/repair_test.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
Labels: ready for review

#832 enable github app integration for slash commands
  .github/workflows/slash-beekeeper.yml
Labels: ready for review

#834 use absolute path for golangci-lint in Makfile
  Makefile
Labels: ready for review

#827 Reverse the order of the queue for push sync index
  pkg/localstore/subscription_push.go
  pkg/localstore/subscription_push_test.go
  pkg/shed/index.go
  pkg/shed/index_test.go
Labels: ready for review

#836 add basic pipeline benchmarks
  pkg/file/pipeline/builder/builder_test.go
  pkg/file/splitter/splitter_test.go
Labels: ready for review

#823 all: use bmt hasher pool
  go.mod
  go.sum
  pkg/bmtpool/bmtpool.go
  pkg/content/content.go
  pkg/file/pipeline/bmt/bmt.go
  pkg/file/pipeline/bmt/bmt_test.go
  pkg/file/pipeline/builder/builder.go
  pkg/file/splitter/internal/job.go
  pkg/node/node.go
  pkg/pss/trojan.go
  pkg/swarm/swarm.go
Labels: clean-up, enhancement, ready for review

#837 do not wait for nat manager in standalone mode
  pkg/node/node.go
Labels: ready for review

#838 fix comments in soc package
  pkg/soc/export_test.go
  pkg/soc/soc.go
  pkg/soc/soc_test.go
  pkg/soc/validator.go
  pkg/soc/validator_test.go
Labels: ready for review

#845 Create bug-report template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: pull-request

#846 api: remove anonymous field from tag reply
  pkg/api/tag.go
Labels: clean-up, pull-request, ready for review

#820 expose nat underlay address by p2p service
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/static_resolver.go
Labels: pull-request, ready for review

#840 propagate context to message read and write in p2p protocols
  pkg/hive/hive.go
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/p2p/libp2p/internal/handshake/handshake_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/protobuf/protobuf.go
  pkg/p2p/protobuf/protobuf_test.go
  pkg/p2p/streamtest/streamtest.go
  pkg/pingpong/pingpong.go
  pkg/pricing/pricing.go
  pkg/puller/puller.go
  pkg/pullsync/mock/pullsync.go
  pkg/pullsync/pullsync.go
  pkg/settlement/pseudosettle/pseudosettle.go
  pkg/settlement/pseudosettle/pseudosettle_test.go
  pkg/settlement/swap/swapprotocol/swapprotocol.go
Labels: pull-request, ready for review

#844 Wait until pusher active jobs are done on Close
  pkg/pusher/pusher.go
  pkg/pusher/pusher_test.go
Labels: pull-request, ready for review

#862 add more info to mattermost fail notifications
  .github/workflows/beekeeper.yml
  .github/workflows/slash-beekeeper.yml
Labels: pull-request, ready for review

#863 adjust tests timings in protobuf package
  pkg/p2p/protobuf/protobuf_test.go
Labels: pull-request, ready for review

#860 swapprotocol: don't wait for full close in emitcheque
  pkg/settlement/swap/swapprotocol/swapprotocol.go
Labels: pull-request, ready for review

#861 pipeline: adjust signature to take in Putter instead of Storer
  pkg/file/pipeline/builder/builder.go
  pkg/file/pipeline/store/store.go
Labels: clean-up, pull-request, ready for review

#864 debugapi: fix various error logs
  pkg/debugapi/chequebook.go
  pkg/debugapi/settlements.go
Labels: pull-request, ready for review

#847 file: joiner cleanup
  cmd/bee-file/main.go
  cmd/bee-join/main.go
  pkg/api/bzz.go
  pkg/api/dirs_test.go
  pkg/api/file.go
  pkg/file/file.go
  pkg/file/file_test.go
  pkg/file/io.go
  pkg/file/joiner/joiner.go
  pkg/file/joiner/joiner_test.go
  pkg/file/seekjoiner/joiner.go
  pkg/file/seekjoiner/joiner_test.go
  pkg/manifest/mantaray.go
  pkg/manifest/simple.go
Labels: clean-up, pull-request, ready for review

#865 fix remaining logging formatting issues
  pkg/api/chunk.go
  pkg/api/tag.go
  pkg/debugapi/balances.go
  pkg/p2p/libp2p/libp2p.go
Labels: pull-request, ready for review

#868 disable port reuse in libp2p
  go.mod
  pkg/p2p/libp2p/libp2p.go
Labels: pull-request, ready for review

#869 set http server timeouts
  pkg/node/node.go
Labels: pull-request, ready for review

#866 Update package documentation
  pkg/addressbook/addressbook.go
  pkg/addressbook/doc.go
  pkg/jsonhttp/doc.go
  pkg/jsonhttp/jsonhttptest/doc.go
  pkg/jsonhttp/jsonhttptest/jsonhttptest.go
  pkg/keystore/file/service.go
  pkg/keystore/keystore.go
  pkg/keystore/mem/service.go
  pkg/keystore/test/test.go
  pkg/tracing/doc.go
Labels: pull-request, ready for review

#876 add scheduled run for infra-test
  .github/workflows/schedule.yaml
Labels: pull-request

#880 Revert reversing the iteration order from pushsync
  pkg/localstore/subscription_push.go
  pkg/localstore/subscription_push_test.go
Labels: pull-request, ready for review

#871 Update package documentation
  pkg/pullsync/doc.go
  pkg/pullsync/pullsync.go
Labels: pull-request
