Repository ethersphere/bee, pull requests merged in 2020-05, with the labels that each got.

#146 Rebuild topology when back-off happens
  go.sum
  pkg/node/node.go
  pkg/p2p/error.go
  pkg/p2p/libp2p/internal/breaker/breaker.go
  pkg/p2p/libp2p/internal/breaker/breaker_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/topology/full/full.go
  pkg/topology/full/full_test.go
  pkg/topology/mock/mock.go
  pkg/topology/topology.go
Labels: ready for review

#158 fix api /bzz post endpoint
  pkg/api/bzz.go
  pkg/api/bzz_test.go
  pkg/api/router.go
Labels: ready for review

#124 Add splitter interface and simple splitter implementation stub
  go.mod
  pkg/file/error.go
  pkg/file/file.go
  pkg/file/io.go
  pkg/file/joiner/internal/job.go
  pkg/file/joiner/joiner.go
  pkg/file/span.go
  pkg/file/splitter/internal/job.go
  pkg/file/splitter/internal/job_test.go
  pkg/file/splitter/splitter.go
  pkg/file/testing/chunk.go
Labels: enhancement, ready for review

#160 add misspell, gofmt and unconvert linters
  .githooks/pre-push.bash
  .github/workflows/go.yml
  .golangci.yml
  Makefile
  pkg/p2p/libp2p/internal/breaker/breaker.go
  pkg/pushsync/metrics.go
  pkg/pushsync/pushsync.go
  pkg/swarm/swarm.go
  pkg/validator/validator_test.go
Labels: ready for review

#167 update README.md
  README.md
Labels: ready for review

#171 Pusher: Move push sync logic in to pusher
  pkg/node/node.go
  pkg/pusher/metrics.go
  pkg/pusher/pusher.go
  pkg/pusher/pusher_test.go
  pkg/pushsync/metrics.go
  pkg/pushsync/mock/mock.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/storage/store.go
Labels: ready for review

#169 kademlia, topology: introduce pslice
  pkg/kademlia/pslice/export_test.go
  pkg/kademlia/pslice/pslice.go
  pkg/kademlia/pslice/pslice_test.go
  pkg/topology/test/helper.go
  pkg/topology/test/helper_test.go
  pkg/topology/topology.go
Labels: ready for review

#173 set explicit protobuf package names
  pkg/hive/pb/hive.pb.go
  pkg/hive/pb/hive.proto
  pkg/p2p/libp2p/internal/handshake/pb/handshake.pb.go
  pkg/p2p/libp2p/internal/handshake/pb/handshake.proto
  pkg/p2p/libp2p/internal/headers/pb/headers.pb.go
  pkg/p2p/libp2p/internal/headers/pb/headers.proto
  pkg/p2p/protobuf/internal/pb/test.pb.go
  pkg/p2p/protobuf/internal/pb/test.proto
  pkg/pingpong/pb/pingpong.pb.go
  pkg/pingpong/pb/pingpong.proto
  pkg/pushsync/pb/pushsync.pb.go
  pkg/pushsync/pb/pushsync.proto
  pkg/retrieval/pb/retrieval.pb.go
  pkg/retrieval/pb/retrieval.proto
Labels: ready for review

#174 add pushsync protocol to p2p service instance
  pkg/node/node.go
Labels: ready for review

#168 Add split join integration test
  pkg/file/file.go
  pkg/file/file_test.go
  pkg/file/joiner/internal/job.go
  pkg/file/joiner/joiner.go
  pkg/file/splitter/internal/job.go
  pkg/file/splitter/internal/job_test.go
  pkg/file/testing/vector.go
Labels: enhancement, ready for review

#183 downgrade golangci-lint to v1.24.0
  .github/workflows/go.yml
  Makefile
Labels: ready for review

#184 fix debugapi pprof profiles router
  pkg/debugapi/router.go
Labels: ready for review

#185 libp2p: DisconnectError test
  pkg/p2p/error.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/protocols_test.go
Labels: ready for review

#186 Add CLI application for splitting data to chunks
  cmd/bee-split/main.go
  pkg/file/joiner/internal/job.go
  pkg/file/joiner/joiner.go
  pkg/file/splitter/internal/job.go
  pkg/file/splitter/splitter.go
  pkg/file/splitter/splitter_test.go
  pkg/storage/store.go
Labels: feature, ready for review

#190 construct overlay address with network id
  cmd/bee/cmd/start.go
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
  pkg/keystore/file/key.go
  pkg/node/node.go
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/p2p/libp2p/internal/handshake/pb/handshake.pb.go
  pkg/p2p/libp2p/internal/handshake/pb/handshake.proto
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/libp2p_test.go
Labels: ready for review

#189 Add join cli
  cmd/bee-join/main.go
  cmd/bee-split/main.go
Labels: feature, ready for review

#191 import interval store code from swarm
  pkg/intervalstore/intervals.go
  pkg/intervalstore/intervals_test.go
  pkg/intervalstore/store_test.go
Labels: ready for review

#194 add protobuf Makefile rule
  Makefile
  README.md
Labels: ready for review

#187 Local pinning of chunk
  pkg/api/bzzchunk.go
  pkg/api/bzzchunk_test.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/pin.go
  pkg/debugapi/pin_test.go
  pkg/debugapi/router.go
  pkg/jsonhttp/jsonhttptest/jsonhttptest.go
  pkg/localstore/pin.go
  pkg/localstore/pin_test.go
  pkg/storage/mock/storer.go
  pkg/storage/mock/validator/validator.go
  pkg/storage/store.go
Labels: ready for review

#200 annotate errors in shed
  pkg/localstore/gc_test.go
  pkg/localstore/localstore.go
  pkg/localstore/localstore_test.go
  pkg/localstore/mode_get.go
  pkg/localstore/mode_get_multi.go
  pkg/localstore/mode_get_multi_test.go
  pkg/localstore/mode_put.go
  pkg/localstore/mode_set.go
  pkg/localstore/mode_set_test.go
  pkg/localstore/pin.go
  pkg/localstore/pin_test.go
  pkg/localstore/subscription_pull.go
  pkg/shed/db.go
  pkg/shed/db_test.go
  pkg/shed/example_store_test.go
  pkg/shed/field_string.go
  pkg/shed/field_struct.go
  pkg/shed/field_uint64.go
  pkg/shed/index.go
  pkg/shed/index_test.go
  pkg/shed/schema.go
  pkg/shed/vector_uint64.go
Labels: ready for review

#196 Signing in handshake
  pkg/crypto/signer.go
  pkg/crypto/signer_test.go
  pkg/node/node.go
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/headers_test.go
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/p2p/libp2p/internal/handshake/handshake_test.go
  pkg/p2p/libp2p/internal/handshake/pb/handshake.pb.go
  pkg/p2p/libp2p/internal/handshake/pb/handshake.proto
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/libp2p_test.go
  pkg/p2p/libp2p/protocols_test.go
  pkg/p2p/libp2p/tracing_test.go
Labels: ready for review

#205 Binary encoding of networkID
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/p2p/libp2p/internal/handshake/handshake_test.go
  pkg/p2p/libp2p/libp2p.go
Labels: ready for review

#202 fix localstore log messages
  pkg/localstore/export.go
  pkg/localstore/gc.go
  pkg/localstore/migration.go
  pkg/localstore/mode_get.go
  pkg/localstore/mode_set.go
  pkg/localstore/subscription_pull.go
  pkg/localstore/subscription_push.go
Labels: ready for review

#203 use testing.Cleanup in localstore tests
  pkg/localstore/export_test.go
  pkg/localstore/gc_test.go
  pkg/localstore/index_test.go
  pkg/localstore/localstore_test.go
  pkg/localstore/mode_get_multi_test.go
  pkg/localstore/mode_get_test.go
  pkg/localstore/mode_has_test.go
  pkg/localstore/mode_put_test.go
  pkg/localstore/mode_set_test.go
  pkg/localstore/pin_test.go
  pkg/localstore/retrieval_index_test.go
  pkg/localstore/subscription_pull_test.go
  pkg/localstore/subscription_push_test.go
Labels: ready for review

#204 use testing.Cleanup in test instead deferred explicit cleanup function
  pkg/addressbook/addressbook_test.go
  pkg/api/api_test.go
  pkg/api/bzz_test.go
  pkg/api/bzzchunk_test.go
  pkg/api/pingpong_test.go
  pkg/debugapi/chunk_test.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/p2p_test.go
  pkg/debugapi/peer_test.go
  pkg/debugapi/pin_test.go
  pkg/debugapi/status_test.go
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/headers_test.go
  pkg/p2p/libp2p/libp2p_test.go
  pkg/p2p/libp2p/protocols_test.go
  pkg/p2p/libp2p/tracing_test.go
  pkg/shed/db_test.go
  pkg/shed/field_string_test.go
  pkg/shed/field_struct_test.go
  pkg/shed/field_uint64_test.go
  pkg/shed/index_test.go
  pkg/shed/schema_test.go
  pkg/shed/vector_uint64_test.go
  pkg/statestore/leveldb/leveldb_test.go
  pkg/statestore/mock/store_test.go
  pkg/statestore/test/store.go
Labels: ready for review

#207 fix TestPinGC localstore test data race on test hook
  pkg/localstore/gc_test.go
Labels: ready for review

#216 add content-type header to debug api /topology endpoint
  pkg/debugapi/topology.go
Labels: ready for review

#217 streamtest: add noop middleware to recorder
  pkg/p2p/streamtest/streamtest.go
  pkg/pushsync/pushsync_test.go
Labels: enhancement, ready for review

#231 netstore, retrieval: wrap errors
  pkg/netstore/netstore.go
  pkg/retrieval/retrieval.go
Labels: ready for review

#225 swarm: add address hash size
  pkg/swarm/swarm.go
Labels: ready for review

#232 handle already connected peer gracefully in kadmelia connect
  pkg/kademlia/kademlia.go
Labels: ready for review

#236 kademlia, debugapi, node: fix connection issues
  pkg/debugapi/debugapi.go
  pkg/debugapi/peer.go
  pkg/kademlia/kademlia.go
  pkg/node/node.go
Labels: bug, ready for review

#233 improve list and get pinned chunks api endpoints and tests
  pkg/debugapi/export_test.go
  pkg/debugapi/pin.go
  pkg/debugapi/pin_test.go
  pkg/debugapi/router.go
  pkg/jsonhttp/jsonhttptest/jsonhttptest.go
  pkg/localstore/pin.go
  pkg/localstore/pin_test.go
  pkg/storage/mock/storer.go
Labels: ready for review

#238 add retrieval protocol to p2p service in node package
  pkg/node/node.go
Labels: ready for review

#239 suppress log messages for debug api metrics, health and readiness
  pkg/debugapi/router.go
  pkg/logging/http_access.go
Labels: ready for review
