Repository ethersphere/bee, pull requests merged in 2020-06, with the labels that each got.

#227 Hive with signature + use Bzz address accross Bee
  pkg/addressbook/addressbook.go
  pkg/addressbook/addressbook_test.go
  pkg/bzz/address.go
  pkg/bzz/address_test.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/peer.go
  pkg/debugapi/peer_test.go
  pkg/hive/hive.go
  pkg/hive/hive_test.go
  pkg/hive/pb/hive.pb.go
  pkg/hive/pb/hive.proto
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/node/node.go
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/p2p/libp2p/internal/handshake/handshake_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/topology/full/full.go
  pkg/topology/full/full_test.go
Labels: ready for review

#245 Fix bzz addr in debugapi
  pkg/debugapi/peer.go
  pkg/debugapi/peer_test.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/node/node.go
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/mock/mock.go
  pkg/p2p/p2p.go
  pkg/topology/full/full_test.go
Labels: ready for review

#242 Add file entry implementation
  pkg/collection/collection.go
  pkg/collection/entry/entry.go
  pkg/collection/entry/entry_test.go
  pkg/collection/entry/metadata.go
  pkg/file/io.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/pslice/pslice_test.go
  pkg/swarm/test/helper.go
  pkg/swarm/test/helper_test.go
Labels: feature, ready for review

#199 Tagging chunks
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/bzzchunk.go
  pkg/api/bzzchunk_test.go
  pkg/api/export_test.go
  pkg/api/router.go
  pkg/api/tag.go
  pkg/api/tag_test.go
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/pin_test.go
  pkg/jsonhttp/jsonhttptest/jsonhttptest.go
  pkg/node/node.go
  pkg/pusher/mock/mock.go
  pkg/pusher/pusher.go
  pkg/pusher/pusher_test.go
  pkg/storage/mock/storer.go
  pkg/storage/mock/storer_test.go
  pkg/tags/tag.go
Labels: ready for review

#256 Fix deadlock in concurrent uploads
  pkg/validator/validator.go
Labels: bug, ready for review

#250 Add db capacity flag
  cmd/bee/cmd/start.go
  pkg/localstore/localstore.go
  pkg/localstore/localstore_test.go
  pkg/node/node.go
Labels: enhancement, ready for review

#251 Add CLI for file entry add and resolve
  cmd/bee-file/main.go
  cmd/bee-join/main.go
  cmd/bee-split/main.go
  cmd/internal/file/io.go
  cmd/internal/file/io_test.go
  pkg/swarm/swarm.go
Labels: feature, ready for review

#257 Handshake with observable underlay
  pkg/bzz/address.go
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/p2p/libp2p/internal/handshake/handshake_test.go
  pkg/p2p/libp2p/internal/handshake/pb/handshake.pb.go
  pkg/p2p/libp2p/internal/handshake/pb/handshake.proto
  pkg/p2p/libp2p/libp2p.go
Labels: ready for review

#260 Guard pusher against tags that are not present
  pkg/pusher/pusher.go
  pkg/pusher/pusher_test.go
Labels: ready for review

#262 Fix bzz chunk api
  .github/workflows/beekeeper.yaml
  pkg/api/bzzchunk.go
  pkg/api/bzzchunk_test.go
  pkg/api/tag_test.go
  pkg/debugapi/pin_test.go
Labels: ready for review

#263 fix db capacity log message
  pkg/localstore/localstore.go
Labels: ready for review

#265 api: more info for failing test
  pkg/api/tag_test.go
Labels: ready for review

#268 set Secp256k1 private key in libp2p test services instead temp RSA
  pkg/p2p/libp2p/libp2p_test.go
Labels: ready for review

#269 improve README.md
  README.md
Labels: ready for review

#270 Empty overlay fix in peer registry
  pkg/p2p/libp2p/peer.go
Labels: ready for review

#272 fixed redundent debug statements
  pkg/pusher/pusher.go
Labels: ready for review

#273 remove tag address field for bzz-chunk api
  pkg/api/bzzchunk.go
  pkg/api/router.go
  pkg/api/tag.go
  pkg/api/tag_test.go
  pkg/pusher/mock/mock.go
Labels: ready for review

#255 Local pinning fix
  pkg/localstore/gc_test.go
  pkg/localstore/localstore_test.go
  pkg/localstore/mode_get.go
  pkg/localstore/mode_put.go
  pkg/localstore/mode_set.go
Labels: bug, ready for review

#281 Overlay from eth addr
  pkg/crypto/crypto.go
  pkg/keystore/file/key.go
Labels: ready for review

#287 return multiple errors from node Shutdown to call all close functions
  pkg/node/node.go
Labels: ready for review

#284 api bzz-chunk and bzz-raw rename
  .github/workflows/beekeeper.yaml
  cmd/internal/file/io.go
  pkg/api/bytes.go
  pkg/api/bytes_test.go
  pkg/api/chunk.go
  pkg/api/chunk_test.go
  pkg/api/export_test.go
  pkg/api/router.go
  pkg/api/tag_test.go
  pkg/debugapi/pin_test.go
Labels: ready for review

#286 proximity function adjustments
  pkg/kademlia/kademlia.go
  pkg/kademlia/pslice/pslice_test.go
  pkg/localstore/localstore.go
  pkg/localstore/subscription_pull_test.go
  pkg/swarm/proximity.go
  pkg/swarm/proximity_test.go
  pkg/swarm/swarm.go
Labels: ready for review

#288 Fix one of the test case in local pinning
  pkg/localstore/gc_test.go
Labels: ready for review

#295 shadow stream descriptor in libp2p
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/protocols_test.go
Labels: bug, ready for review

#294 Add join from chunks on disk (symmetric to bee-split)
  cmd/bee-join/main.go
  cmd/internal/file/io.go
Labels: enhancement, ready for review

#283 Advertisable address
  pkg/node/node.go
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/p2p/libp2p/internal/handshake/handshake_test.go
  pkg/p2p/libp2p/internal/handshake/pb/handshake.pb.go
  pkg/p2p/libp2p/internal/handshake/pb/handshake.proto
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/libp2p_test.go
  pkg/p2p/libp2p/upnp.go
Labels: ready for review

#282 File upload with metadata
  pkg/api/bytes.go
  pkg/api/file.go
  pkg/api/file_test.go
  pkg/api/router.go
  pkg/jsonhttp/jsonhttptest/jsonhttptest.go
Labels: ready for review

#291 move tags endpoints to debug api
  pkg/api/export_test.go
  pkg/api/router.go
  pkg/debugapi/export_test.go
  pkg/debugapi/router.go
  pkg/debugapi/tag.go
  pkg/debugapi/tag_test.go
  pkg/tags/tag.go
  pkg/tags/tags.go
Labels: ready for review

#298 implement http.CloseNotifier to responseLogger for gorilla compress
  pkg/logging/http_access.go
Labels: ready for review

#299 reduce some of very frequent pusher log messages
  pkg/pusher/pusher.go
Labels: ready for review

#305 fix the reference to tags.ErrNotFound error type
  pkg/pusher/pusher.go
Labels: ready for review

#300 remove experimental -x http header prefix
  pkg/api/chunk.go
Labels: ready for review

#303 Ux fixes
  README.md
  pkg/node/node.go
Labels: ready for review

#306 support binary upload to api files endpoint
  pkg/api/bytes.go
  pkg/api/export_test.go
  pkg/api/file.go
  pkg/api/file_test.go
  pkg/api/router.go
Labels: ready for review

#308 Added translation from chunks to bytes in help and log
  cmd/bee/cmd/start.go
  pkg/localstore/localstore.go
Labels: ready for review

#311 add option to specify static nat address
  cmd/bee/cmd/start.go
  pkg/node/node.go
  pkg/p2p/libp2p/export_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/static_resolver.go
  pkg/p2p/libp2p/static_resolver_test.go
Labels: ready for review

#314 get the correct data size for file download
  pkg/api/file.go
Labels: ready for review

#310 add File upload section to readme
  README.md
Labels: ready for review

#313 kademlia: pslice rwmutex
  pkg/kademlia/kademlia.go
  pkg/kademlia/pslice/pslice.go
Labels: ready for review

#309 Clean addressbook after failed connection attempts
  pkg/addressbook/addressbook.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
Labels: ready for review

#316 Printing bzzaddress
  pkg/bzz/address.go
  pkg/kademlia/kademlia.go
  pkg/p2p/libp2p/libp2p.go
Labels: ready for review

#318 suppress p2p.ErrAlreadyConnected log when connecting to bootnodes
  pkg/kademlia/kademlia.go
  pkg/node/node.go
Labels: ready for review

#321 full close timeout handle
  pkg/hive/hive.go
  pkg/kademlia/kademlia.go
  pkg/p2p/libp2p/libp2p.go
  pkg/topology/full/full.go
Labels: ready for review

#319 Addressbook get - not found
  pkg/addressbook/addressbook.go
  pkg/addressbook/addressbook_test.go
  pkg/debugapi/peer_test.go
  pkg/hive/hive.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/topology/full/full.go
Labels: ready for review

#325 add send headers timeout
  pkg/p2p/libp2p/headers.go
Labels: ready for review

#328 implement skip peers for ClosestPeerer
  pkg/api/file.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
Labels: ready for review

#193 pull sync: initial version
  pkg/bitvector/bitvector.go
  pkg/bitvector/bitvector_test.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/mock/kademlia.go
  pkg/localstore/subscription_pull.go
  pkg/localstore/subscription_pull_test.go
  pkg/node/node.go
  pkg/puller/export_test.go
  pkg/puller/puller.go
  pkg/puller/puller_test.go
  pkg/pullsync/doc.go
  pkg/pullsync/export_test.go
  pkg/pullsync/mock/pullsync.go
  pkg/pullsync/pb/doc.go
  pkg/pullsync/pb/pullsync.pb.go
  pkg/pullsync/pb/pullsync.proto
  pkg/pullsync/pullstorage/doc.go
  pkg/pullsync/pullstorage/export_test.go
  pkg/pullsync/pullstorage/mock/pullstorage.go
  pkg/pullsync/pullstorage/pullstorage.go
  pkg/pullsync/pullstorage/pullstorage_test.go
  pkg/pullsync/pullsync.go
  pkg/pullsync/pullsync_test.go
  pkg/shed/db.go
  pkg/storage/mock/storer.go
  pkg/storage/mock/storer_test.go
  pkg/storage/store.go
  pkg/topology/full/full.go
  pkg/topology/mock/mock.go
  pkg/topology/topology.go
Labels: ready for review

#327 Improve code in api/bytes.go
  pkg/api/bytes.go
  pkg/api/file.go
  pkg/file/error.go
  pkg/file/file.go
Labels: clean-up, ready for review

#331 retrieval, headers and kademlia announce improvements
  pkg/api/file.go
  pkg/kademlia/kademlia.go
  pkg/p2p/libp2p/headers.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
Labels: ready for review

#335 Revert "Disconnect on headers error (#333)"
  pkg/p2p/libp2p/libp2p.go
Labels: ready for review

#338 use singleflight in retrieval
  pkg/retrieval/retrieval.go
Labels: ready for review

#337 reduce pull sync logging
  pkg/puller/puller.go
  pkg/pullsync/pullsync.go
Labels: clean-up, ready for review

#332 kademlia: add timeout to connect
  pkg/kademlia/kademlia.go
Labels: ready for review

#341 libp2p: reduce trace logs
  pkg/p2p/libp2p/libp2p.go
Labels: clean-up

#330 pusher: disable broken tags and make pusher push chunks in parallel
  pkg/pusher/pusher.go
Labels: clean-up, enhancement, ready for review

#346 puller: silence quit errors
  pkg/puller/puller.go
Labels: clean-up

#345 Ethereum address creation faulty
  pkg/bzz/address.go
  pkg/bzz/address_test.go
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
  pkg/debugapi/peer_test.go
  pkg/hive/hive_test.go
  pkg/keystore/file/key.go
  pkg/node/node.go
  pkg/p2p/libp2p/internal/handshake/handshake_test.go
  pkg/p2p/libp2p/libp2p_test.go
Labels: bug, ready for review

#351 puller: make logging toggleable
  pkg/puller/puller.go
Labels: clean-up

#350 kademlia pslice copy on write
  pkg/kademlia/pslice/pslice.go
Labels: ready for review

#358 implement CORS headers in API
  cmd/bee/cmd/start.go
  pkg/api/api.go
  pkg/api/router.go
  pkg/node/node.go
Labels: ready for review

#367 libp2p: increase receiveHeaders timeout
  pkg/p2p/libp2p/headers.go
Labels: ready for review

#352 kademlia: dont connect to the same peer again in short interval
  pkg/kademlia/kademlia.go
Labels: ready for review

#356 kademlia: handle overlay mismatch
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
Labels: ready for review

#355 reduce max peers, introduce context timeout on RetrieveChunk
  pkg/retrieval/retrieval.go
Labels: ready for review

#353 remove peer from kademlia on peer not found in peer registry
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/libp2p_test.go
Labels: enhancement, ready for review

#368 instrument libp2p errors, print pusher trace only when successful
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/p2p/libp2p/libp2p.go
  pkg/puller/puller.go
  pkg/pusher/pusher.go
Labels: ready for review

#372 cancel stream contexts
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/peer.go
Labels: ready for review

#371 pullsync: add explicit termination
  pkg/puller/puller.go
  pkg/pullsync/mock/pullsync.go
  pkg/pullsync/pb/pullsync.pb.go
  pkg/pullsync/pb/pullsync.proto
  pkg/pullsync/pullsync.go
  pkg/pullsync/pullsync_test.go
Labels: ready for review

#289 Added base api and debugapi yamls, common types
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
Labels: ready for review

#376 add decompressed-content-length header to be used for progress bar
  pkg/api/file.go
Labels: ready for review

#370 puller, pull sync: clean shutdown
  pkg/puller/puller.go
  pkg/puller/puller_test.go
  pkg/pullsync/pullsync.go
Labels: bug, clean-up, ready for review

#379 pullsync: fix shutdown
  pkg/pullsync/pullsync.go
Labels: clean-up, ready for review

#381 fix pullsync panic on unprotected read from map
  pkg/pullsync/pullsync.go
Labels: bug

#384 kademlia: announce in a separate goroutine
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
Labels: bug, ready for review

#389 Multistream test fix
  pkg/p2p/libp2p/protocols_test.go
Labels: ready for review

#374 kademlia: saturate based on known peers
  pkg/kademlia/export_test.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/p2p/libp2p/peer.go
Labels: bug, ready for review

#387 less errors
  pkg/kademlia/kademlia.go
  pkg/pusher/pusher.go
  pkg/retrieval/retrieval.go
Labels: clean-up

#390 Disable QUIC and WS libp2p transports by default
  cmd/bee/cmd/start.go
  pkg/node/node.go
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/libp2p.go
Labels: ready for review

#397 fix puller test, add cleanups to kademlia
  pkg/kademlia/kademlia_test.go
  pkg/puller/puller_test.go
Labels: clean-up, flaky-test, ready for review

#261 update modules
  go.mod
  go.sum
Labels: ready for review
