Repository ethersphere/bee, pull requests merged in 2020-12, with the labels that each got.

#1031 github: disable pullsync integration tests
  .github/workflows/beekeeper.yml
  .github/workflows/slash-beekeeper.yml
Labels: pull-request, ready for review

#1039 add beekeeper.yaml to workflows
  .github/workflows/beekeeper.yml
  .github/workflows/slash-beekeeper.yml
Labels: pull-request

#1040 fix beekeeper.yaml cmd placement
  .github/workflows/beekeeper.yml
Labels: pull-request

#939 api, manifest: abstract saver/loader functionality
  go.mod
  go.sum
  pkg/api/api.go
  pkg/api/bzz.go
  pkg/api/bzz_test.go
  pkg/api/dirs.go
  pkg/api/dirs_test.go
  pkg/api/file.go
  pkg/file/io.go
  pkg/file/loadsave/loadsave.go
  pkg/manifest/manifest.go
  pkg/manifest/mantaray.go
  pkg/manifest/simple.go
  pkg/traversal/traversal.go
  pkg/traversal/traversal_test.go
Labels: pull-request, ready for review

#1042 Remove "error" from log messages
  pkg/kademlia/kademlia.go
  pkg/p2p/libp2p/libp2p.go
  pkg/pricing/pricing.go
  pkg/puller/puller.go
Labels: pull-request

#1035 Openapi description fixes
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
Labels: pull-request, ready for review

#1032 Resolve peer topology inconsistencies
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/peer.go
Labels: pull-request, ready for review

#1036 Compensated Balances error suppression fix
  pkg/accounting/accounting.go
Labels: pull-request, ready for review

#1027 Clean file path from tar archive
  pkg/api/dirs.go
  pkg/api/dirs_test.go
Labels: pull-request

#1029 Add ENS contract address parameter to config
  pkg/resolver/client/ens/ens.go
  pkg/resolver/client/ens/ens_integration_test.go
  pkg/resolver/client/ens/ens_test.go
  pkg/resolver/client/ens/export_test.go
  pkg/resolver/multiresolver/multiresolver.go
Labels: pull-request

#1033 add support for docker-compose
  Dockerfile
  packaging/docker/README.md
  packaging/docker/docker-compose.yml
  packaging/docker/env
Labels: devops, pull-request, ready for review

#1043 simplify validators
  cmd/internal/file/io_test.go
  pkg/api/chunk.go
  pkg/api/chunk_test.go
  pkg/api/gatewaymode_test.go
  pkg/api/pin_chunks_test.go
  pkg/api/tag_test.go
  pkg/content/content.go
  pkg/content/content_test.go
  pkg/content/mock/validator.go
  pkg/content/validator.go
  pkg/content/validator_test.go
  pkg/localstore/localstore_test.go
  pkg/node/node.go
  pkg/pullsync/pullsync.go
  pkg/pullsync/pullsync_test.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/recovery/repair_test.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
  pkg/soc/export_test.go
  pkg/soc/soc.go
  pkg/soc/soc_test.go
  pkg/soc/validator.go
  pkg/soc/validator_test.go
  pkg/storage/mock/storer.go
  pkg/storage/mock/storer_test.go
  pkg/storage/mock/validator/validator.go
  pkg/storage/mock/validator/validator_test.go
  pkg/storage/testing/chunk.go
  pkg/swarm/validator.go
Labels: clean-up, pull-request, ready for review

#1049 minor code hygiene fixes
  pkg/accounting/accounting.go
  pkg/resolver/multiresolver/multiresolver.go
  pkg/settlement/swap/chequebook/cashout.go
  pkg/settlement/swap/swap_test.go
  pkg/tracing/tracing_test.go
Labels: pull-request

#1050 Fix version docker compose
  packaging/docker/docker-compose.yml
Labels: pull-request, ready for review

#1055 version: bump to v0.4.2
  version.go
Labels: pull-request

#930 storage incentives: add stamper putter to api
  cmd/internal/file/io_test.go
  pkg/accounting/accounting.go
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/bytes.go
  pkg/api/bytes_test.go
  pkg/api/bzz.go
  pkg/api/bzz_test.go
  pkg/api/dirs.go
  pkg/api/dirs_test.go
  pkg/api/file.go
  pkg/file/file_test.go
  pkg/file/joiner/joiner_test.go
  pkg/file/loadsave/loadsave.go
  pkg/file/pipeline/builder/builder.go
  pkg/file/pipeline/builder/builder_test.go
  pkg/node/node.go
  pkg/postage/mock/service.go
  pkg/postage/mock/stamper.go
  pkg/postage/service.go
  pkg/postage/service_test.go
  pkg/postage/stamper.go
  pkg/postage/stamper_test.go
  pkg/postage/stampissuer.go
  pkg/pss/trojan.go
  pkg/resolver/multiresolver/multiresolver.go
  pkg/settlement/swap/chequebook/cashout.go
  pkg/settlement/swap/swap_test.go
  pkg/tracing/tracing_test.go
  pkg/traversal/traversal.go
  pkg/traversal/traversal_test.go
Labels: pull-request, ready for review

#1058 fix multiple typos in docker-compose
  packaging/docker/README.md
  packaging/docker/docker-compose.yml
  packaging/docker/env
Labels: pull-request, ready for review

#1045 Fetch chunks from network when pinning
  pkg/api/pin_bytes.go
  pkg/api/pin_bzz.go
  pkg/api/pin_chunks.go
  pkg/api/pin_files.go
  pkg/localstore/mode_put.go
  pkg/localstore/mode_put_test.go
  pkg/localstore/mode_set.go
  pkg/localstore/pin_test.go
  pkg/node/node.go
  pkg/storage/mock/storer.go
  pkg/storage/store.go
Labels: pull-request, ready for review

#1059 If P2P connection exists compare overlay address
  pkg/kademlia/kademlia.go
  pkg/p2p/libp2p/libp2p.go
Labels: pull-request, ready for review

#1060 Windows service support
  cmd/bee/cmd/start.go
  cmd/bee/cmd/start_unix.go
  cmd/bee/cmd/start_windows.go
  go.mod
  go.sum
Labels: pull-request, ready for review

#1056 set only two fresh clusters in ci and slash tests
  .github/workflows/beekeeper.yml
  .github/workflows/slash-beekeeper.yml
Labels: pull-request
