Repository ethersphere/bee, pull requests merged in 2021-04, with the labels that each got.

#1520 bmt: import bmt repo
  pkg/bmt/bmt.go
  pkg/bmt/cmd/generate-hashes/generate-hashes.go
  pkg/bmt/cmd/main_legacy.go
  pkg/bmt/doc.go
  pkg/bmt/errors.go
  pkg/bmt/legacy/bmt.go
  pkg/bmt/legacy/bmt_test.go
  pkg/bmt/legacy/doc.go
  pkg/bmt/pool/pool.go
  pkg/bmt/pool/pool_test.go
  pkg/bmt/reference/doc.go
  pkg/bmt/reference/reference.go
  pkg/bmt/reference/reference_test.go
  pkg/bmtpool/bmtpool.go
Labels: pull-request

#1519 manifest: import manifest repo into bee
  go.mod
  go.sum
  pkg/api/bzz.go
  pkg/manifest/manifest.go
  pkg/manifest/mantaray.go
  pkg/manifest/mantaray/docs/format/node.md
  pkg/manifest/mantaray/marshal.go
  pkg/manifest/mantaray/marshal_test.go
  pkg/manifest/mantaray/node.go
  pkg/manifest/mantaray/node_test.go
  pkg/manifest/mantaray/persist.go
  pkg/manifest/mantaray/persist_test.go
  pkg/manifest/mantaray/stringer.go
  pkg/manifest/mantaray/walker.go
  pkg/manifest/mantaray/walker_test.go
  pkg/manifest/simple.go
  pkg/manifest/simple/entry.go
  pkg/manifest/simple/manifest.go
  pkg/manifest/simple/manifest_test.go
  pkg/manifest/simple/walker.go
  pkg/manifest/simple/walker_test.go
Labels: pull-request

#1516 Remove marshall from kad, refactor debugapi
  pkg/debugapi/topology.go
  pkg/debugapi/topology_test.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/mock/kademlia.go
  pkg/topology/mock/mock.go
  pkg/topology/topology.go
Labels: pull-request, ready for review

#1522 fix bad connected value in kad snapshot test
  pkg/kademlia/kademlia_test.go
Labels: pull-request, ready for review

#1513 run beekeeper tests on every push to pr
  .github/workflows/beekeeper.yml
Labels: pull-request, ready for review

#1523 retrieval: log less
  pkg/retrieval/retrieval.go
Labels: pull-request

#1321 stamp support in storage and protocols
  pkg/api/api.go
  pkg/localstore/export.go
  pkg/localstore/export_test.go
  pkg/localstore/localstore.go
  pkg/localstore/localstore_test.go
  pkg/localstore/mode_get.go
  pkg/localstore/mode_get_multi.go
  pkg/localstore/subscription_push.go
  pkg/localstore/subscription_push_test.go
  pkg/node/node.go
  pkg/postage/stamp.go
  pkg/pullsync/pullsync.go
  pkg/pullsync/pullsync_test.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/shed/index.go
  pkg/storage/testing/chunk.go
  pkg/swarm/swarm.go
Labels: pull-request, ready for review

#1521 pss: beekeeper tests
  .github/workflows/beekeeper.yml
Labels: pull-request, ready for review

#1524 Soc/beekeeper
  .github/workflows/beekeeper.yml
Labels: pull-request, ready for review

#1533 pss test timeout
  .github/workflows/beekeeper.yml
Labels: pull-request, ready for review

#1486 replace sw3-bindings with go-sw3-abi
  go.mod
  go.sum
  pkg/settlement/swap/chequebook/cashout_test.go
  pkg/settlement/swap/chequebook/chequebook.go
  pkg/settlement/swap/chequebook/factory.go
  pkg/settlement/swap/chequebook/factory_test.go
  pkg/settlement/swap/erc20/erc20.go
  pkg/settlement/swap/erc20/erc20_test.go
  pkg/settlement/swap/transaction/event_test.go
Labels: pull-request, ready for review

#1550 add pr branch name to github action fail messages
  .github/workflows/beekeeper.yml
Labels: pull-request

#1537 Push/pull sync - neighborhood syncing
  pkg/kademlia/mock/kademlia.go
  pkg/node/node.go
  pkg/puller/puller.go
  pkg/puller/puller_test.go
  pkg/pullsync/mock/pullsync.go
  pkg/pushsync/metrics.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/topology/mock/mock.go
  pkg/topology/topology.go
Labels: pull-request, ready for review

#1535 api: endpoints for stamp issuers
  pkg/api/export_test.go
  pkg/api/postage.go
  pkg/api/postage_test.go
  pkg/api/router.go
  pkg/postage/mock/service.go
  pkg/postage/stampissuer.go
Labels: pull-request, ready for review

#1490 bmt pkg migrate under swarm
  pkg/bmt/benchmark_test.go
  pkg/bmt/bmt.go
  pkg/bmt/bmt_test.go
  pkg/bmt/cmd/generate-hashes/generate-hashes.go
  pkg/bmt/cmd/main_legacy.go
  pkg/bmt/doc.go
  pkg/bmt/errors.go
  pkg/bmt/export_test.go
  pkg/bmt/interface.go
  pkg/bmt/legacy/bmt.go
  pkg/bmt/legacy/bmt_test.go
  pkg/bmt/legacy/doc.go
  pkg/bmt/pool.go
  pkg/bmt/pool/pool.go
  pkg/bmt/pool/pool_test.go
  pkg/bmt/reference/reference.go
  pkg/bmt/reference/reference_test.go
  pkg/bmtpool/bmtpool.go
  pkg/cac/cac.go
  pkg/file/pipeline/bmt/bmt.go
  pkg/file/pipeline/bmt/bmt_test.go
  pkg/file/pipeline/builder/builder_test.go
  pkg/pss/trojan.go
Labels: pull-request, ready for review

#1465 transaction: add nonce-based monitor
  cmd/bee/cmd/deploy.go
  pkg/node/chain.go
  pkg/node/node.go
  pkg/settlement/swap/transaction/backend.go
  pkg/settlement/swap/transaction/backendmock/backend.go
  pkg/settlement/swap/transaction/backendsimulation/backend.go
  pkg/settlement/swap/transaction/export_test.go
  pkg/settlement/swap/transaction/mock/transaction.go
  pkg/settlement/swap/transaction/monitor.go
  pkg/settlement/swap/transaction/monitor_test.go
  pkg/settlement/swap/transaction/monitormock/monitor.go
  pkg/settlement/swap/transaction/transaction.go
  pkg/settlement/swap/transaction/transaction_test.go
Labels: pull-request, ready for review

#1552 retrieval: add stamps
  pkg/retrieval/pb/retrieval.pb.go
  pkg/retrieval/pb/retrieval.proto
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
  pkg/storage/mock/storer.go
Labels: pull-request, ready for review

#1555 bump debian base to 10.9-slim
  Dockerfile
  Dockerfile.goreleaser
Labels: pull-request, ready for review

#1560 install beekeeper using make
  Makefile
Labels: pull-request, ready for review

#1322 localstore reserve logic
  .github/workflows/beekeeper.yml
  pkg/localstore/gc.go
  pkg/localstore/gc_test.go
  pkg/localstore/index_test.go
  pkg/localstore/localstore.go
  pkg/localstore/localstore_test.go
  pkg/localstore/mode_get.go
  pkg/localstore/mode_get_test.go
  pkg/localstore/mode_put.go
  pkg/localstore/mode_put_test.go
  pkg/localstore/mode_set.go
  pkg/localstore/mode_set_test.go
  pkg/localstore/pin_test.go
  pkg/localstore/reserve.go
  pkg/localstore/reserve_test.go
  pkg/netstore/netstore.go
  pkg/netstore/netstore_test.go
  pkg/node/node.go
  pkg/postage/batchstore/reserve.go
  pkg/postage/batchstore/reserve_test.go
  pkg/postage/batchstore/store.go
  pkg/pushsync/pushsync_test.go
  pkg/recovery/repair_test.go
  pkg/shed/index.go
  pkg/storage/store.go
  pkg/storage/testing/chunk.go
Labels: pull-request, ready for review

#1553 kademlia: add unsaturated bins to depth calculation
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
Labels: pull-request, ready for review

#1563 Pricing no protocol updates
  pkg/node/node.go
  pkg/pricer/export_test.go
  pkg/pricer/mock/pricer.go
  pkg/pricer/pricer.go
  pkg/pricer/pricer_test.go
  pkg/pricing/pb/pricing.pb.go
  pkg/pricing/pb/pricing.proto
  pkg/pricing/pricing.go
  pkg/pricing/pricing_test.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/recovery/repair_test.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
  pkg/topology/mock/mock.go
Labels: pull-request, ready for review

#1567 separate context for pushsync replication
  pkg/pushsync/pushsync.go
Labels: pull-request, ready for review

#1554 publish docker image to quay.io as well
  .github/workflows/beekeeper.yml
  .github/workflows/release.yaml
  .goreleaser.yml
Labels: pull-request, ready for review

#1501 Removing collections package and API cleanup
  cmd/bee-file/main.go
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  pkg/api/api.go
  pkg/api/bytes_test.go
  pkg/api/bzz.go
  pkg/api/bzz_test.go
  pkg/api/dirs.go
  pkg/api/dirs_test.go
  pkg/api/export_test.go
  pkg/api/file.go
  pkg/api/file_test.go
  pkg/api/pin_bytes_test.go
  pkg/api/pin_bzz_test.go
  pkg/api/pin_files.go
  pkg/api/pin_files_test.go
  pkg/api/router.go
  pkg/api/tag_test.go
  pkg/collection/collection.go
  pkg/collection/entry/entry.go
  pkg/collection/entry/entry_test.go
  pkg/collection/entry/metadata.go
  pkg/file/loadsave/loadsave.go
  pkg/manifest/manifest.go
  pkg/manifest/mantaray.go
  pkg/manifest/mantaray/marshal.go
  pkg/traversal/traversal.go
  pkg/traversal/traversal_test.go
Labels: pull-request

#1565 Restore CI parameters for thresholds
  .github/workflows/beekeeper.yml
  pkg/pushsync/pushsync.go
Labels: pull-request, ready for review

#1568 localstore: dont acquire batchMu for a single chunk that already exists
  pkg/localstore/mode_put.go
Labels: enhancement, pull-request, ready for review

#1572 chunks: batchID
  pkg/api/chunk.go
  pkg/pushsync/pushsync.go
Labels: pull-request

#1574 batch service: improve logging
  pkg/postage/batchservice/batchservice.go
Labels: pull-request

#1575 Storage incentives polling reduction
  pkg/postage/listener/listener.go
Labels: pull-request, ready for review

#1569 api: stamper propagation
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/bzz.go
  pkg/api/chunk.go
  pkg/api/dirs.go
  pkg/api/export_test.go
  pkg/api/feed.go
  pkg/api/feed_test.go
  pkg/api/pss.go
  pkg/api/pss_test.go
  pkg/api/soc.go
  pkg/api/soc_test.go
  pkg/pss/pss.go
  pkg/pss/pss_test.go
  pkg/recovery/repair.go
  pkg/recovery/repair_test.go
Labels: pull-request, ready for review

#1576 Make localcluster
  Makefile
Labels: pull-request

#1579 cmd: deprecate utility binaries
  Makefile
  cmd/bee-file/main.go
  cmd/bee-join/main.go
  cmd/bee-split/main.go
  cmd/internal/file/io.go
  cmd/internal/file/io_test.go
Labels: clean-up, pull-request, ready for review

#1581 sign checksums.txt with gpg key
  .github/workflows/release.yaml
  .goreleaser.yml
Labels: pull-request

#1580 cmd: add db import export
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/db.go
  cmd/bee/cmd/deploy.go
  cmd/bee/cmd/init.go
  cmd/bee/cmd/start.go
  pkg/localstore/export.go
  pkg/localstore/export_test.go
Labels: enhancement, pull-request, ready for review

#1588 storage incentives: add reservestate metrics
  pkg/node/node.go
  pkg/postage/batchstore/metrics.go
  pkg/postage/batchstore/reserve.go
  pkg/postage/batchstore/store.go
Labels: pull-request, ready for review

#1584 localstore: increment export version
  pkg/localstore/export.go
Labels: pull-request

#1586 Storage incentives reservestate api
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/postage.go
  pkg/debugapi/postage_test.go
  pkg/debugapi/router.go
  pkg/node/node.go
  pkg/postage/batchstore/mock/store.go
  pkg/postage/batchstore/store.go
  pkg/postage/interface.go
  pkg/postage/reservestate.go
Labels: pull-request, ready for review

#1592 beekeeper: disable pinning tests
  .github/workflows/beekeeper.yml
Labels: pull-request

#1566 Change pins API
  go.mod
  go.sum
  openapi/Swarm.yaml
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/bytes.go
  pkg/api/bytes_test.go
  pkg/api/bzz.go
  pkg/api/bzz_test.go
  pkg/api/chunk.go
  pkg/api/chunk_test.go
  pkg/api/dirs.go
  pkg/api/export_test.go
  pkg/api/feed.go
  pkg/api/gatewaymode_test.go
  pkg/api/pin.go
  pkg/api/pin_bytes.go
  pkg/api/pin_bytes_test.go
  pkg/api/pin_bzz.go
  pkg/api/pin_bzz_test.go
  pkg/api/pin_chunks.go
  pkg/api/pin_chunks_test.go
  pkg/api/pin_files.go
  pkg/api/pin_files_test.go
  pkg/api/pin_test.go
  pkg/api/router.go
  pkg/api/soc.go
  pkg/localstore/metrics.go
  pkg/localstore/mode_get.go
  pkg/localstore/mode_get_multi.go
  pkg/localstore/mode_get_multi_test.go
  pkg/localstore/pin.go
  pkg/localstore/pin_test.go
  pkg/manifest/manifest.go
  pkg/manifest/mantaray/marshal.go
  pkg/netstore/netstore.go
  pkg/node/node.go
  pkg/pinning/doc.go
  pkg/pinning/mock/mock.go
  pkg/pinning/pinning.go
  pkg/pinning/pinning_test.go
  pkg/storage/mock/storer.go
  pkg/storage/store.go
  pkg/swarm/swarm.go
  pkg/traversal/traversal.go
  pkg/traversal/traversal_test.go
Labels: pull-request, ready for review

#1594 batchstore, kademlia: add radius as depth upper bound
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/node/node.go
  pkg/postage/batchstore/mock/store.go
  pkg/postage/batchstore/reserve_test.go
  pkg/postage/batchstore/store.go
  pkg/postage/batchstore/store_test.go
  pkg/postage/interface.go
Labels: pull-request, ready for review

#1596 storage incentives: reduce deepsource complaints
  pkg/api/api.go
  pkg/api/bzz.go
  pkg/api/dirs.go
  pkg/api/export_test.go
  pkg/feeds/feed.go
  pkg/feeds/testing/lookup.go
  pkg/postage/batchservice/batchservice_test.go
  pkg/postage/batchstore/reserve_test.go
  pkg/postage/listener/listener.go
  pkg/postage/postagecontract/contract.go
  pkg/postage/testing/batch.go
  pkg/postage/testing/chainstate.go
  pkg/pss/trojan.go
  pkg/resolver/client/ens/ens.go
  pkg/settlement/swap/transaction/event_test.go
  pkg/swarm/test/helper.go
  pkg/tracing/tracing.go
Labels: pull-request, ready for review

#1590 Add logging welcome message on incoming connections
  pkg/p2p/libp2p/internal/handshake/handshake.go
Labels: pull-request, ready for review

#1598 batchstore: fix panic
  pkg/node/node.go
  pkg/postage/batchservice/batchservice.go
  pkg/postage/batchstore/store.go
  pkg/postage/interface.go
  pkg/postage/listener/listener_test.go
Labels: pull-request

#1582 take care for option deprecation
  .goreleaser.yml
Labels: pull-request

#1593 swarm: change MaxPO
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/pullsync/pullstorage/pullstorage.go
  pkg/swarm/swarm.go
  pkg/topology/topology.go
Labels: pull-request, ready for review

#1599 use abi library
  go.mod
  go.sum
  pkg/postage/listener/abi.go
  pkg/postage/listener/listener.go
  pkg/postage/postagecontract/contract.go
Labels: pull-request, ready for review

#1597 fix cors preflight headers bug
  pkg/api/router.go
  pkg/debugapi/cors.go
Labels: pull-request

#1458 light nodes
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/topology.go
  pkg/node/node.go
  pkg/p2p/error.go
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/p2p/libp2p/internal/handshake/handshake_test.go
  pkg/p2p/libp2p/internal/handshake/pb/handshake.pb.go
  pkg/p2p/libp2p/internal/handshake/pb/handshake.proto
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/libp2p_test.go
  pkg/p2p/libp2p/metrics.go
  pkg/p2p/p2p.go
  pkg/p2p/specwrapper.go
  pkg/p2p/specwrapper_test.go
  pkg/puller/puller_test.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/topology/kademlia/doc.go
  pkg/topology/kademlia/export_test.go
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
  pkg/topology/kademlia/mock/kademlia.go
  pkg/topology/lightnode/container.go
  pkg/topology/lightnode/container_test.go
  pkg/topology/mock/mock.go
  pkg/topology/pslice/export_test.go
  pkg/topology/pslice/pslice.go
  pkg/topology/pslice/pslice_test.go
  pkg/topology/topology.go
Labels: pull-request, ready for review

#1604 localstore: simplify updategc logic, put to pullsync index when stamp valid
  pkg/localstore/mode_get.go
  pkg/localstore/mode_put.go
  pkg/localstore/mode_put_test.go
  pkg/localstore/pin_test.go
Labels: pull-request

#1600 Slack/api metrics
  pkg/api/metrics.go
  pkg/api/router.go
Labels: pull-request

#1607 node: fix standalone mode, fix panic
  pkg/node/node.go
Labels: pull-request, ready for review

#1617 libp2p static address resolver test simplification
  go.mod
  go.sum
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/static_resolver.go
  pkg/p2p/libp2p/static_resolver_test.go
Labels: pull-request

#1621 Light nodes: flipped default value
  cmd/bee/cmd/cmd.go
  pkg/p2p/libp2p/internal/handshake/handshake.go
Labels: pull-request

#1611 Using the correct http response codes when creating a resource
  openapi/Swarm.yaml
  openapi/SwarmDebug.yaml
  pkg/api/api_test.go
  pkg/api/bytes.go
  pkg/api/bytes_test.go
  pkg/api/bzz.go
  pkg/api/bzz_test.go
  pkg/api/chunk.go
  pkg/api/chunk_test.go
  pkg/api/dirs.go
  pkg/api/dirs_test.go
  pkg/api/gatewaymode_test.go
  pkg/api/pin.go
  pkg/api/pin_test.go
  pkg/api/postage.go
  pkg/api/postage_test.go
  pkg/api/pss.go
  pkg/api/pss_test.go
  pkg/api/tag_test.go
Labels: pull-request, ready for review

#1622 libp2p: improve cleanup on shutdown
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/libp2p.go
Labels: pull-request, ready for review

#1609 intervalstore: fix uint64 overflow
  pkg/intervalstore/intervals.go
  pkg/intervalstore/intervals_test.go
Labels: bug, pull-request, ready for review

#1614 Fix OpenAPI specification inconsistencies
  .github/workflows/beekeeper.yml
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
Labels: pull-request, ready for review

#1616 Rename address to reference in pinning related code
  openapi/Swarm.yaml
  pkg/api/bytes_test.go
  pkg/api/bzz_test.go
  pkg/api/chunk_test.go
  pkg/api/pin.go
  pkg/api/pin_test.go
  pkg/api/router.go
  pkg/pinning/doc.go
  pkg/pinning/mock/mock.go
  pkg/pinning/pinning.go
  pkg/pinning/pinning_test.go
Labels: pull-request, ready for review
