Repository ethersphere/bee, pull requests merged in 2021-07, with the labels that each got.

#2281 fix: deep source
  pkg/pricing/pricing.go
  pkg/pushsync/pushsync.go
  pkg/settlement/pseudosettle/pseudosettle.go
  pkg/settlement/pseudosettle/pseudosettle_test.go
  pkg/settlement/swap/chequebook/chequestore.go
  pkg/settlement/swap/chequebook/factory.go
  pkg/settlement/swap/chequestore/mock/chequestore.go
  pkg/settlement/swap/headers/utilities.go
  pkg/settlement/swap/mock/swap.go
  pkg/settlement/swap/priceoracle/mock/priceoracle.go
  pkg/settlement/swap/priceoracle/priceoracle.go
  pkg/settlement/swap/swap.go
  pkg/settlement/swap/swapprotocol/swapprotocol.go
Labels: pull-request

#2225 fix: typo in URL
  cmd/bee/cmd/start.go
Labels: pull-request, ready for review

#2227 feat: batchstore checksums
  pkg/node/node.go
  pkg/postage/batchservice/batchservice.go
  pkg/postage/batchservice/batchservice_test.go
  pkg/postage/interface.go
  pkg/postage/listener/listener.go
  pkg/postage/listener/listener_test.go
Labels: pull-request, ready for review

#2233 fix: disable forwarding node stamp verification
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
Labels: pull-request, ready for review

#2140 fix(pss): make sending PSS messages more efficient
  pkg/pss/mining_test.go
  pkg/pss/trojan.go
Labels: pull-request, ready for review

#2285 fix: commit hash for bee version
  .goreleaser.yml
  Makefile
Labels: pull-request

#2232 fix: default network config
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  pkg/config/chain.go
  pkg/node/chain.go
  pkg/node/node.go
  pkg/postage/listener/listener.go
  pkg/settlement/swap/chequebook/factory.go
  pkg/settlement/swap/priceoracle/priceoracle.go
Labels: pull-request, ready for review

#2290 fix: deep source
  pkg/node/node.go
  pkg/transaction/backend.go
Labels: pull-request, ready for review

#1978 fix: enable light node test
  .github/workflows/beekeeper.yml
Labels: pull-request

#2237 fix: only in neighborhood replication
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
Labels: pull-request, ready for review

#2289 ci: auto build openapi spec
  .github/workflows/docs.yaml
  README.md
Labels: pull-request, ready for review

#2296 fix: least authority gcSizeChange bug
  pkg/localstore/mode_put.go
  pkg/localstore/mode_put_test.go
Labels: bug, pull-request

#2293 fix: replicate with peers further from the chunk
  pkg/pushsync/pushsync.go
Labels: pull-request, ready for review

#2313 chore: document implementation detail
  pkg/localstore/mode_set.go
Labels: pull-request, ready for review

#2279 chore: reinstate stamps on the api
  openapi/Swarm.yaml
  pkg/api/export_test.go
  pkg/api/postage.go
  pkg/api/postage_test.go
  pkg/api/router.go
Labels: pull-request, ready for review

#2287 fix(pss): fix trojan mining
  pkg/pss/mining_test.go
  pkg/pss/trojan.go
Labels: pull-request, ready for review

#2315 chore: bump base docker image
  Dockerfile
  Dockerfile.goreleaser
  Dockerfile.scratch
Labels: pull-request

#2311 fix: add to skiplist on error in goroutine
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/topology/mock/mock.go
Labels: pull-request, ready for review

#2316 chore: update dependency versions
  go.mod
  go.sum
  pkg/debugapi/metrics.go
Labels: pull-request, ready for review

#2320 chore: fix typo
  pkg/debugapi/peer_test.go
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/p2p/libp2p/internal/handshake/handshake_test.go
  pkg/resolver/client/ens/ens_integration_test.go
  pkg/resolver/client/ens/export_test.go
  pkg/settlement/swap/mock/swap.go
  pkg/tags/tag.go
  pkg/topology/kademlia/kademlia.go
Labels: pull-request

#2322 fix: OpenAPI transaction info response fields type
  openapi/SwarmCommon.yaml
Labels: pull-request, ready for review

#2327 fix(pushsync, retrieval): avoid deadlocks on context done
  pkg/pushsync/pushsync.go
  pkg/retrieval/retrieval.go
Labels: pull-request, ready for review

#2323 feat: allow setting tracing-endpoint using host and port
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
Labels: pull-request

#2324 feat: rename log field traceid to traceID
  pkg/tracing/doc.go
  pkg/tracing/tracing.go
Labels: pull-request

#2325 docs: gateway mode forbidden and tweaks
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
Labels: pull-request

#2328 feat: add expired field to the postage stamp response
  openapi/SwarmCommon.yaml
  pkg/debugapi/postage.go
  pkg/debugapi/postage_test.go
  pkg/postage/batchstore/mock/store.go
  pkg/postage/batchstore/store.go
  pkg/postage/interface.go
  pkg/postage/mock/service.go
  pkg/postage/service.go
Labels: pull-request

#2331 refactor: remove standalone mode
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  packaging/bee.yaml
  packaging/docker/docker-compose.yml
  packaging/docker/env
  packaging/homebrew/bee.yaml
  packaging/scoop/bee.yaml
  pkg/node/node.go
  pkg/p2p/libp2p/libp2p.go
  pkg/topology/kademlia/kademlia.go
Labels: pull-request

#2321 feat: add bucket data endpoint
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
  pkg/debugapi/export_test.go
  pkg/debugapi/postage.go
  pkg/debugapi/postage_test.go
  pkg/debugapi/router.go
  pkg/postage/stampissuer.go
Labels: pull-request, ready for review

#2234 feat: cache on forwarding in retrieval
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  pkg/netstore/netstore.go
  pkg/netstore/netstore_test.go
  pkg/node/node.go
  pkg/postage/stamp.go
  pkg/pullsync/pullsync.go
  pkg/pushsync/pushsync.go
  pkg/recovery/repair_test.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
Labels: pull-request, ready for review

#2319 feat(hive, libp2p): check reachability while processing peer from hive
  go.sum
  pkg/hive/hive.go
  pkg/hive/hive_test.go
  pkg/hive/metrics.go
  pkg/node/node.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/protocols_test.go
  pkg/p2p/p2p.go
  pkg/p2p/streamtest/streamtest.go
  pkg/p2p/streamtest/streamtest_test.go
  pkg/pullsync/mock/pullsync.go
  pkg/topology/kademlia/kademlia.go
Labels: pull-request

#2337 fix: restore initial balance check
  pkg/settlement/swap/chequebook/init.go
Labels: pull-request, ready for review

#2341 ci: disable flaky test
  pkg/p2p/libp2p/protocols_test.go
Labels: pull-request

#2340 fix: correct blocktime for xdai
  cmd/bee/cmd/start.go
Labels: pull-request, ready for review

#2345 fix(retrieval): flaky retrieval test
  pkg/retrieval/retrieval_test.go
Labels: pull-request

#2338 chore: remove dead code
  pkg/localstore/mode_get.go
  pkg/localstore/mode_get_multi.go
  pkg/localstore/mode_get_multi_test.go
  pkg/storage/store.go
Labels: pull-request, ready for review

#2336 feat: estimate expected lifetime of batches
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/postage.go
  pkg/debugapi/postage_test.go
  pkg/node/node.go
  pkg/postage/mock/service.go
  pkg/postage/service.go
Labels: pull-request, ready for review

#2350 chore: add OpenAPI postage batch missing field
  openapi/SwarmCommon.yaml
Labels: pull-request, ready for review

#2349 fix: flaky ping test and log correction
  go.mod
  pkg/hive/hive.go
  pkg/p2p/libp2p/export_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/protocols_test.go
Labels: pull-request

#2318 fix: reinstate gc test
  .github/patches/postagecontract.patch
  .github/patches/postagereserve.patch
  .github/patches/postagereserve_gc.patch
  .github/workflows/beekeeper.yml
  pkg/debugapi/postage.go
  pkg/postage/batchstore/reserve.go
Labels: pull-request, ready for review

#2352 chore: adjust flipflop worst case time
  pkg/localstore/localstore.go
Labels: pull-request, ready for review

#2353 chore(api): improve logging
  pkg/api/bzz.go
Labels: pull-request, ready for review

#2356 refactor(api): move bzz patch under the stewardship endpoint
  openapi/Swarm.yaml
  pkg/api/bzz.go
  pkg/api/bzz_test.go
  pkg/api/router.go
  pkg/api/stewardship.go
  pkg/api/stewardship_test.go
Labels: pull-request, ready for review

#2351 feat: announce to lightnodes
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/p2p.go
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
  pkg/topology/kademlia/mock/kademlia.go
  pkg/topology/lightnode/container.go
  pkg/topology/lightnode/container_test.go
  pkg/topology/mock/mock.go
Labels: pull-request, ready for review

#2359 fix: flaky test
  go.mod
  pkg/p2p/libp2p/connections_test.go
Labels: pull-request

#2358 fix: use our own timestamp in too soon check
  pkg/settlement/pseudosettle/pseudosettle.go
Labels: pull-request

#2348 feat: only local pushsync skiplist
  .github/bin/beekeeper_artifacts.sh
  .github/workflows/beekeeper.yml
  pkg/p2p/libp2p/libp2p.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
Labels: pull-request, ready for review

#2342 chore: update go-ethereum
  go.mod
  go.sum
  pkg/node/node.go
  pkg/settlement/swap/addressbook.go
  pkg/settlement/swap/chequebook/chequebook_test.go
  pkg/settlement/swap/chequebook/export_test.go
  pkg/settlement/swap/export_test.go
  pkg/settlement/swap/swap_test.go
  pkg/statestore/leveldb/migration.go
  pkg/statestore/leveldb/migration_test.go
  pkg/transaction/sender_matcher_test.go
Labels: pull-request, ready for review

#2169 feat: bootnodes dont dial
  pkg/topology/kademlia/kademlia.go
Labels: on hold, pull-request

#2364 chore: bump openapi version
  openapi/Swarm.yaml
  openapi/SwarmDebug.yaml
Labels: pull-request

#2366 bump clef in dockercompose
  packaging/docker/docker-compose.yml
Labels: pull-request

#2367 chore(packaging): update comment
  packaging/docker/env
Labels: pull-request

#2365 chore: bump bee version
  version.go
Labels: pull-request

#2369 feat: dont push all docker image tags to the dockerhub for rc
  .goreleaser.yml
Labels: pull-request

#2370 fix: bad err formatting
  pkg/pullsync/pullsync.go
Labels: pull-request, ready for review

#2372 fix: query header instead of block
  pkg/transaction/backend.go
Labels: pull-request, ready for review

#2374 fix: closest peer skip list
  pkg/topology/kademlia/kademlia.go
Labels: pull-request

#2375 fix: postage stamp usable flag
  pkg/debugapi/postage.go
Labels: pull-request, ready for review

#2376 fix: postage stamp estimate batch not found result
  pkg/debugapi/postage.go
Labels: pull-request, ready for review

#2377 chore(hive): reduce log verbosity
  pkg/hive/hive.go
Labels: pull-request, ready for review

#2378 refactor: simplify error handling
  pkg/pushsync/pushsync.go
Labels: pull-request, ready for review

#2379 feat: limit concurrent access to some parts of the api resources
  pkg/debugapi/chequebook.go
  pkg/debugapi/debugapi.go
  pkg/debugapi/postage.go
Labels: pull-request
