Repository ethersphere/bee, pull requests merged in 2021-12, with the labels that each got.

#2692 chore: pushsync valid stamp metrics
  .github/workflows/beekeeper.yml
  Makefile
  go.sum
  pkg/postage/listener/export_test.go
  pkg/postage/listener/listener.go
  pkg/pushsync/metrics.go
  pkg/pushsync/pushsync.go
Labels: pull-request

#2691 feat: code formatter command
  Makefile
Labels: in progress, pull-request

#2707 fix(pushsync): close done channel with a defer
  pkg/pushsync/pushsync.go
Labels: ready for review, pull-request

#2690 feat: lint style command
  .golangci.style.yml
  CODINGSTYLE.md
Labels: ready for review, pull-request

#2706 feat: preemptive retrieval based on mainnet p90
  pkg/p2p/streamtest/streamtest.go
  pkg/retrieval/metrics.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
Labels: ready for review, pull-request

#2710 feat: support loading ethereum key files
  pkg/keystore/file/key.go
Labels: ready for review, pull-request

#2711 feat: create eth V3 compatible keys
  pkg/keystore/file/key.go
Labels: pull-request

#2677 feat: relax balancing
  pkg/topology/kademlia/kademlia.go
Labels: pull-request

#2714 chore(ci): adjust block threshold for ci
  .github/patches/postageservice.patch
Labels: ready for review, pull-request

#2718 revert: preemptive retrieval based on mainnet p90
  pkg/p2p/streamtest/streamtest.go
  pkg/retrieval/metrics.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
Labels: pull-request

#2719 perf(retrieval): faster preemptive retry
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
Labels: ready for review, pull-request

#2649 feat(debugapi): node ep
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/export_test.go
  pkg/debugapi/node.go
  pkg/debugapi/router.go
  pkg/node/devnode.go
  pkg/node/node.go
Labels: pull-request

#2717 docs: update chunk endpoint info
  openapi/Swarm.yaml
Labels: pull-request

#2716 docs: naked returns chapter
  CODINGSTYLE.md
Labels: ready for review, pull-request

#2721 feat: bump go linter version
  .golangci.local.yml
  .golangci.style.yml
  Makefile
  cmd/bee/cmd/start_unix.go
  pkg/manifest/mantaray/marshal.go
  pkg/manifest/mantaray/node.go
  pkg/manifest/mantaray/stringer.go
  pkg/settlement/swap/priceoracle/mock/priceoracle.go
Labels: ready for review, pull-request

#2730 chore: bump v1.4.2
  version.go
Labels: pull-request

#2236 feat: allow swap without chequebook
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  openapi/SwarmCommon.yaml
  pkg/debugapi/chequebook.go
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/node.go
  pkg/debugapi/router.go
  pkg/node/devnode.go
  pkg/node/node.go
  pkg/settlement/swap/swap.go
Labels: ready for review, pull-request

#2726 fix: add missing goreleaser ldflags
  .goreleaser.yml
Labels: pull-request

#2731 feat: nonconditional expiring skip of peers pushed
  pkg/pushsync/pushsync.go
Labels: ready for review, pull-request

#2729 fix: unblocking write to channel in retrieval
  pkg/retrieval/retrieval.go
Labels: ready for review, pull-request

#2728 fix: changing node reachability status
  pkg/topology/kademlia/kademlia.go
Labels: pull-request

#2732 fix: cashout to overlay address if no chequebook
  pkg/node/chain.go
  pkg/settlement/swap/swap.go
  pkg/settlement/swap/swap_test.go
Labels: ready for review, pull-request

#2733 fix: no pulling on bootnodes
  pkg/node/node.go
Labels: ready for review, pull-request

#2734 fix: ignore reachability status updates to unknown
  pkg/topology/kademlia/kademlia.go
Labels: pull-request

#2737 chore: add check for trailing whitespaces
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/workflows/release_triggers.yaml
  .golangci.local.yml
  .goreleaser.yml
  Makefile
  README.md
  cmd/bee/cmd/start_dev.go
  openapi/Swarm.yaml
  openapi/SwarmDebug.yaml
  packaging/rpm/post
  pkg/p2p/protobuf/internal/pb/test.proto
  pkg/pullsync/pb/pullsync.proto
Labels: ready for review, pull-request

#2736 fix: fix openapi generator for debug api
  openapi/SwarmCommon.yaml
Labels: ready for review, pull-request

#2738 fix: whitespace
  openapi/SwarmCommon.yaml
Labels: ready for review, pull-request

#2720 test: add missing unit test for BeeNodeMode enum
  pkg/debugapi/node_test.go
Labels: pull-request

#2740 feat: enable darwin arm64 binary build
  .goreleaser.yml
Labels: pull-request

#2739 fix: set missing env variables inside .goreleaser.yaml
  .github/workflows/release.yaml
  .goreleaser.yml
Labels: pull-request

#2741 fix: incorrect funding messages
  .goreleaser.yml
  packaging/homebrew/bee-get-addr
  pkg/settlement/swap/chequebook/init.go
Labels: pull-request

#2744 feat: enable homebrew arm64 installation
  .goreleaser.yml
  packaging/homebrew-amd64/bee-get-addr
  packaging/homebrew-amd64/bee.yaml
  packaging/homebrew-arm64/bee-get-addr
  packaging/homebrew-arm64/bee.yaml
Labels: pull-request

#2743 fix: inaccurate database capacity in dev mode
  pkg/node/devnode.go
Labels: pull-request

#2745 chore: bump base docker image
  Dockerfile
  Dockerfile.goreleaser
  Dockerfile.scratch
Labels: pull-request
