Repository ethersphere/bee, pull requests merged in 2021-03, with the labels that each got.

#1348 merge beekeeper and slash-beekeeper
  .github/workflows/beekeeper.yml
  .github/workflows/slash-beekeeper.yml
Labels: pull-request, ready for review

#1354 fix repository_dispatch type check
  .github/workflows/beekeeper.yml
Labels: pull-request

#1355 version: bump 0.5.3
  version.go
Labels: pull-request

#1356 fix repo dispatch for good
  .github/workflows/beekeeper.yml
Labels: pull-request

#1357 fix output of factory address
  go.sum
  pkg/node/chain.go
Labels: pull-request, ready for review

#1345 update to go-ethereum 1.9.23
  go.mod
  go.sum
  pkg/settlement/swap/chequebook/bindings.go
  pkg/settlement/swap/chequebook/cashout.go
  pkg/settlement/swap/chequebook/cashout_test.go
  pkg/settlement/swap/chequebook/chequebook.go
  pkg/settlement/swap/chequebook/common_test.go
  pkg/settlement/swap/chequebook/factory.go
  pkg/settlement/swap/chequebook/factory_test.go
Labels: pull-request, ready for review

#1363 Move cac validator to cac package
  pkg/cac/cac.go
  pkg/cac/cac_test.go
  pkg/content/validator.go
  pkg/content/validator_test.go
  pkg/pullsync/pullsync.go
  pkg/pushsync/pushsync.go
  pkg/retrieval/retrieval.go
Labels: clean-up, pull-request, ready for review

#1358 debug api basic and full routing
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/p2p.go
  pkg/debugapi/router.go
  pkg/debugapi/status.go
  pkg/node/node.go
Labels: pull-request, ready for review

#1368 remove go-log.v1 yet again
  go.mod
Labels: pull-request, ready for review

#1366 increase wait time in gc-chunk
  .github/workflows/beekeeper.yml
Labels: pull-request, ready for review

#1360 chequebook: better event parsing
  pkg/node/chain.go
  pkg/node/node.go
  pkg/settlement/swap/chequebook/bindings.go
  pkg/settlement/swap/chequebook/cashout.go
  pkg/settlement/swap/chequebook/cashout_test.go
  pkg/settlement/swap/chequebook/chequebook.go
  pkg/settlement/swap/chequebook/common_test.go
  pkg/settlement/swap/chequebook/factory.go
  pkg/settlement/swap/chequebook/factory_test.go
  pkg/settlement/swap/transaction/backend.go
  pkg/settlement/swap/transaction/event.go
  pkg/settlement/swap/transaction/event_test.go
Labels: pull-request, ready for review

#1313 clef: allow specifying account
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  pkg/crypto/clef/clef.go
  pkg/crypto/clef/clef_test.go
Labels: pull-request, ready for review

#1373 hive: add metrics
  pkg/hive/hive.go
  pkg/hive/metrics.go
Labels: pull-request, ready for review

#1381 libp2p: skip dns test entirely on windows
  pkg/p2p/libp2p/static_resolver_test.go
Labels: pull-request, ready for review

#1370 debug api as a concrete service
  pkg/debugapi/balances.go
  pkg/debugapi/chequebook.go
  pkg/debugapi/chunk.go
  pkg/debugapi/cors.go
  pkg/debugapi/cors_test.go
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/metrics.go
  pkg/debugapi/p2p.go
  pkg/debugapi/peer.go
  pkg/debugapi/pingpong.go
  pkg/debugapi/router.go
  pkg/debugapi/settlements.go
  pkg/debugapi/tag.go
  pkg/debugapi/topology.go
  pkg/debugapi/welcome_message.go
  pkg/node/node.go
Labels: pull-request, ready for review

#1377 prevent nodes from starting with a different overlay
  cmd/bee/cmd/deploy.go
  cmd/bee/cmd/init.go
  pkg/node/node.go
  pkg/node/statestore.go
Labels: pull-request, ready for review

#1391 Update coding guidelines
  CODING.md
Labels: pull-request, ready for review

#1383 streamtest: add option to add a correct base address
  pkg/p2p/streamtest/streamtest.go
  pkg/pricing/pricing_test.go
  pkg/pushsync/pushsync_test.go
  pkg/retrieval/retrieval_test.go
  pkg/settlement/pseudosettle/pseudosettle_test.go
Labels: pull-request, ready for review

#1390 libp2p: wait for readyness before accepting incoming connections
  pkg/node/node.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/libp2p_test.go
Labels: clean-up, pull-request, ready for review

#1361 chequebook: remove use of bindings for factory
  pkg/node/chain.go
  pkg/settlement/swap/chequebook/bindings.go
  pkg/settlement/swap/chequebook/common_test.go
  pkg/settlement/swap/chequebook/factory.go
  pkg/settlement/swap/chequebook/factory_test.go
  pkg/settlement/swap/transaction/mock/transaction.go
  pkg/settlement/swap/transaction/transaction.go
Labels: pull-request, ready for review

#1352 Limit incoming connections
  pkg/kademlia/export_test.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/node/node.go
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/mock/mock.go
  pkg/p2p/p2p.go
  pkg/topology/topology.go
Labels: pull-request, ready for review

#1399 kademlia, cmd, node: add bootnode-mode flag
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/node/node.go
Labels: clean-up, pull-request, ready for review

#1379 some housekeeping
  cmd/bee/cmd/start.go
  packaging/bee-get-addr
Labels: pull-request

#1400 libp2p: missing error check on TestStaticAddressResolver
  pkg/p2p/libp2p/static_resolver_test.go
Labels: pull-request, ready for review

#1407 kademlia: add bootnode connection timeout
  pkg/kademlia/kademlia.go
Labels: bug, pull-request, ready for review

#1401 pkg: suppress logging in tests
  pkg/api/bzz_test.go
  pkg/pushsync/pushsync_test.go
Labels: pull-request, ready for review

#1392 statestore: add migration capabilities
  pkg/statestore/leveldb/export_test.go
  pkg/statestore/leveldb/leveldb.go
  pkg/statestore/leveldb/leveldb_test.go
  pkg/statestore/leveldb/migration.go
  pkg/statestore/leveldb/migration_test.go
  pkg/statestore/mock/store.go
  pkg/statestore/test/store.go
Labels: pull-request, ready for review

#1386 pullsync: coalesce batch writes
  pkg/pullsync/pullsync.go
  pkg/pullsync/pullsync_test.go
Labels: pull-request, ready for review

#1408 libp2p: skip static resolver tests on windows completely
  pkg/p2p/libp2p/static_resolver_test.go
Labels: pull-request, ready for review

#1406 pipeline: add special case for empty file
  pkg/file/pipeline/builder/builder_test.go
  pkg/file/pipeline/feeder/feeder.go
  pkg/file/pipeline/feeder/feeder_test.go
Labels: bug, pull-request, ready for review

#1207 Balanced peers in kademlia
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/swarm/proximity.go
  pkg/swarm/swarm.go
Labels: pull-request, ready for review

#1410 Correct metrics to use Set instead of Put
  pkg/localstore/mode_set.go
Labels: pull-request, ready for review

#1417 Gc metric fix
  pkg/localstore/gc.go
Labels: pull-request, ready for review

#1416 pushsync: improve context handling
  pkg/pushsync/pushsync.go
Labels: pull-request, ready for review

#1424 localstore: increase gc batch size
  pkg/localstore/gc.go
  pkg/localstore/localstore.go
Labels: pull-request, ready for review

#1426 shed: return swallowed error
  pkg/shed/db.go
Labels: bug, pull-request, ready for review

#1427 localstore: improve metrics
  pkg/localstore/gc.go
  pkg/localstore/metrics.go
Labels: pull-request, ready for review

#1362 chequebook: remove erc20 bindings
  pkg/node/chain.go
  pkg/settlement/swap/chequebook/bindings.go
  pkg/settlement/swap/chequebook/chequebook.go
  pkg/settlement/swap/chequebook/chequebook_test.go
  pkg/settlement/swap/chequebook/common_test.go
  pkg/settlement/swap/chequebook/init.go
  pkg/settlement/swap/erc20/erc20.go
  pkg/settlement/swap/erc20/erc20_test.go
  pkg/settlement/swap/erc20/mock/erc20.go
Labels: pull-request, ready for review

#1430 pusher: less concurrent jobs
  pkg/pusher/pusher.go
Labels: pull-request, ready for review

#1432 readme: update godoc link
  README.md
Labels: pull-request, ready for review

#1420 set ENV var with run type
  .github/workflows/beekeeper.yml
Labels: pull-request

#1438 add --no-install-recommends to apt-get install
  Dockerfile
  Dockerfile.goreleaser
Labels: pull-request

#1394 Soc refactor
  pkg/api/bzz_test.go
  pkg/api/feed.go
  pkg/api/feed_test.go
  pkg/api/soc.go
  pkg/api/soc_test.go
  pkg/feeds/feed.go
  pkg/feeds/getter.go
  pkg/feeds/putter.go
  pkg/soc/export_test.go
  pkg/soc/soc.go
  pkg/soc/soc_test.go
  pkg/soc/testing/soc.go
  pkg/soc/validator.go
  pkg/soc/validator_test.go
Labels: pull-request, ready for review

#1435 localstore: reduce critical section size on gc
  pkg/localstore/gc.go
  pkg/localstore/gc_test.go
  pkg/localstore/localstore.go
  pkg/localstore/metrics.go
  pkg/localstore/mode_get.go
  pkg/localstore/mode_put.go
  pkg/localstore/mode_set.go
  pkg/swarm/swarm.go
  pkg/swarm/swarm_test.go
Labels: pull-request, ready for review

#1446 add metrics to track number of cheques
  pkg/settlement/swap/metrics.go
  pkg/settlement/swap/swap.go
Labels: pull-request, ready for review

#1384 localstore: improve CPU usage due to leveldb iterator
  pkg/flipflop/doc.go
  pkg/flipflop/falling_edge.go
  pkg/flipflop/falling_edge_test.go
  pkg/localstore/localstore.go
  pkg/localstore/subscription_pull.go
  pkg/localstore/subscription_push.go
Labels: pull-request, ready for review

#1447 reverted revert on disconnecting peers in Kadamlia - ClosestPeer
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
Labels: pull-request

#1448 skip flipflop tests
  pkg/flipflop/falling_edge_test.go
Labels: pull-request

#1449 kademlia: wait on peer before retrying after connect err
  pkg/kademlia/kademlia.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/metrics.go
Labels: pull-request, ready for review

#1452 localstore: fix data race in test
  pkg/localstore/gc.go
  pkg/localstore/gc_test.go
Labels: pull-request, ready for review

#1451 kademlia: check peer sanctioned when connecting on balanced loop
  pkg/kademlia/kademlia.go
Labels: bug, pull-request, ready for review

#1453 kademlia: balanced iterator erroneously exits but should continue
  pkg/kademlia/kademlia.go
Labels: pull-request, ready for review

#1456 flipflop: fix goroutine leak on subscription termination
  pkg/flipflop/falling_edge.go
Labels: bug, pull-request, ready for review

#1455 swap,sctx,debugapi: add optional gas limit and gas price to cashout
  pkg/debugapi/balances.go
  pkg/debugapi/balances_test.go
  pkg/debugapi/chequebook.go
  pkg/debugapi/chequebook_test.go
  pkg/debugapi/export_test.go
  pkg/debugapi/settlements.go
  pkg/debugapi/settlements_test.go
  pkg/sctx/sctx.go
  pkg/settlement/swap/chequebook/cashout.go
Labels: enhancement, pull-request, ready for review

#1454 shed, localstore, cmd: expose leveldb configuration parameters to cli
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  pkg/localstore/localstore.go
  pkg/node/node.go
  pkg/shed/db.go
  pkg/shed/db_test.go
  pkg/shed/example_store_test.go
Labels: pull-request, ready for review

#1457 Missing defers
  pkg/localstore/subscription_pull.go
  pkg/localstore/subscription_push.go
Labels: pull-request, ready for review

#1460 fix amount
  packaging/homebrew/bee-get-addr
Labels: pull-request, ready for review

#1462 add new config options to package config files
  packaging/bee.yaml
  packaging/docker/docker-compose.yml
  packaging/docker/env
  packaging/homebrew/bee.yaml
Labels: pull-request

#1464 docker-compose: update version
  packaging/docker/docker-compose.yml
Labels: pull-request

#1466 Add cashout endpoint parameters
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
Labels: pull-request

#1467 add nonce log line
  pkg/settlement/swap/transaction/transaction.go
Labels: pull-request, ready for review

#1468 set bee image to beta and adjust README
  packaging/docker/README.md
  packaging/docker/docker-compose.yml
Labels: pull-request

#1463 version: bump to 0.5.4
  version.go
Labels: pull-request

#1461 TestRetrievePreemptiveRetry fixed
  pkg/retrieval/retrieval_test.go
Labels: pull-request, ready for review

#1480 PSS API Test flakiness
  pkg/api/pss_test.go
Labels: flaky-test, pull-request

#1134 Pricing update strategy
  .github/workflows/beekeeper.yml
  pkg/accounting/accounting_test.go
  pkg/accounting/mock/pricer.go
  pkg/accounting/pricer.go
  pkg/node/node.go
  pkg/p2p/libp2p/headers.go
  pkg/p2p/libp2p/headers_test.go
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/p2p/libp2p/internal/handshake/mock/stream.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/stream.go
  pkg/p2p/p2p.go
  pkg/p2p/protobuf/protobuf_test.go
  pkg/p2p/streamtest/streamtest.go
  pkg/pricer/export_test.go
  pkg/pricer/headerutils/export_test.go
  pkg/pricer/headerutils/utilities.go
  pkg/pricer/headerutils/utilities_test.go
  pkg/pricer/mock/pricer.go
  pkg/pricer/pricer.go
  pkg/pricer/pricer_test.go
  pkg/pricing/pb/pricing.pb.go
  pkg/pricing/pb/pricing.proto
  pkg/pricing/pricing.go
  pkg/pricing/pricing_test.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/recovery/repair_test.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
Labels: pull-request, ready for review

#1484 swap: treat not found cashout transactions as pending
  pkg/settlement/swap/chequebook/cashout.go
Labels: pull-request, ready for review

#1402 chequebook: change cashout api to include uncashed amount
  openapi/SwarmCommon.yaml
  pkg/debugapi/chequebook.go
  pkg/debugapi/chequebook_test.go
  pkg/settlement/swap/chequebook/cashout.go
  pkg/settlement/swap/chequebook/cashout_test.go
Labels: pull-request, ready for review

#1489 version: bump to 0.6.0
  version.go
Labels: pull-request, ready for review

#1431 receipt is signed by storer node and verified by origin node
  pkg/crypto/mock/signer.go
  pkg/node/node.go
  pkg/pusher/pusher.go
  pkg/pusher/pusher_test.go
  pkg/pushsync/pb/pushsync.pb.go
  pkg/pushsync/pb/pushsync.proto
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
Labels: pull-request, ready for review

#1483 fix chown after init
  packaging/deb/postinst
  packaging/rpm/post
Labels: pull-request, ready for review

#1492 add fetch-depth: 0 to release
  .github/workflows/release.yaml
Labels: pull-request, ready for review

#1491 localstore: change pin gc test to reduce flakiness
  pkg/localstore/gc_test.go
Labels: pull-request, ready for review

#1494 pusher: receipt can only be nil for ErrWantSelf cases
  pkg/pusher/pusher.go
Labels: pull-request, ready for review

#1487 transaction: add extra gas everywhere
  pkg/settlement/swap/transaction/transaction.go
Labels: pull-request, ready for review

#1509 pss: mining metric
  pkg/pss/metrics.go
  pkg/pss/pss.go
Labels: pull-request, ready for review

#1510 kademlia: EachNeighbor funcs
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
Labels: pull-request, ready for review

#1495 pushsync: reduce logging
  pkg/pushsync/pushsync.go
Labels: pull-request, ready for review

#1262 batchstore: reserve
  Dockerfile
  Dockerfile.goreleaser
  pkg/node/node.go
  pkg/postage/batch.go
  pkg/postage/batch_test.go
  pkg/postage/batchservice/batchservice.go
  pkg/postage/batchservice/batchservice_test.go
  pkg/postage/batchstore/export_test.go
  pkg/postage/batchstore/mock/store.go
  pkg/postage/batchstore/mock/store_test.go
  pkg/postage/batchstore/reserve.go
  pkg/postage/batchstore/reserve_test.go
  pkg/postage/batchstore/store.go
  pkg/postage/batchstore/store_test.go
  pkg/postage/interface.go
  pkg/postage/listener/listener.go
  pkg/postage/listener/listener_test.go
Labels: pull-request, ready for review

#1514 increase delays in ci
  .github/workflows/beekeeper.yml
Labels: pull-request, ready for review

#1515 5s retry delay
  .github/workflows/beekeeper.yml
Labels: pull-request

#1470 add timeout
  .github/workflows/beekeeper.yml
Labels: pull-request

#1493 switch scoop package and binary files order
  .goreleaser.yml
Labels: pull-request
