Repository ethersphere/bee, pull requests merged in 2021-09, with the labels that each got.

#2429 fix: removed kademlia and libp2p discrepancy kludge
  pkg/topology/kademlia/kademlia.go
Labels: pull-request

#2462 feat(libp2p): add custom user agent and log it on connection
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/export_test.go
  pkg/p2p/libp2p/libp2p.go
Labels: ready for review, pull-request

#2456 fix: build custom beekeeper
  .github/workflows/beekeeper.yml
  Makefile
Labels: pull-request

#2461 chore: update libp2p version
  go.mod
  go.sum
Labels: ready for review, pull-request

#2469 fix: retrieval flaky test
  pkg/retrieval/retrieval_test.go
Labels: ready for review, pull-request

#2422 feat: verify own transaction
  pkg/node/node.go
Labels: ready for review, pull-request

#2463 feat: pss target input validation
  openapi/SwarmCommon.yaml
  pkg/api/pss.go
  pkg/api/pss_test.go
Labels: pull-request

#2458 fix: use correct prefix for ens entries
  pkg/resolver/client/ens/ens.go
Labels: ready for review, pull-request

#2468 refactor: move bin prefix logic to new file
  pkg/topology/kademlia/binprefix.go
  pkg/topology/kademlia/kademlia.go
Labels: ready for review, pull-request

#2476 chore: remove tag logline
  pkg/tags/tags.go
Labels: ready for review, pull-request

#2480 fix: ethereum address migration
  pkg/statestore/leveldb/migration.go
Labels: ready for review, pull-request

#2452 fix: inefficient kademlia metrics saving
  pkg/node/node.go
  pkg/statestore/leveldb/migration.go
  pkg/topology/kademlia/internal/metrics/metrics.go
  pkg/topology/kademlia/internal/metrics/metrics_test.go
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
Labels: ready for review, pull-request

#2412 feat: prune oversaturated bins when depth increases
  pkg/p2p/mock/mock.go
  pkg/topology/kademlia/binprefix.go
  pkg/topology/kademlia/export_test.go
  pkg/topology/kademlia/internal/metrics/metrics.go
  pkg/topology/kademlia/internal/metrics/metrics_test.go
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
Labels: ready for review, pull-request

#2483 fix: unit test
  pkg/topology/kademlia/internal/metrics/metrics_test.go
Labels: ready for review, pull-request

#2484 fix: added missing metric
  pkg/pushsync/pushsync.go
Labels: pull-request

#2471 feat: p2p disconnect with reason
  pkg/accounting/accounting.go
  pkg/accounting/accounting_test.go
  pkg/debugapi/peer.go
  pkg/debugapi/peer_test.go
  pkg/node/devnode.go
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/protocols_test.go
  pkg/p2p/mock/mock.go
  pkg/p2p/p2p.go
  pkg/p2p/streamtest/streamtest.go
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
Labels: ready for review, pull-request

#2482 fix: retry user agent get from libp2p peerstore
  pkg/p2p/libp2p/libp2p.go
Labels: ready for review, pull-request

#2486 chore: remove deepsource for good
  .github/workflows/go.yml
Labels: pull-request

#2453 feat: pslice 2d
  pkg/topology/lightnode/container_test.go
  pkg/topology/pslice/export_test.go
  pkg/topology/pslice/pslice.go
  pkg/topology/pslice/pslice_test.go
Labels: ready for review, pull-request

#2487 chore: improve metrics
  pkg/localstore/metrics.go
  pkg/localstore/mode_get_multi.go
  pkg/pushsync/metrics.go
  pkg/pushsync/pushsync.go
Labels: ready for review, pull-request

#2488 chore: add stale bot config
  .github/stale.yaml
Labels: pull-request

#2481 fix: recursive file joiner read
  pkg/file/joiner/joiner.go
  pkg/file/joiner/joiner_test.go
Labels: pull-request

#2475 feat: chainsync protocol
  go.mod
  pkg/chainsync/chainsync.go
  pkg/chainsync/chainsync_test.go
  pkg/chainsync/pb/chainsync.pb.go
  pkg/chainsync/pb/chainsync.proto
  pkg/chainsync/pb/doc.go
  pkg/chainsyncer/chainsyncer.go
  pkg/chainsyncer/chainsyncer_test.go
  pkg/chainsyncer/export_test.go
  pkg/chainsyncer/metrics.go
  pkg/node/node.go
Labels: ready for review, pull-request

#2493 chore: delete stale bot and replace with action
  .github/stale.yaml
  .github/workflows/stale.yaml
Labels: pull-request

#2489 fix: filter out filename path
  pkg/api/bzz.go
  pkg/api/bzz_test.go
Labels: pull-request

#2495 chore: update golang and ldb
  .github/workflows/go.yml
  .github/workflows/release.yaml
  Dockerfile
  go.mod
  go.sum
Labels: ready for review, pull-request

#2425 fix: random generation of tag uids
  pkg/tags/tags.go
  pkg/tags/tags_test.go
Labels: ready for review, pull-request

#2500 fix: updated go version in beelocal tests
  .github/workflows/beekeeper.yml
Labels: pull-request

#2333 refactor: move welcome message into separate file
  cmd/bee/cmd/bee-welcome-message.txt
  cmd/bee/cmd/start.go
Labels: ready for review, pull-request

#2490 feat: add handshake protocol messages metrics
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/p2p/libp2p/internal/handshake/metrics.go
  pkg/p2p/libp2p/metrics.go
Labels: ready for review, pull-request

#2497 feat: extra metrics for connectivity
  pkg/hive/hive.go
  pkg/hive/metrics.go
Labels: pull-request

#2498 feat: ping time metric
  pkg/hive/hive.go
  pkg/hive/metrics.go
Labels: ready for review, pull-request

#2502 feat: invalid stamp metric
  pkg/pushsync/metrics.go
  pkg/pushsync/pushsync.go
Labels: ready for review, pull-request

#2491 feat: skip validation if peer is known
  pkg/hive/hive.go
  pkg/hive/hive_test.go
  pkg/node/node.go
Labels: ready for review, pull-request

#2504 chore: lint
  pkg/hive/metrics.go
Labels: pull-request

#2506 ci: move coverage step
  .github/workflows/go.yml
Labels: pull-request

#2510 ci: test once
  .github/workflows/go.yml
  Makefile
Labels: pull-request

#2511 fix: add peer to cache if found in addressbook
  pkg/hive/hive.go
Labels: ready for review, pull-request

#2513 refactor: add p2p headers exchange duration metrics
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/metrics.go
Labels: ready for review, pull-request

#2514 fix(kademlia): change metric histogram resolution to seconds
  pkg/topology/kademlia/kademlia.go
Labels: ready for review, pull-request

#2503 chore: update go to 1.17
  .github/workflows/beekeeper.yml
  .github/workflows/go.yml
  .github/workflows/release.yaml
  Dockerfile
  go.mod
  go.sum
  pkg/pullsync/pullstorage/pullstorage.go
Labels: ready for review, on hold, pull-request

#2519 chore: bump 1.2.0
  version.go
Labels: pull-request

#2520 refactor(pushsync): better tracing
  pkg/pushsync/pushsync.go
Labels: ready for review, pull-request

#2525 ci: disable coveralls
  .github/workflows/go.yml
Labels: pull-request

#2524 fix: continue forwarding if replication fails
  pkg/pushsync/pushsync.go
Labels: ready for review, pull-request

#2508 feat: more pushsync metrics
  pkg/pushsync/metrics.go
  pkg/pushsync/pushsync.go
Labels: ready for review, pull-request

#2512 feat(kademlia): static nodes
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  pkg/node/node.go
  pkg/topology/kademlia/export_test.go
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
Labels: ready for review, pull-request

#2509 feat: metrics for non closest storer
  pkg/pushsync/metrics.go
  pkg/pushsync/pushsync.go
Labels: pull-request

#2528 chore: added more logs to pushsync
  pkg/pushsync/pushsync.go
Labels: pull-request

#2527 refactor: closer func
  pkg/pushsync/pushsync.go
  pkg/retrieval/retrieval.go
  pkg/swarm/swarm.go
  pkg/swarm/swarm_test.go
  pkg/topology/kademlia/kademlia.go
Labels: ready for review, pull-request

#2537 fix: fix swap migraton state store corruption
  pkg/statestore/leveldb/migration.go
Labels: ready for review, pull-request

#2529 fix: switched to each peer iterator for pushsync replication
  pkg/pushsync/pushsync.go
Labels: ready for review, pull-request

#2534 fix(localstore): stale push index items
  pkg/localstore/gc.go
  pkg/localstore/migration.go
  pkg/localstore/migration_dead_push.go
  pkg/localstore/mode_set.go
  pkg/localstore/schema.go
Labels: pull-request

#2541 opt: handshake handle checks with kademlia pick before overlay verification
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/p2p/libp2p/internal/handshake/handshake_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/p2p.go
Labels: ready for review, pull-request

#2526 fix: removed neighborhood check for replication
  pkg/pushsync/metrics.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/topology/kademlia/kademlia.go
Labels: ready for review, pull-request

#2539 fix: handle background broadcasts using separate context
  pkg/discovery/mock/mock.go
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
Labels: ready for review, pull-request

#2538 fix: avoid advertising private IP addresses to the public network
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  pkg/hive/hive.go
  pkg/hive/hive_test.go
  pkg/node/node.go
Labels: ready for review, pull-request

#2543 feat: kademlia blocklists peer on ping timeout
  pkg/blocker/blocker.go
  pkg/blocker/blocker_test.go
  pkg/p2p/p2p.go
  pkg/topology/kademlia/kademlia.go
Labels: ready for review, pull-request

#2547 chore: increase ping interval
  pkg/topology/kademlia/export_test.go
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
Labels: pull-request

#2548 refactor: kademlia close err group
  pkg/topology/kademlia/kademlia.go
Labels: pull-request

#2546 fix: persist postage stamps on add
  pkg/node/devnode.go
  pkg/postage/batchservice/batchservice.go
  pkg/postage/batchservice/batchservice_test.go
  pkg/postage/interface.go
  pkg/postage/mock/service.go
  pkg/postage/postagecontract/contract.go
  pkg/postage/service.go
  pkg/postage/service_test.go
Labels: pull-request

#2523 docs(openapi): add array of swarm addresses to topology bins
  openapi/SwarmCommon.yaml
Labels: pull-request
