Repository ethersphere/bee, pull requests merged in 2021-06, with the labels that each got.

#1952 fix: granular pss errors
  pkg/api/pss.go
Labels: pull-request

#1877 add support for slim docker image release
  .goreleaser.yml
  Dockerfile.scratch
Labels: pull-request

#1931 feat: makefile beekeeper
  .github/workflows/beekeeper.yml
  Makefile
Labels: pull-request

#1956 ci: add coveralls
  .github/workflows/go.yml
  README.md
Labels: pull-request, ready for review

#1955 chore: fix comment typo
  pkg/swarm/distance.go
Labels: pull-request

#1953 fix: #/components/schemas/ProblemDetails definition was incorrect
  openapi/SwarmCommon.yaml
Labels: pull-request

#1833 add miss env in docker-compose
  packaging/docker/docker-compose.yml
Labels: pull-request

#1957 feat: fix contract versions
  .github/workflows/beekeeper.yml
Labels: pull-request, ready for review

#1961 chore: same stamp unit test
  pkg/api/postage_test.go
  pkg/localstore/export.go
  pkg/localstore/mode_put.go
  pkg/localstore/mode_put_test.go
Labels: pull-request, ready for review

#1960 feat(kademlia): add prometheus metrics
  pkg/node/node.go
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/metrics.go
Labels: pull-request, ready for review

#1977 feat(pusher): receipt depth metric
  pkg/pusher/metrics.go
  pkg/pusher/pusher.go
Labels: pull-request

#1979 feat(lightnode,libp2p): add prometheus metrics
  pkg/node/node.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/metrics.go
  pkg/topology/lightnode/container.go
  pkg/topology/lightnode/metrics.go
Labels: pull-request, ready for review

#1980 fix(steward): swallow ErrWantSelf
  pkg/steward/steward.go
  pkg/steward/steward_test.go
Labels: bug, pull-request, ready for review

#1989 fix(kademlia): flaky prune test
  pkg/topology/kademlia/kademlia_test.go
Labels: pull-request

#1990 fix(libp2p): rename kickedout peers counter
  pkg/p2p/libp2p/metrics.go
Labels: pull-request, ready for review

#1912 fix: shutdown only once
  pkg/node/node.go
Labels: pull-request, ready for review

#1992 ci: apply patches earlier
  .github/workflows/beekeeper.yml
Labels: pull-request

#2013 feat: add more metrics to accounting and settlements
  go.mod
  pkg/accounting/accounting.go
  pkg/accounting/metrics.go
  pkg/settlement/pseudosettle/metrics.go
  pkg/settlement/pseudosettle/pseudosettle.go
Labels: pull-request, ready for review

#2018 feat: reduce required eth
  pkg/settlement/swap/chequebook/init.go
Labels: pull-request, ready for review

#2015 fix: update go-ethereum
  go.mod
  go.sum
  pkg/transaction/sender_matcher_test.go
Labels: pull-request

#1735 fix: marshal bigint as string
  openapi/SwarmCommon.yaml
  pkg/bigint/bigint.go
  pkg/bigint/bigint_test.go
  pkg/debugapi/balances.go
  pkg/debugapi/balances_test.go
  pkg/debugapi/chequebook.go
  pkg/debugapi/chequebook_test.go
  pkg/debugapi/export_test.go
  pkg/debugapi/postage.go
  pkg/debugapi/postage_test.go
  pkg/debugapi/settlements.go
  pkg/debugapi/settlements_test.go
  pkg/postage/chainstate.go
  pkg/postage/reservestate.go
Labels: pull-request

#2028 refactor(kademlia): speeding up topology build
  pkg/topology/kademlia/export_test.go
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
Labels: pull-request

#2037 fix: api errors related to postage stamps
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  pkg/api/bytes.go
  pkg/api/bzz.go
  pkg/api/chunk.go
  pkg/api/dirs.go
  pkg/api/pss.go
Labels: pull-request

#2046 fix: don't log checking pending transactions as errors
  pkg/transaction/monitor.go
Labels: pull-request, ready for review

#1625 feat: postage stamp indexing
  .github/patches/listener.patch
  .github/patches/postagecontract.patch
  .github/workflows/beekeeper.yml
  go.mod
  go.sum
  pkg/api/postage.go
  pkg/api/postage_test.go
  pkg/localstore/export.go
  pkg/localstore/export_test.go
  pkg/localstore/gc.go
  pkg/localstore/gc_test.go
  pkg/localstore/localstore.go
  pkg/localstore/localstore_test.go
  pkg/localstore/mode_get.go
  pkg/localstore/mode_get_multi.go
  pkg/localstore/mode_get_test.go
  pkg/localstore/mode_put.go
  pkg/localstore/mode_put_test.go
  pkg/localstore/mode_set.go
  pkg/localstore/mode_set_test.go
  pkg/localstore/reserve_test.go
  pkg/localstore/subscription_push.go
  pkg/postage/batch.go
  pkg/postage/batch_test.go
  pkg/postage/batchservice/batchservice.go
  pkg/postage/batchservice/batchservice_test.go
  pkg/postage/batchstore/mock/store.go
  pkg/postage/batchstore/mock/store_test.go
  pkg/postage/export_test.go
  pkg/postage/interface.go
  pkg/postage/listener/listener.go
  pkg/postage/listener/listener_test.go
  pkg/postage/postagecontract/contract.go
  pkg/postage/postagecontract/contract_test.go
  pkg/postage/postagecontract/mock/contract.go
  pkg/postage/stamp.go
  pkg/postage/stamp_test.go
  pkg/postage/stamper.go
  pkg/postage/stamper_test.go
  pkg/postage/stampissuer.go
  pkg/postage/stampissuer_test.go
  pkg/postage/testing/batch.go
  pkg/postage/testing/stamp.go
  pkg/pushsync/pushsync_test.go
  pkg/recovery/repair_test.go
  pkg/shed/example_store_test.go
  pkg/shed/index.go
  pkg/storage/store.go
  pkg/swarm/swarm.go
Labels: pull-request, ready for review

#2060 feat: enable support for releasing rc
  .goreleaser.yml
Labels: pull-request

#1780 feat: Retrial behavior in retrieval
  pkg/netstore/netstore.go
  pkg/netstore/netstore_test.go
  pkg/recovery/repair_test.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
  pkg/retrieval/skip_peers.go
Labels: pull-request

#1870 feat: Maintain originated balance
  pkg/accounting/accounting.go
  pkg/accounting/accounting_test.go
  pkg/accounting/metrics.go
  pkg/accounting/mock/accounting.go
  pkg/pushsync/pushsync.go
  pkg/retrieval/retrieval.go
Labels: pull-request, ready for review

#1924 feat: Negotiate cheques
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  go.mod
  go.sum
  pkg/accounting/accounting.go
  pkg/accounting/accounting_test.go
  pkg/node/chain.go
  pkg/node/node.go
  pkg/p2p/streamtest/streamtest.go
  pkg/pricing/pricing.go
  pkg/settlement/swap/addressbook.go
  pkg/settlement/swap/chequebook/chequestore.go
  pkg/settlement/swap/chequebook/chequestore_test.go
  pkg/settlement/swap/chequebook/mock/chequebook.go
  pkg/settlement/swap/chequestore/mock/chequestore.go
  pkg/settlement/swap/headers/export_test.go
  pkg/settlement/swap/headers/utilities.go
  pkg/settlement/swap/headers/utilities_test.go
  pkg/settlement/swap/mock/swap.go
  pkg/settlement/swap/priceoracle/mock/priceoracle.go
  pkg/settlement/swap/priceoracle/priceoracle.go
  pkg/settlement/swap/priceoracle/priceoracle_test.go
  pkg/settlement/swap/swap.go
  pkg/settlement/swap/swap_test.go
  pkg/settlement/swap/swapprotocol/export_test.go
  pkg/settlement/swap/swapprotocol/swapprotocol.go
  pkg/settlement/swap/swapprotocol/swapprotocol_test.go
Labels: pull-request, ready for review

#2065 feat: add xdai addresses
  pkg/postage/listener/listener.go
  pkg/settlement/swap/chequebook/factory.go
  pkg/settlement/swap/priceoracle/priceoracle.go
Labels: pull-request, ready for review

#2067 chore: bump v1.0.0
  version.go
Labels: pull-request

#2072 fix: revert "fix: update go-ethereum (#2015)"
  go.mod
  go.sum
  pkg/transaction/sender_matcher_test.go
Labels: pull-request

#2073 feat: add support for tagging docker image with prerelease version
  .goreleaser.yml
Labels: pull-request

#2063 feat(postage): stampissuer usability
  .github/patches/postageservice.patch
  .github/workflows/beekeeper.yml
  openapi/SwarmCommon.yaml
  pkg/api/api_test.go
  pkg/api/bzz.go
  pkg/api/feed.go
  pkg/api/feed_test.go
  pkg/api/postage.go
  pkg/api/postage_test.go
  pkg/api/pss.go
  pkg/api/pss_test.go
  pkg/api/soc.go
  pkg/api/soc_test.go
  pkg/node/node.go
  pkg/postage/export_test.go
  pkg/postage/mock/service.go
  pkg/postage/postagecontract/contract.go
  pkg/postage/service.go
  pkg/postage/service_test.go
  pkg/postage/stamp_test.go
  pkg/postage/stamper_test.go
  pkg/postage/stampissuer.go
  pkg/postage/stampissuer_test.go
Labels: pull-request, ready for review

#2003 chore: error log info
  pkg/topology/kademlia/kademlia.go
Labels: pull-request

#2051 feat: extend information returned by GET /stamps
  go.mod
  go.sum
  openapi/SwarmCommon.yaml
  pkg/api/api_test.go
  pkg/api/feed_test.go
  pkg/api/postage.go
  pkg/api/postage_test.go
  pkg/api/pss_test.go
  pkg/api/soc_test.go
  pkg/postage/batch.go
  pkg/postage/mock/service.go
  pkg/postage/postagecontract/contract.go
  pkg/postage/service.go
  pkg/postage/service_test.go
  pkg/postage/stamp_test.go
  pkg/postage/stamper.go
  pkg/postage/stamper_test.go
  pkg/postage/stampissuer.go
  pkg/postage/stampissuer_test.go
Labels: pull-request, ready for review

#2081 fix(pusher): dont increment missing tags
  pkg/pusher/pusher.go
Labels: pull-request

#2049 pusher: retry shallow receipts
  pkg/pusher/export_test.go
  pkg/pusher/metrics.go
  pkg/pusher/pusher.go
  pkg/pusher/pusher_test.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/topology/mock/mock.go
  pkg/topology/topology.go
Labels: pull-request

#2080 fix: recover stampissuer on batch creation
  openapi/Swarm.yaml
  pkg/api/chunk.go
  pkg/node/node.go
  pkg/postage/batchservice/batchservice.go
  pkg/postage/batchservice/batchservice_test.go
  pkg/postage/interface.go
  pkg/postage/mock/service.go
  pkg/postage/service.go
  pkg/postage/service_test.go
Labels: pull-request, ready for review

#2016 fix: delay concluding attempt in pushsync
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
Labels: pull-request, ready for review

#2095 fix: new stamp issuer call
  pkg/postage/service.go
Labels: pull-request, ready for review

#2097 fix: pushsync test limits
  pkg/pushsync/pushsync_test.go
Labels: pull-request

#2102 fix: don't disconnect on non-swap peers
  pkg/node/chain.go
  pkg/settlement/swap/swap.go
  pkg/settlement/swap/swap_test.go
Labels: pull-request, ready for review

#1983 feat: Always reset balances to zero after disconnection or blocklisting
  pkg/accounting/accounting.go
  pkg/accounting/accounting_test.go
  pkg/accounting/mock/accounting.go
  pkg/node/node.go
  pkg/pushsync/pushsync.go
  pkg/retrieval/retrieval.go
  pkg/settlement/interface.go
  pkg/settlement/pseudosettle/pseudosettle.go
  pkg/settlement/pseudosettle/pseudosettle_test.go
  pkg/settlement/swap/swap_test.go
Labels: pull-request, ready for review

#2101 fix: set explicit gas limits
  pkg/postage/postagecontract/contract.go
  pkg/settlement/swap/chequebook/chequebook.go
  pkg/settlement/swap/chequebook/factory.go
  pkg/settlement/swap/erc20/erc20.go
Labels: pull-request, ready for review

#2082 refactor(kademlia): add peers at start asynchronously
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
  pkg/topology/kademlia/metrics.go
Labels: pull-request, ready for review

#2100 feat: disconnect from peer upon refreshment attempt being reset
  pkg/accounting/accounting.go
  pkg/settlement/pseudosettle/pseudosettle.go
Labels: pull-request, ready for review

#1469 feat: add various transaction endpoint and track pending transactions
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/export_test.go
  pkg/debugapi/router.go
  pkg/debugapi/transaction.go
  pkg/debugapi/transaction_test.go
  pkg/node/node.go
  pkg/settlement/swap/chequebook/cashout.go
  pkg/settlement/swap/chequebook/chequebook.go
  pkg/settlement/swap/chequebook/factory.go
  pkg/settlement/swap/erc20/erc20.go
  pkg/transaction/export_test.go
  pkg/transaction/mock/transaction.go
  pkg/transaction/transaction.go
  pkg/transaction/transaction_test.go
Labels: pull-request, ready for review

#2104 docs: add commit message convention to the CODING.md
  CODING.md
Labels: pull-request, ready for review

#2099 fix: bucket depth size expectation
  pkg/postage/postagecontract/contract.go
  pkg/postage/postagecontract/contract_test.go
Labels: pull-request, ready for review

#2107 debugapi: less messages on pingpong
  pkg/debugapi/pingpong.go
Labels: pull-request, ready for review

#2110 chore: increment handshake protocol
  pkg/p2p/libp2p/internal/handshake/handshake.go
Labels: pull-request

#2115 fix(pushsync): originator replication
  pkg/pusher/pusher_test.go
  pkg/pushsync/pushsync.go
Labels: pull-request, ready for review

#2116 fix: recompute expected debt after time settlement
  pkg/accounting/accounting.go
  pkg/accounting/accounting_test.go
Labels: pull-request, ready for review

#2120 feat: Detailed accounting disconnect metrics
  pkg/accounting/accounting.go
  pkg/accounting/metrics.go
Labels: pull-request, ready for review

#2124 fix: move a misplaced unlock
  pkg/accounting/accounting.go
Labels: pull-request, ready for review

#2112 feat(localstore): add migration for batch-index
  cmd/bee/cmd/db.go
  pkg/localstore/gc_test.go
  pkg/localstore/localstore.go
  pkg/localstore/localstore_test.go
  pkg/localstore/migration.go
  pkg/localstore/migration_batch_index.go
  pkg/localstore/migration_test.go
  pkg/localstore/migration_yuj.go
  pkg/localstore/schema.go
  pkg/node/node.go
  pkg/pullsync/pullstorage/pullstorage_test.go
  pkg/pusher/pusher_test.go
Labels: pull-request, ready for review

#2128 fix: duplicate stampissuers
  pkg/postage/service.go
Labels: bug, pull-request, ready for review

#2127 fix: origin credit in replication
  pkg/pushsync/pushsync.go
Labels: pull-request, ready for review

#2130 fix: faster kademlia startup
  pkg/topology/kademlia/kademlia.go
Labels: pull-request

#2108 feat: non-mineable overlays
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/deploy.go
  cmd/bee/cmd/init.go
  cmd/bee/cmd/start.go
  go.mod
  go.sum
  pkg/addressbook/addressbook_test.go
  pkg/bzz/address.go
  pkg/bzz/address_test.go
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/p2p.go
  pkg/debugapi/p2p_test.go
  pkg/debugapi/peer_test.go
  pkg/hive/hive.go
  pkg/hive/hive_test.go
  pkg/hive/pb/hive.pb.go
  pkg/hive/pb/hive.proto
  pkg/node/chain.go
  pkg/node/node.go
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/p2p/libp2p/internal/handshake/handshake_test.go
  pkg/p2p/libp2p/libp2p_test.go
  pkg/pusher/pusher.go
  pkg/pusher/pusher_test.go
  pkg/pushsync/pb/pushsync.pb.go
  pkg/pushsync/pb/pushsync.proto
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/settlement/swap/swap.go
  pkg/settlement/swap/swap_test.go
  pkg/settlement/swap/swapprotocol/swapprotocol.go
  pkg/topology/kademlia/kademlia_test.go
  pkg/transaction/backend.go
  pkg/transaction/backendmock/backend.go
  pkg/transaction/backendsimulation/backend.go
  pkg/transaction/monitor.go
  pkg/transaction/monitormock/monitor.go
  pkg/transaction/sender_matcher.go
  pkg/transaction/sender_matcher_test.go
Labels: pull-request, ready for review

#2126 fix: add Ethereum address field
  pkg/bzz/address.go
  pkg/debugapi/peer.go
  pkg/debugapi/peer_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/p2p.go
  pkg/settlement/swap/addressbook.go
  pkg/settlement/swap/swap.go
  pkg/settlement/swap/swap_test.go
  pkg/settlement/swap/swapprotocol/swapprotocol.go
  pkg/settlement/swap/swapprotocol/swapprotocol_test.go
Labels: pull-request

#2133 fix: old node overlay migration
  pkg/node/statestore.go
Labels: pull-request, ready for review

#2136 fix: flush stamps
  pkg/statestore/leveldb/migration.go
Labels: pull-request

#2135 fix: non-blocking calls in pseudosettle
  pkg/accounting/accounting.go
  pkg/accounting/accounting_test.go
  pkg/settlement/pseudosettle/pseudosettle.go
Labels: pull-request, ready for review

#2138 chore: disable test
  pkg/topology/kademlia/kademlia_test.go
Labels: pull-request

#2139 fix: update network id value
  cmd/bee/cmd/cmd.go
Labels: pull-request

#2142 feat: change global bandwidth refreshment rate
  pkg/node/node.go
Labels: pull-request, ready for review

#2071 feat: unreserve on-demand
  .github/patches/postagereserve_gc.patch
  .github/workflows/beekeeper.yml
  pkg/debugapi/postage.go
  pkg/localstore/gc.go
  pkg/localstore/gc_test.go
  pkg/localstore/localstore.go
  pkg/localstore/metrics.go
  pkg/localstore/mode_put.go
  pkg/localstore/mode_set.go
  pkg/localstore/mode_set_test.go
  pkg/localstore/reserve.go
  pkg/localstore/reserve_test.go
  pkg/node/node.go
  pkg/postage/batchstore/export_test.go
  pkg/postage/batchstore/mock/store.go
  pkg/postage/batchstore/reserve.go
  pkg/postage/batchstore/reserve_test.go
  pkg/postage/batchstore/store.go
  pkg/postage/batchstore/store_test.go
  pkg/postage/interface.go
  pkg/postage/reservestate.go
Labels: pull-request, ready for review

#2144 chore: remove logging from localstore
  pkg/localstore/gc.go
  pkg/localstore/reserve.go
Labels: pull-request

#2145 fix(transaction): add a missing return, implement a mock function
  pkg/transaction/transaction.go
  pkg/transaction/transaction_test.go
Labels: pull-request, ready for review

#2146 fix: address delete
  pkg/statestore/leveldb/migration.go
Labels: pull-request

#2155 fix: update thresholds in packaging
  packaging/bee.yaml
  packaging/docker/env
  packaging/homebrew/bee.yaml
  packaging/scoop/bee.yaml
Labels: pull-request, ready for review

#2152 fix: seconds in overdraft blocklist
  pkg/accounting/accounting.go
Labels: pull-request, ready for review

#2156 fix: delete blocklist entries
  pkg/statestore/leveldb/migration.go
Labels: pull-request, ready for review

#2154 fix: introduce max threshold
  pkg/node/node.go
Labels: pull-request, ready for review

#2147 add disclaimer
  README.md
  cmd/bee/cmd/start.go
Labels: pull-request

#2157 fix: remove whatsoever
  README.md
  cmd/bee/cmd/start.go
Labels: pull-request

#2148 Update start.go
  README.md
  cmd/bee/cmd/start.go
Labels: pull-request

#2160 fix: cache verifications
  pkg/node/node.go
  pkg/transaction/sender_matcher.go
  pkg/transaction/sender_matcher_test.go
Labels: pull-request, ready for review

#2158 feat: time based warning
  Makefile
  cmd/bee/cmd/start.go
  cmd/bee/cmd/timebomb.go
  version.go
Labels: pull-request, ready for review

#2161 feat: add greylist to sender matcher
  pkg/transaction/export_test.go
  pkg/transaction/sender_matcher.go
  pkg/transaction/sender_matcher_test.go
Labels: pull-request, ready for review

#2162 feat(kademlia): AddPeers batch on Start
  pkg/addressbook/addressbook.go
  pkg/topology/kademlia/kademlia.go
Labels: pull-request, ready for review

#2164 fix: flaky test
  pkg/localstore/gc_test.go
Labels: pull-request, ready for review

#2163 feat(batchstore): add storage radius metric
  pkg/postage/batchstore/metrics.go
  pkg/postage/batchstore/reserve.go
Labels: pull-request, ready for review

#2093 fix: add peer in topology through the debug api
  pkg/debugapi/peer.go
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/p2p.go
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
  pkg/topology/kademlia/mock/kademlia.go
  pkg/topology/mock/mock.go
  pkg/topology/topology.go
Labels: pull-request, ready for review

#2166 perf: tiny peer string optimization
  pkg/transaction/sender_matcher.go
Labels: pull-request

#2168 fix: only greylist after error
  pkg/transaction/sender_matcher.go
Labels: pull-request, ready for review

#2170 fix: check network id before backend call
  pkg/p2p/libp2p/internal/handshake/handshake.go
Labels: pull-request

#2159 feat: main net flag
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  packaging/bee.yaml
  packaging/docker/docker-compose.yml
  packaging/docker/env
  packaging/homebrew/bee.yaml
  packaging/scoop/bee.yaml
Labels: pull-request, ready for review

#2172 chore: warmup time increase
  cmd/bee/cmd/cmd.go
Labels: pull-request

#2173 chore: remove Prerelease docker tag
  .goreleaser.yml
Labels: pull-request

#2070 bump to 1.0.1
  version.go
Labels: pull-request

#2171 refactor: move stamps API to debug API
  pkg/api/export_test.go
  pkg/api/postage.go
  pkg/api/postage_test.go
  pkg/api/router.go
  pkg/debugapi/chequebook.go
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/export_test.go
  pkg/debugapi/postage.go
  pkg/debugapi/postage_test.go
  pkg/debugapi/router.go
  pkg/node/node.go
Labels: pull-request

#2174 chore: change beta tag to stable
  .goreleaser.yml
Labels: pull-request

#2175 feat: use default stamp issuer on missing postage batch id header
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/bytes.go
  pkg/api/bzz.go
  pkg/api/chunk.go
  pkg/api/feed.go
  pkg/api/feed_test.go
  pkg/api/pss.go
  pkg/api/pss_test.go
  pkg/api/soc.go
  pkg/api/soc_test.go
  pkg/debugapi/postage.go
  pkg/debugapi/router.go
  pkg/postage/mock/service.go
  pkg/postage/service.go
Labels: pull-request

#2178 fix: align OpenAPI spec with the server implementation
  openapi/Swarm.yaml
  openapi/SwarmDebug.yaml
Labels: pull-request, ready for review

#2179 fix: always enable tx api
  pkg/debugapi/router.go
Labels: pull-request, ready for review

#2196 fix: add commit time in releaser
  .goreleaser.yml
Labels: pull-request

#2186 fix: change bee-mainnet to mainnet in yaml config file
  packaging/bee.yaml
  packaging/homebrew/bee.yaml
  packaging/scoop/bee.yaml
Labels: pull-request

#2193 fix: override block time for mainnet
  cmd/bee/cmd/start.go
Labels: pull-request, ready for review

#2212 feat: add tx cancel
  openapi/SwarmDebug.yaml
  pkg/debugapi/router.go
  pkg/debugapi/transaction.go
  pkg/debugapi/transaction_test.go
  pkg/transaction/mock/transaction.go
  pkg/transaction/transaction.go
  pkg/transaction/transaction_test.go
Labels: pull-request, ready for review

#2211 feat: more blockchain related logging
  pkg/node/chain.go
  pkg/transaction/backend.go
  pkg/transaction/backend_test.go
Labels: pull-request, ready for review

#2210 feat: early tx api
  pkg/debugapi/debugapi.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/router.go
  pkg/node/chain.go
  pkg/node/node.go
Labels: pull-request, ready for review

#2214 fix: verify signer result
  pkg/crypto/clef/clef.go
Labels: pull-request, ready for review

#2218 fix: remove unnecessary dependencies for traversal
  pkg/traversal/traversal.go
Labels: pull-request, ready for review

#2219 revert: default stamp issuer
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/bytes.go
  pkg/api/bzz.go
  pkg/api/chunk.go
  pkg/api/feed.go
  pkg/api/feed_test.go
  pkg/api/pss.go
  pkg/api/pss_test.go
  pkg/api/soc.go
  pkg/api/soc_test.go
  pkg/debugapi/postage.go
  pkg/debugapi/router.go
  pkg/postage/mock/service.go
  pkg/postage/service.go
Labels: pull-request, ready for review

#2203 Changed Ethereum address message
  packaging/bee-get-addr
Labels: pull-request

#2228 fix: continue processing pullsync batch on unverifiable stamp
  pkg/pullsync/pullsync.go
Labels: pull-request, ready for review

#2231 revert: default stamp issuer OpenAPI debug endpoint
  openapi/SwarmDebug.yaml
Labels: pull-request, ready for review

#2235 feat: rate limit hive broadcast calls
  pkg/hive/hive.go
  pkg/hive/hive_test.go
  pkg/ratelimit/ratelimit.go
  pkg/ratelimit/ratelimit_test.go
Labels: pull-request, ready for review
