Repository ethersphere/bee, pull requests merged in 2021-02, with the labels that each got.

#1182 postage: bigger page size
  pkg/postage/listener/listener.go
Labels: pull-request

#1183 postage: handle bucket depth error in api
  pkg/api/postage.go
  pkg/api/postage_test.go
Labels: pull-request

#1120 feeds: add feed resolution
  pkg/feeds/epochs/epoch.go
  pkg/feeds/epochs/finder.go
  pkg/feeds/epochs/lookup_benchmark_test.go
  pkg/feeds/epochs/lookup_test.go
  pkg/feeds/epochs/updater.go
  pkg/feeds/feed.go
  pkg/feeds/getter.go
  pkg/feeds/putter.go
  pkg/feeds/sequence/lookup_benchmark_test.go
  pkg/feeds/sequence/lookup_test.go
  pkg/feeds/sequence/sequence.go
  pkg/feeds/testing/lookup.go
  pkg/soc/soc.go
Labels: pull-request, ready for review

#1143 api: split chunk and soc api
  cmd/internal/file/io.go
  pkg/api/api_test.go
  pkg/api/chunk.go
  pkg/api/chunk_test.go
  pkg/api/export_test.go
  pkg/api/gatewaymode_test.go
  pkg/api/pin_chunks_test.go
  pkg/api/router.go
  pkg/api/soc.go
  pkg/api/soc_test.go
  pkg/api/tag_test.go
  pkg/soc/soc.go
Labels: pull-request, ready for review

#1190 fix: conditionally enable chequebook endpoints
  pkg/debugapi/router.go
Labels: pull-request

#1192 localstore: attach stamp to outgoing chunk
  pkg/localstore/subscription_push.go
Labels: pull-request, ready for review

#1186 wait for clef on startup
  cmd/bee/cmd/start.go
Labels: pull-request

#1148 Simplify public tags API response
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/bytes.go
  pkg/api/chunk.go
  pkg/api/dirs.go
  pkg/api/export_test.go
  pkg/api/file.go
  pkg/api/router.go
  pkg/api/tag.go
  pkg/api/tag_test.go
  pkg/debugapi/export_test.go
  pkg/debugapi/router.go
  pkg/debugapi/tag.go
  pkg/debugapi/tag_test.go
  pkg/localstore/mode_set_test.go
  pkg/manifest/manifest.go
  pkg/manifest/mantaray.go
  pkg/manifest/simple.go
  pkg/pusher/pusher_test.go
  pkg/pushsync/pushsync_test.go
  pkg/swarm/swarm.go
  pkg/tags/tag.go
  pkg/tags/tag_test.go
  pkg/tags/tags.go
  pkg/tags/tags_test.go
Labels: pull-request, ready for review

#1176 pushsync: clean up
  pkg/pusher/pusher.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/topology/mock/mock.go
Labels: pull-request, ready for review

#1189 OAS description updates
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
Labels: pull-request, ready for review

#1185 docs: fix chequebookaddress response property name
  openapi/SwarmCommon.yaml
Labels: pull-request

#1187 swap, accounting: move to bigint
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  pkg/accounting/accounting.go
  pkg/accounting/accounting_test.go
  pkg/accounting/mock/accounting.go
  pkg/debugapi/balances.go
  pkg/debugapi/balances_test.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/settlements.go
  pkg/debugapi/settlements_test.go
  pkg/node/node.go
  pkg/pricing/pb/pricing.pb.go
  pkg/pricing/pb/pricing.proto
  pkg/pricing/pricing.go
  pkg/pricing/pricing_test.go
  pkg/pushsync/pushsync_test.go
  pkg/retrieval/retrieval_test.go
  pkg/settlement/interface.go
  pkg/settlement/pseudosettle/mock/pseudosettle.go
  pkg/settlement/pseudosettle/pseudosettle.go
  pkg/settlement/pseudosettle/pseudosettle_test.go
  pkg/settlement/swap/chequebook/init.go
  pkg/settlement/swap/mock/swap.go
  pkg/settlement/swap/swap.go
  pkg/settlement/swap/swap_test.go
Labels: pull-request, ready for review

#1198 token migration
  .github/workflows/beekeeper.yml
  .github/workflows/slash-beekeeper.yml
  cmd/bee/cmd/cmd.go
  pkg/accounting/accounting.go
  pkg/bzz/address.go
  pkg/node/node.go
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/settlement/swap/addressbook.go
  pkg/settlement/swap/chequebook/cashout.go
  pkg/settlement/swap/chequebook/chequebook.go
  pkg/settlement/swap/chequebook/chequestore.go
  pkg/settlement/swap/chequebook/factory.go
  pkg/settlement/swap/chequebook/init.go
Labels: pull-request, ready for review

#1199 blocklist: fix string trim
  pkg/p2p/libp2p/internal/blocklist/blocklist.go
Labels: bug, pull-request

#1201 fix receiver encoding in bzzaar url
  pkg/settlement/swap/chequebook/init.go
Labels: pull-request, ready for review

#1202 swap: fix storage keys
  .github/workflows/beekeeper.yml
  .github/workflows/slash-beekeeper.yml
  pkg/settlement/swap/chequebook/chequebook.go
  pkg/settlement/swap/chequebook/chequestore.go
Labels: bug, pull-request, ready for review

#1203 check eth balance on initial startup and show required funds
  cmd/bee/cmd/cmd.go
  pkg/settlement/swap/chequebook/init.go
  pkg/settlement/swap/transaction/backend.go
  pkg/settlement/swap/transaction/backendmock/backend.go
Labels: pull-request, ready for review

#1205 Added instructions on how to run multiple bee nodes
  packaging/docker/README.md
  packaging/docker/docker-compose.yml
Labels: pull-request

#1193 api, feeds: wire-in feeds resolution
  cmd/internal/file/io_test.go
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/bytes.go
  pkg/api/bzz.go
  pkg/api/bzz_test.go
  pkg/api/export_test.go
  pkg/api/feed.go
  pkg/api/feed_test.go
  pkg/api/file.go
  pkg/api/router.go
  pkg/api/soc_test.go
  pkg/cac/cac.go
  pkg/cac/cac_test.go
  pkg/feeds/epochs/finder.go
  pkg/feeds/epochs/lookup_benchmark_test.go
  pkg/feeds/epochs/lookup_test.go
  pkg/feeds/epochs/updater.go
  pkg/feeds/factory/factory.go
  pkg/feeds/feed.go
  pkg/feeds/getter.go
  pkg/feeds/putter.go
  pkg/feeds/sequence/lookup_benchmark_test.go
  pkg/feeds/sequence/lookup_test.go
  pkg/feeds/sequence/sequence.go
  pkg/feeds/testing/lookup.go
  pkg/manifest/mantaray.go
  pkg/node/node.go
  pkg/storage/mock/storer.go
Labels: pull-request, ready for review

#1213 debugapi: set received / sent to 0 if no settlements
  pkg/debugapi/settlements.go
  pkg/debugapi/settlements_test.go
Labels: bug, pull-request, ready for review

#1209 openapi: lint yamls
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
Labels: pull-request, ready for review

#1217 version: bump to 0.5.0
  version.go
Labels: pull-request

#1218 version: bump to 0.5.1
  version.go
Labels: pull-request

#1220 Update docker-compose.yml
  packaging/docker/docker-compose.yml
Labels: pull-request

#1223 Include offset and limit in API specification
  openapi/Swarm.yaml
Labels: pull-request, ready for review

#1229 api: unexport api struct fields
  pkg/api/api.go
  pkg/api/bytes.go
  pkg/api/bzz.go
  pkg/api/chunk.go
  pkg/api/dirs.go
  pkg/api/feed.go
  pkg/api/file.go
  pkg/api/pin_bytes.go
  pkg/api/pin_bzz.go
  pkg/api/pin_chunks.go
  pkg/api/pin_files.go
  pkg/api/pss.go
  pkg/api/router.go
  pkg/api/soc.go
  pkg/api/tag.go
Labels: pull-request

#1219 fix payment threshold log message
  pkg/pricing/pricing.go
Labels: pull-request, ready for review

#1230 set swap-endpoint to slock.it goerli for deb, rpm and brew package
  .goreleaser.yml
  packaging/bee.yaml
  packaging/homebrew/bee.yaml
  packaging/rpm/post
Labels: pull-request

#1228 fix funding addr for both linux and mac bee-get-addr
  packaging/bee-get-addr
  packaging/homebrew/bee-get-addr
Labels: pull-request

#1152 godoc package documentation
  pkg/accounting/accounting.go
  pkg/accounting/mock/accounting.go
  pkg/api/api.go
  pkg/bitvector/bitvector.go
  pkg/bmtpool/bmtpool.go
  pkg/bzz/address.go
  pkg/content/validator.go
  pkg/debugapi/debugapi.go
  pkg/discovery/discovery.go
  pkg/encryption/encryption.go
  pkg/hive/hive.go
  pkg/intervalstore/intervals.go
  pkg/jsonhttp/jsonhttp.go
  pkg/logging/logging.go
  pkg/manifest/manifest.go
  pkg/netstore/netstore.go
  pkg/node/node.go
  pkg/p2p/p2p.go
  pkg/pingpong/pingpong.go
  pkg/pss/pss.go
  pkg/puller/puller.go
  pkg/pullsync/pullsync.go
  pkg/pusher/pusher.go
  pkg/pushsync/pushsync.go
  pkg/retrieval/retrieval.go
  pkg/sctx/sctx.go
  pkg/soc/soc.go
  pkg/statestore/doc.go
  pkg/storage/store.go
  pkg/tags/tags.go
  pkg/topology/topology.go
  pkg/traversal/traversal.go
Labels: pull-request, ready for review

#1246 api: fix bzz dereference when no updates posted
  pkg/api/bzz.go
Labels: bug, pull-request, ready for review

#1238 change print line for deb postinst, missed in previous pr
  packaging/deb/postinst
Labels: pull-request

#1253 statestore: try to recover leveldb on corrupted db
  pkg/intervalstore/store_test.go
  pkg/node/node.go
  pkg/statestore/leveldb/leveldb.go
  pkg/statestore/leveldb/leveldb_test.go
Labels: bug, pull-request, ready for review

#1255 tags: delete persisted tag
  pkg/tags/tags.go
  pkg/tags/tags_test.go
Labels: bug, pull-request, ready for review

#1265 transaction: add support for deployments
  pkg/settlement/swap/chequebook/cashout.go
  pkg/settlement/swap/chequebook/cashout_test.go
  pkg/settlement/swap/chequebook/chequebook.go
  pkg/settlement/swap/chequebook/chequebook_test.go
  pkg/settlement/swap/chequebook/factory.go
  pkg/settlement/swap/chequebook/factory_test.go
  pkg/settlement/swap/transaction/transaction.go
  pkg/settlement/swap/transaction/transaction_test.go
Labels: pull-request, ready for review

#1284 feeds: disable epochs tests
  pkg/feeds/epochs/lookup_test.go
Labels: pull-request

#1277 packaging/docker: remove quotes from compose .env file
  packaging/docker/env
Labels: pull-request

#1266 transaction: add simple nonce tracking
  pkg/crypto/mock/signer.go
  pkg/node/node.go
  pkg/settlement/swap/transaction/backend.go
  pkg/settlement/swap/transaction/transaction.go
  pkg/settlement/swap/transaction/transaction_test.go
Labels: pull-request, ready for review

#1283 fix: expose content-disposition HTTP header for CORS requests
  pkg/api/file.go
Labels: pull-request, ready for review

#1282 libp2p: always close streams
  pkg/p2p/libp2p/stream.go
Labels: clean-up, pull-request, ready for review

#1278 enable dns entry for nat-addr
  go.mod
  go.sum
  pkg/p2p/libp2p/static_resolver.go
  pkg/p2p/libp2p/static_resolver_test.go
Labels: pull-request

#1290 libp2p: add more stream cleanups
  pkg/p2p/libp2p/libp2p.go
Labels: pull-request, ready for review

#1281 Cac refactor
  pkg/api/chunk.go
  pkg/api/soc.go
  pkg/cac/cac.go
  pkg/cac/cac_test.go
  pkg/cac/export_test.go
  pkg/feeds/putter.go
  pkg/file/splitter/internal/job.go
  pkg/soc/export_test.go
  pkg/soc/soc.go
  pkg/soc/soc_test.go
  pkg/storage/testing/chunk.go
Labels: pull-request, ready for review

#1267 pipeline: hasher bug
  pkg/api/gatewaymode_test.go
  pkg/file/pipeline/hashtrie/export_test.go
  pkg/file/pipeline/hashtrie/hashtrie.go
  pkg/file/pipeline/hashtrie/hashtrie_test.go
  pkg/file/pipeline/store/store.go
  pkg/storage/mock/storer.go
Labels: bug, pull-request, ready for review

#1308 add sleep for sync check
  pkg/settlement/swap/transaction/backend.go
Labels: bug, pull-request, ready for review

#1231 check if password file already exists
  .goreleaser.yml
Labels: pull-request

#1310 chequebook: continue waiting for previous deploy transaction
  pkg/settlement/swap/chequebook/init.go
Labels: pull-request, ready for review

#1309 pullstorage: remove flaky test
  pkg/pullsync/pullstorage/pullstorage_test.go
Labels: flaky-test, pull-request, ready for review

#1256 api: dont accept two soc's with the same address
  pkg/api/soc.go
  pkg/api/soc_test.go
Labels: bug, clean-up, pull-request, ready for review

#1259 feeds: sequence feed resolution fixed and timestamp based heuristic dropped
  pkg/api/feed_test.go
  pkg/feeds/epochs/epoch.go
  pkg/feeds/epochs/lookup_benchmark_test.go
  pkg/feeds/epochs/lookup_test.go
  pkg/feeds/epochs/updater.go
  pkg/feeds/feed.go
  pkg/feeds/sequence/lookup_benchmark_test.go
  pkg/feeds/sequence/lookup_test.go
  pkg/feeds/sequence/sequence.go
  pkg/feeds/testing/lookup.go
Labels: pull-request, ready for review

#1316 openapi: remove unused field
  openapi/Swarm.yaml
Labels: pull-request, ready for review

#1315 Docker arm image support
  .github/workflows/release.yaml
  .goreleaser.yml
Labels: pull-request

#1327 fix default config values and bump version inside docker-compose.yml
  packaging/bee.yaml
  packaging/docker/README.md
  packaging/docker/docker-compose.yml
  packaging/docker/env
  packaging/homebrew/bee.yaml
Labels: pull-request

#1323 Openapi headers revised
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
Labels: pull-request

#1328 bump version.go to 0.5.2
  version.go
Labels: pull-request

#1329 accounting: copy big numbers in various places
  pkg/accounting/accounting.go
Labels: bug, pull-request, ready for review

#1336 bump clef version
  packaging/docker/docker-compose.yml
Labels: pull-request

#1334 fix brew post_install
  .goreleaser.yml
Labels: pull-request, ready for review

#1339 shed: improve leveldb configuration
  pkg/shed/db.go
Labels: pull-request

#1342 Revert "kademlia: hotfix for peer list inconsistency (#1020)"
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
Labels: pull-request, ready for review

#1338 use eip155 signing in in-memory signer
  pkg/crypto/clef/clef.go
  pkg/crypto/mock/signer.go
  pkg/crypto/signer.go
  pkg/crypto/signer_test.go
  pkg/node/node.go
  pkg/settlement/swap/transaction/transaction.go
  pkg/settlement/swap/transaction/transaction_test.go
Labels: pull-request, ready for review

#1314 Add deploy command to bee
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/deploy.go
  pkg/node/chain.go
  pkg/node/node.go
  pkg/node/statestore.go
Labels: pull-request, ready for review
