Repository ethersphere/bee, pull requests merged in 2021-11, with the labels that each got.

#2637 fix: continue on invalid stamp
  pkg/pusher/pusher.go
Labels: pull-request

#2636 fix: panic in kademlia metrics
  pkg/topology/kademlia/kademlia.go
Labels: pull-request

#2638 feat: add bee open API versions info to the health endpoint
  Makefile
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
  pkg/api/version.go
  pkg/debugapi/debugapi_test.go
  pkg/debugapi/status.go
  pkg/debugapi/status_test.go
  pkg/debugapi/version.go
Labels: pull-request

#2618 feat: show eth backend client on startup
  pkg/node/chain.go
Labels: ready for review, pull-request

#2640 fix: panic on stewardship endpoints in dev mode
  pkg/api/bzz_test.go
  pkg/api/stewardship_test.go
  pkg/node/devnode.go
  pkg/steward/mock/steward.go
Labels: pull-request

#2632 refactor(api): remove deprecated stamps endpoint
  openapi/Swarm.yaml
  pkg/api/export_test.go
  pkg/api/postage.go
  pkg/api/postage_test.go
  pkg/api/router.go
Labels: ready for review, pull-request

#2565 feat!: only consider backbone nodes for core protocols
  .github/workflows/beekeeper.yml
  Makefile
  pkg/chainsyncer/chainsyncer.go
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/export_test.go
  pkg/p2p/libp2p/internal/reacher/metrics.go
  pkg/p2p/libp2p/internal/reacher/reacher.go
  pkg/p2p/libp2p/internal/reacher/reacher_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/p2p.go
  pkg/p2p/p2p_test.go
  pkg/puller/puller.go
  pkg/pullsync/pullsync.go
  pkg/pushsync/pushsync.go
  pkg/recovery/repair_test.go
  pkg/retrieval/retrieval.go
  pkg/retrieval/retrieval_test.go
  pkg/topology/kademlia/export_test.go
  pkg/topology/kademlia/internal/metrics/metrics.go
  pkg/topology/kademlia/internal/metrics/metrics_test.go
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
  pkg/topology/kademlia/metrics.go
  pkg/topology/kademlia/mock/kademlia.go
  pkg/topology/mock/mock.go
  pkg/topology/topology.go
Labels: pull-request

#2647 chore(ver): bump v1.4.0
  version.go
Labels: pull-request

#2644 doc: remove github templates
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: pull-request

#2652 fix: add accounting endpoint role
  pkg/auth/auth.go
Labels: pull-request

#2657 ci: add postage intergration test to git workflow
  .github/workflows/beekeeper.yml
Labels: ready for review, pull-request

#2658 fix: retry push on err, drain semaphore
  .github/workflows/beekeeper.yml
  pkg/api/api.go
  pkg/pusher/pusher.go
Labels: pull-request

#2660 fix: topup role
  pkg/auth/auth.go
Labels: pull-request

#2659 fix(auth): missing roles
  pkg/auth/auth.go
Labels: pull-request

#2630 fix(puller): delete cursors on disconnect
  pkg/puller/puller.go
Labels: ready for review, pull-request

#2654 ci: trigger bee-factory builds on release
  .github/workflows/release_triggers.yaml
Labels: pull-request

#2662 fix: direct op
  pkg/api/api.go
  pkg/pusher/pusher.go
  pkg/pusher/pusher_test.go
Labels: pull-request

#2655 chore: upload and download api metrics middleware
  pkg/api/api.go
  pkg/api/export_test.go
  pkg/api/metrics.go
  pkg/api/metrics_test.go
  pkg/api/router.go
Labels: ready for review, pull-request

#2663 feat: extra linters command
  .golangci.local.yml
  Makefile
Labels: ready for review, pull-request

#2621 feat: differentiate refresh rate
  pkg/node/devnode.go
  pkg/node/node.go
  pkg/settlement/pseudosettle/pseudosettle.go
  pkg/settlement/pseudosettle/pseudosettle_test.go
Labels: ready for review, pull-request, p1

#2639 feat!: change to percentage based accounting tolerances
  .github/workflows/beekeeper.yml
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  packaging/bee.yaml
  packaging/docker/docker-compose.yml
  packaging/docker/env
  packaging/homebrew/bee.yaml
  packaging/scoop/bee.yaml
  pkg/accounting/accounting.go
  pkg/accounting/accounting_test.go
  pkg/node/node.go
Labels: ready for review, pull-request, p1

#2629 Feat: Increase number of originator retries for chunk
  pkg/pushsync/pushsync.go
Labels: ready for review, pull-request, p1

#2651 fix: checks at time based refreshment
  pkg/accounting/accounting.go
  pkg/accounting/metrics.go
  pkg/settlement/pseudosettle/pseudosettle.go
Labels: ready for review, pull-request, p1

#2650 feat: retrieval attempt persistently tried on originator
  pkg/retrieval/retrieval.go
  pkg/retrieval/skip_peers.go
Labels: ready for review, pull-request, p1

#2664 feat: make forwarder storing non-blocking
  pkg/pushsync/pushsync.go
Labels: pull-request

#2675 fix: beekeeper branch
  .github/workflows/beekeeper.yml
Labels: ready for review, pull-request, p1

#2676 chore(handshake)!: bump protocol version
  pkg/p2p/libp2p/internal/handshake/handshake.go
Labels: ready for review, pull-request

#2673 fix: check stamp before creating tag in /bytes upload
  pkg/api/bytes.go
Labels: pull-request

#2674 fix: remove unnecessary labels from pushsync metric
  pkg/pushsync/metrics.go
  pkg/pushsync/pushsync.go
Labels: pull-request

#2679 docs(openapi): major bump for bee api
  openapi/Swarm.yaml
Labels: pull-request

#2678 docs: versioning strategy note
  README.md
Labels: pull-request

#2667 fix: retry transaction receipt with delay
  pkg/transaction/backend.go
Labels: ready for review, pull-request

#2665 feat: async writes to store for netstore retrieval
  pkg/netstore/netstore.go
  pkg/netstore/netstore_test.go
  pkg/node/node.go
Labels: ready for review, pull-request

#2641 feat: sync postage stamps in batches
  .github/patches/listener.patch
  .github/workflows/beekeeper.yml
  pkg/node/node.go
  pkg/postage/listener/export_test.go
  pkg/postage/listener/listener.go
  pkg/postage/listener/listener_test.go
Labels: ready for review, pull-request

#2684 fix: cors passing user-agent
  pkg/api/router.go
  pkg/debugapi/cors.go
Labels: pull-request

#2688 fix: ignore greylist for self verification
  pkg/node/node.go
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/p2p/libp2p/internal/handshake/handshake_test.go
  pkg/p2p/libp2p/libp2p_test.go
  pkg/transaction/sender_matcher.go
  pkg/transaction/sender_matcher_test.go
Labels: ready for review, pull-request

#2695 chore(version): bump to 1.4.1
  version.go
Labels: pull-request

#2694 fix: storer node forwarder replication edge case
  pkg/pushsync/pushsync.go
Labels: pull-request

#2620 feat: direct uploads
  .github/workflows/beekeeper.yml
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/auth_test.go
  pkg/api/bytes.go
  pkg/api/bytes_test.go
  pkg/api/bzz.go
  pkg/api/bzz_test.go
  pkg/api/chunk.go
  pkg/api/chunk_stream.go
  pkg/api/chunk_stream_test.go
  pkg/api/chunk_test.go
  pkg/api/cors_test.go
  pkg/api/dirs.go
  pkg/api/dirs_test.go
  pkg/api/feed.go
  pkg/api/feed_test.go
  pkg/api/gatewaymode_test.go
  pkg/api/pin_test.go
  pkg/api/pss_test.go
  pkg/api/soc_test.go
  pkg/api/stewardship_test.go
  pkg/api/tag_test.go
  pkg/node/devnode.go
  pkg/node/node.go
  pkg/pusher/pusher.go
  pkg/pusher/pusher_test.go
Labels: ready for review, pull-request

#2697 chore(deps): update libp2p
  go.mod
  go.sum
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/export_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/protocols_test.go
Labels: ready for review, pull-request

#2700 chore(retrieval): improve metrics
  pkg/retrieval/metrics.go
  pkg/retrieval/retrieval.go
Labels: ready for review, pull-request

#2703 fix(pusher): feed channel respects warmup
  pkg/pusher/pusher.go
Labels: ready for review, pull-request

#2666 doc: style guide
  CODINGSTYLE.md
  README.md
Labels: in progress, pull-request
