Repository ethersphere/bee, pull requests merged in 2022-10, with the labels that each got.

#3355 feat(stakingAgent): storage incentives contract calls implementation
  pkg/storageincentives/redistributioncontract/export_test.go
  pkg/storageincentives/redistributioncontract/redistribution.go
  pkg/storageincentives/redistributioncontract/redistributionABI.go
  pkg/storageincentives/redistributioncontract/redistribution_test.go
Labels: ready for review, pull-request

#3357 fix: move upload store
  pkg/localstorev2/internal/internal.go
  pkg/localstorev2/internal/pinning/pinning_test.go
  pkg/localstorev2/internal/upload/export_test.go
  pkg/localstorev2/internal/upload/uploadstore.go
  pkg/localstorev2/internal/upload/uploadstore_test.go
  pkg/storagev2/inmemchunkstore/inmemchunkstore_test.go
  pkg/storagev2/storagetest/benchmark.go
  pkg/storagev2/storagetest/benchmark_test.go
Labels: pull-request

#3374 fix: race condition in soc/TestInvalid
  pkg/soc/validator_test.go
  pkg/swarm/swarm.go
  pkg/swarm/swarm_test.go
Labels: ready for review, pull-request

#3363 feat: Redistribution agent updates
  pkg/storageincentives/agent.go
  pkg/storageincentives/incentives_test.go
  pkg/topology/depthmonitor/depthmonitor.go
Labels: pull-request

#3364 chore: full nodes run the incentives agent
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/config/chain.go
  pkg/node/chain.go
  pkg/node/devnode.go
  pkg/node/node.go
  pkg/postage/listener/listener.go
  pkg/storageincentives/agent.go
  pkg/storageincentives/agent_test.go
  pkg/storageincentives/metrics.go
  pkg/storageincentives/redistribution/export_test.go
  pkg/storageincentives/redistribution/redistribution.go
  pkg/storageincentives/redistribution/redistributionABI.go
  pkg/storageincentives/redistribution/redistribution_test.go
  pkg/storageincentives/staking/contract.go
  pkg/storageincentives/staking/mock/contract.go
Labels: pull-request

#3376 chore: tweak agent test
  pkg/storageincentives/agent_test.go
Labels: pull-request

#3378 refactor(auth): interface with duration
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/auth/auth.go
  pkg/auth/auth_test.go
  pkg/auth/mock/auth.go
  pkg/node/devnode.go
  pkg/node/node.go
Labels: ready for review, pull-request

#3375 chore(lint): made tests execute in parallel (part 6)
  .golangci.yml
  pkg/chainsyncer/chainsyncer_test.go
  pkg/hive/hive_test.go
  pkg/intervalstore/intervals_test.go
  pkg/intervalstore/store_test.go
  pkg/pinning/pinning_test.go
  pkg/shed/field_struct_test.go
  pkg/shed/field_uint64_test.go
  pkg/shed/index_test.go
  pkg/shed/schema_test.go
  pkg/shed/vector_uint64_test.go
Labels: ready for review, pull-request

#3370 fix: cannot get batch after purchase
  pkg/api/postage.go
Labels: ready for review, pull-request

#3377 feat: goerli redistribution address
  pkg/config/chain.go
Labels: ready for review, pull-request

#3382 feat: decrease lower bound
  pkg/topology/depthmonitor/depthmonitor.go
Labels: ready for review, pull-request

#3385 feat: update redistribution address and abi
  pkg/config/chain.go
  pkg/crypto/crypto.go
  pkg/storageincentives/redistribution/redistributionABI.go
  pkg/storageincentives/staking/abi.go
  pkg/storageincentives/staking/contract.go
Labels: pull-request

#3391 fix: reveal phases 39 blocks long
  pkg/storageincentives/agent.go
  pkg/storageincentives/agent_test.go
Labels: pull-request

#3384 fix: preserve new overlay on db nuke
  pkg/statestore/leveldb/migration.go
Labels: pull-request

#3398 chore: temporarily disabled commitlint
  .github/workflows/go.yml
Labels: pull-request

#3392 chore: bump version
  pkg/storageincentives/agent.go
  version.go
Labels: pull-request

#3396 chore(lint): make test execute in parallel (part 8)
  .golangci.yml
  pkg/manifest/mantaray/marshal_test.go
  pkg/manifest/mantaray/node_test.go
  pkg/manifest/mantaray/persist_test.go
  pkg/manifest/mantaray/walker_test.go
  pkg/manifest/simple/manifest_test.go
  pkg/pullsync/pullstorage/pullstorage_test.go
  pkg/pullsync/pullsync_test.go
  pkg/resolver/cidv1/cidv1_test.go
  pkg/resolver/client/ens/ens_test.go
  pkg/resolver/multiresolver/config_test.go
  pkg/resolver/multiresolver/multiresolver_test.go
Labels: ready for review, pull-request

#3380 chore(lint): make test execute in parallel (part 7)
  .golangci.yml
  pkg/node/node.go
  pkg/pusher/export_test.go
  pkg/pusher/inflight.go
  pkg/pusher/pusher.go
  pkg/pusher/pusher_test.go
Labels: ready for review, pull-request

#3372 chore(lint): make test execute in parallel (part 5)
  .golangci.yml
  pkg/file/addresses/addresses_getter_test.go
  pkg/file/buffer_test.go
  pkg/file/file_test.go
  pkg/file/joiner/joiner_test.go
  pkg/file/loadsave/loadsave_test.go
  pkg/file/pipeline/bmt/bmt_test.go
  pkg/file/pipeline/builder/builder_test.go
  pkg/file/pipeline/feeder/feeder_test.go
  pkg/file/pipeline/hashtrie/hashtrie_test.go
  pkg/file/pipeline/store/store_test.go
  pkg/file/splitter/internal/job_test.go
  pkg/file/splitter/splitter_test.go
  pkg/puller/puller_test.go
Labels: ready for review, pull-request

#3404 chore: rename option
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
Labels: pull-request

#3390 fix: missing key in log line
  pkg/accounting/accounting.go
Labels: ready for review, pull-request

#3406 chore(lint): enable disabled commitlint
  .github/workflows/go.yml
  commitlint.config.js
Labels: ready for review, pull-request

#3415 feat: new redistribution contract address for Goerli
  pkg/config/chain.go
Labels: pull-request

#3407 fix: flaky test TestSendChunkAndTimeoutinReceivingReceipt
  pkg/pusher/pusher_test.go
Labels: pull-request

#3410 fix: flaky tests TestCopyBuffer and TestChunkPipe
  pkg/file/buffer_test.go
Labels: ready for review, pull-request

#3400 feat: add consensus time for sampler
  pkg/api/router.go
  pkg/localstore/sampler.go
  pkg/localstore/sampler_test.go
  pkg/storage/store.go
  pkg/storageincentives/agent.go
Labels: pull-request

#3399 feat: add consensus time to sampling
  pkg/api/rchash.go
  pkg/localstore/sampler.go
  pkg/localstore/sampler_test.go
  pkg/postage/testing/stamp.go
  pkg/storage/inmemstore/store.go
  pkg/storage/mock/storer.go
  pkg/storage/store.go
  pkg/storageincentives/agent.go
  pkg/storageincentives/agent_test.go
Labels: pull-request

#3419 feat: increase attempt count in retrieval and pushsync
  pkg/pushsync/pushsync.go
  pkg/retrieval/retrieval.go
Labels: pull-request

#3417 fix(blocker): fix flaky tests
  pkg/blocker/blocker_test.go
Labels: ready for review

#3379 chore(feeds): better parallel tests
  pkg/feeds/sequence/lookup_test.go
  pkg/feeds/testing/lookup.go
Labels: ready for review, pull-request

#3418 fix: sampler duration tracks seconds
  pkg/localstore/sampler.go
Labels: pull-request

#3367 feat: broadcast size should not be capped for newly connected neighbors
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
Labels: ready for review, pull-request

#3425 fix: increase timeout for release action and bump base docker images
  .github/workflows/release.yaml
  Dockerfile
  Dockerfile.goreleaser
  Dockerfile.scratch
Labels: pull-request

#3420 chore(lint): simplified govet rules
  .golangci.yml
Labels: ready for review, pull-request

#3360 refactor(kademlia): remove hacky config usage
  pkg/topology/kademlia/export_test.go
  pkg/topology/kademlia/internal/metrics/metrics_test.go
  pkg/topology/kademlia/internal/waitnext/waitnext_test.go
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
Labels: ready for review, pull-request

#3432 chore(topology): enabled parallel tests
  .golangci.yml
  pkg/topology/kademlia/kademlia_test.go
  pkg/topology/pslice/pslice_test.go
Labels: pull-request

#3436 chore(bmt): enable parallel tests
  .golangci.yml
  pkg/bmt/bmt_test.go
  pkg/bmt/proof_test.go
  pkg/bmt/reference/reference_test.go
Labels: pull-request

#3441 ci: trigger bee-factory only in the event latest image is being pushed
  .github/workflows/beekeeper.yml
Labels: pull-request

#3444 fix: pullsync and puller sync process to continue
  .golangci.yml
  pkg/puller/metrics.go
  pkg/puller/puller.go
  pkg/pullsync/pullsync.go
Labels: pull-request

#3345 fix: rename swap
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/deploy.go
  cmd/bee/cmd/start.go
  packaging/bee.yaml
  packaging/docker/env
  packaging/homebrew-amd64/bee.yaml
  packaging/homebrew-arm64/bee.yaml
  packaging/scoop/bee.yaml
  pkg/node/node.go
Labels: ready for review, pull-request

#3449 feat(agent):metrics for errors in agent
  pkg/storageincentives/agent.go
  pkg/storageincentives/metrics.go
Labels: pull-request

#3424 feat: migration initiation
  pkg/storagev2/migration/export_test.go
  pkg/storagev2/migration/migration.go
  pkg/storagev2/migration/migration_test.go
Labels: ready for review, pull-request

#3447 fix(localstore): remove pullIndex on caching
  pkg/localstore/gc_test.go
  pkg/localstore/mode_put.go
  pkg/localstore/mode_put_test.go
  pkg/localstore/mode_set.go
  pkg/localstore/pin_test.go
  pkg/localstore/reserve_test.go
Labels: pull-request

#3458 fix: flaky unit tests
  pkg/puller/puller_test.go
  pkg/topology/kademlia/kademlia_test.go
Labels: pull-request

#3421 feat(migration): store migration helpers
  pkg/storagev2/migration/export_test.go
  pkg/storagev2/migration/index.go
  pkg/storagev2/migration/index_test.go
  pkg/storagev2/migration/migration.go
  pkg/storagev2/migration/migration_test.go
  pkg/storagev2/migration/steps_chain.go
  pkg/storagev2/migration/steps_chain_test.go
Labels: pull-request

#3457 fix: redirect loop
  pkg/api/bzz.go
  pkg/api/bzz_test.go
Labels: pull-request

#3459 chore: cleanup of unnecessary address at bin function
  pkg/localstore/reserve.go
  pkg/localstore/sampler.go
Labels: pull-request

#3461 fix(depthmonitor): increased depth wait timeout
  pkg/topology/depthmonitor/depthmonitor_test.go
Labels: ready for review, pull-request

#3456 chore(pullsync): cancel ruid cleanup
  pkg/puller/puller.go
  pkg/pullsync/mock/pullsync.go
  pkg/pullsync/pb/pullsync.pb.go
  pkg/pullsync/pb/pullsync.proto
  pkg/pullsync/pullsync.go
  pkg/pullsync/pullsync_test.go
Labels: pull-request

#3430 feat: stamp validity check upon sample insert
  pkg/api/rchash.go
  pkg/localstore/localstore.go
  pkg/localstore/localstore_test.go
  pkg/localstore/sampler.go
  pkg/localstore/sampler_test.go
  pkg/node/node.go
  pkg/storage/testing/chunk.go
Labels: ready for review, pull-request

#3452 feat: increase reveal price
  pkg/storageincentives/redistribution/redistribution.go
  pkg/storageincentives/redistribution/redistribution_test.go
  pkg/transaction/mock/transaction.go
  pkg/transaction/transaction.go
  pkg/transaction/transaction_test.go
Labels: pull-request

#3460 feat: new redistribution address
  pkg/config/chain.go
  pkg/storageincentives/agent.go
Labels: pull-request

#3470 fix: redistribution tests
  pkg/storageincentives/redistribution/redistribution_test.go
  pkg/transaction/mock/transaction.go
Labels: pull-request

#3473 fix(depthmonitor): unit tests
  pkg/topology/depthmonitor/depthmonitor_test.go
  pkg/topology/depthmonitor/export_test.go
Labels: pull-request

#3475 fix(pullsync): eof flaky test
  pkg/p2p/streamtest/export_test.go
  pkg/p2p/streamtest/streamtest.go
  pkg/p2p/streamtest/streamtest_test.go
  pkg/pullsync/pullsync.go
Labels: ready for review, pull-request

#3471 chore: sampler logs fix and agent timer limit helper func
  pkg/localstore/sampler.go
  pkg/storageincentives/agent.go
Labels: pull-request
