Repository ethersphere/bee, pull requests merged in 2022-05, with the labels that each got.

#2922 chore(chainsyncer): reinstate 24h blocking
  pkg/chainsyncer/chainsyncer.go
Labels: ready for review, pull-request

#2923 chore: update stale bot configuration
  .github/workflows/stale.yaml
Labels: pull-request

#2924 feat(cmd): add db indices command
  cmd/bee/cmd/db.go
  pkg/localstore/localstore.go
Labels: ready for review, pull-request

#2921 fix: improper error formatting
  pkg/accounting/accounting.go
  pkg/api/chunk_stream.go
  pkg/api/dirs.go
  pkg/api/pss_test.go
  pkg/api/tag.go
  pkg/bigint/bigint_test.go
  pkg/bitvector/bitvector_test.go
  pkg/debugapi/chequebook.go
  pkg/debugapi/transaction.go
  pkg/debugapi/welcome_message.go
  pkg/feeds/getter.go
  pkg/flipflop/falling_edge_test.go
  pkg/localstore/localstore.go
  pkg/localstore/migration_test.go
  pkg/netstore/netstore_test.go
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/pullsync/pullsync.go
  pkg/settlement/swap/chequebook/init.go
  pkg/statestore/leveldb/migration_test.go
  pkg/topology/pslice/pslice_test.go
Labels: pull-request

#2914 fix: postage service initialization bug
  pkg/postage/service.go
  pkg/postage/service_test.go
Labels: ready for review, pull-request

#2928 fix(pushsync): replace standard logger with trace logger
  pkg/pushsync/pushsync.go
Labels: pull-request

#2929 fix: add ignore radius flag
  pkg/node/node.go
  pkg/topology/kademlia/kademlia.go
Labels: pull-request

#2932 fix: sharky read deadlock on context cancelled
  pkg/sharky/shard.go
  pkg/sharky/shard_slots_test.go
  pkg/sharky/store.go
Labels: ready for review, pull-request

#2945 fix: devmode postage amount bug
  pkg/node/devnode.go
Labels: pull-request

#2948 fix(sharky): emit error on context cancelation
  pkg/sharky/shard.go
  pkg/sharky/store.go
Labels: bug, ready for review, pull-request

#2949 fix: devmode batch ttl wrong response
  pkg/debugapi/postage.go
  pkg/node/devnode.go
Labels: pull-request

#2953 fix(sharky): remove next slot allocation optimization
  pkg/sharky/slots.go
Labels: ready for review, pull-request

#2954 chore: bump v1.6.1
  version.go
Labels: pull-request

#2944 fix: shutdown deadlock
  cmd/bee/cmd/start.go
  cmd/bee/cmd/start_dev.go
  pkg/hive/hive.go
  pkg/node/bootstrap.go
  pkg/node/devnode.go
  pkg/node/node.go
  pkg/p2p/libp2p/libp2p.go
  pkg/postage/listener/listener.go
  pkg/postage/listener/listener_test.go
  pkg/topology/kademlia/kademlia.go
Labels: ready for review, pull-request

#2947 feat: set default admin password in restricted dev
  cmd/bee/cmd/start_dev.go
Labels: ready for review, pull-request

#2951 fix: allow nested paths for multipart upload
  pkg/api/dirs.go
  pkg/api/dirs_test.go
Labels: pull-request

#2952 feat(bmt): segment inclusion Merkle proofs
  pkg/bmt/proof.go
  pkg/bmt/proof_test.go
Labels: ready for review, pull-request

#2968 fix: NPE on shutdown
  pkg/node/node.go
Labels: pull-request

#2967 chore: update package post install messages
  .goreleaser.yml
  packaging/bee-get-addr
  packaging/deb/postinst
  packaging/homebrew-amd64/bee-get-addr
  packaging/homebrew-arm64/bee-get-addr
  packaging/rpm/post
Labels: pull-request

#2979 fix(pullsync): create a new context on cancel ruid
  pkg/puller/puller.go
Labels: pull-request

#2966 feat: accounting metrics
  pkg/accounting/accounting.go
  pkg/accounting/metrics.go
  pkg/settlement/pseudosettle/pseudosettle.go
Labels: pull-request

#2984 chore(batchstore): commitment metric
  pkg/postage/batchstore/metrics.go
  pkg/postage/batchstore/reserve.go
Labels: ready for review, pull-request

#2976 fix(kademlia): check if peer is blocklisted before connection
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/mock/mock.go
  pkg/p2p/p2p.go
  pkg/topology/kademlia/kademlia.go
Labels: ready for review, pull-request

#2981 fix: reduce logging during bootstrapping
  pkg/node/node.go
Labels: pull-request

#2970 feat(api): subdomain support
  go.mod
  pkg/api/api_test.go
  pkg/api/bzz.go
  pkg/api/router.go
  pkg/api/subdomain.go
  pkg/api/subdomain_test.go
  pkg/logging/httpaccess/http_access.go
  pkg/node/node.go
  pkg/resolver/cidv1/cidv1.go
  pkg/resolver/cidv1/cidv1_test.go
  pkg/resolver/multiresolver/multiresolver.go
Labels: ready for review, pull-request

#2987 fix: replace PAT with GITHUB_TOKEN for ghcr.io login
  .github/workflows/beekeeper.yml
Labels: pull-request

#2971 fix(kademlia): increase bit suffix length to improve bin population
  pkg/topology/kademlia/export_test.go
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
Labels: ready for review, pull-request
