Repository ethersphere/bee, pull requests merged in 2022-01, with the labels that each got.

#2746 fix: remove subdirectories, not root path for migration command
  cmd/bee/cmd/db.go
Labels: ready for review, pull-request

#2748 ci: disable codecov comments
  codecov.yml
Labels: ready for review, pull-request

#2708 refactor: sharky free slot handling and recovery support
  pkg/sharky/recovery.go
  pkg/sharky/recovery_test.go
  pkg/sharky/shard.go
  pkg/sharky/shards.go
  pkg/sharky/sharky_test.go
  pkg/sharky/slots.go
  pkg/sharky/store.go
Labels: ready for review, builds on open pr, pull-request

#2747 fix(statestore): dont share iterator slice
  pkg/statestore/leveldb/leveldb.go
Labels: ready for review, pull-request

#2750 chore(localstore): add reserve size to debug
  pkg/localstore/localstore.go
Labels: ready for review, pull-request

#2753 test(localstore): add write-in-place test
  pkg/localstore/mode_put_test.go
Labels: ready for review, pull-request

#2751 fix: remove old overlay delete
  pkg/node/statestore.go
Labels: ready for review, pull-request

#2755 docs: functional auth openapi spec
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
Labels: ready for review, pull-request

#2756 chore(localstore): decrease debug logging for pull subs
  pkg/localstore/subscription_pull.go
Labels: ready for review, pull-request

#2757 fix: notifier setter race condition
  pkg/node/node.go
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/libp2p_test.go
Labels: ready for review, pull-request

#2752 feat: sharky DRP
  pkg/localstore/disaster_recovery.go
  pkg/localstore/disaster_recovery_test.go
  pkg/localstore/localstore.go
  pkg/localstore/migration.go
  pkg/localstore/migration_sharky.go
  pkg/localstore/schema.go
  pkg/shed/db.go
Labels: ready for review, pull-request

#2759 feat: add basic metrics for sharky
  pkg/sharky/metrics.go
  pkg/sharky/store.go
Labels: ready for review, pull-request

#2769 docs(styleguide): don't use fail as test keyword
  CODINGSTYLE.md
  pkg/accounting/accounting_test.go
  pkg/postage/batchservice/batchservice_test.go
  pkg/pushsync/pushsync_test.go
Labels: ready for review, pull-request

#2767 feat(postage): network commitment
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
  pkg/debugapi/export_test.go
  pkg/debugapi/postage.go
  pkg/debugapi/postage_test.go
  pkg/debugapi/router.go
  pkg/postage/batchstore/mock/store.go
  pkg/postage/batchstore/store.go
  pkg/postage/batchstore/store_test.go
  pkg/postage/interface.go
Labels: ready for review, pull-request

#2775 chore(deps): update libp2p
  go.mod
  go.sum
Labels: ready for review, pull-request

#2774 fix(kademlia): no once on reachability
  pkg/topology/kademlia/kademlia.go
Labels: ready for review, pull-request

#2772 feat: increase minimum neighborhood size
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
Labels: pull-request

#2779 fix: gc over collecting
  pkg/localstore/gc.go
  pkg/localstore/gc_test.go
Labels: ready for review, pull-request

#2735 fix(localstore): corrupt reserve size
  pkg/localstore/gc.go
  pkg/localstore/localstore_test.go
  pkg/localstore/mode_put.go
  pkg/localstore/mode_set.go
  pkg/localstore/reserve.go
  pkg/localstore/reserve_test.go
Labels: ready for review, pull-request
