Repository ethersphere/bee, pull requests merged in 2022-09, with the labels that each got.

#3239 refactor: cleanups
  pkg/storagev2/chunkstore.go
  pkg/storagev2/inmemchunkstore/inmemchunkstore.go
  pkg/storagev2/inmemchunkstore/inmemchunkstore_test.go
  pkg/storagev2/inmemstore/inmemstore.go
  pkg/storagev2/inmemstore/inmemstore_test.go
  pkg/storagev2/leveldbstore/store.go
  pkg/storagev2/leveldbstore/store_test.go
  pkg/storagev2/storage.go
  pkg/storagev2/storagetest/chunkstore.go
  pkg/storagev2/storagetest/storage.go
Labels: pull-request

#3238 fix: handle mantaray malformed manifest contents
  pkg/manifest/mantaray/marshal.go
  pkg/manifest/mantaray/marshal_test.go
Labels: pull-request

#3222 chore: add contributing guide
  CONTRIBUTING.md
Labels: pull-request

#3247 fix(localstore): out of memory issue during unreserve
  pkg/localstore/reserve.go
  pkg/localstore/reserve_test.go
  pkg/postage/testing/stamp.go
Labels: ready for review, pull-request

#3245 chore(mantaray): add test case name
  pkg/manifest/mantaray/marshal_test.go
Labels: pull-request

#3237 feat: localstore benchmarks
  pkg/storagev2/inmemchunkstore/inmemchunkstore_test.go
  pkg/storagev2/inmemstore/inmemstore_test.go
  pkg/storagev2/leveldbstore/store_test.go
  pkg/storagev2/storagetest/benchmark.go
  pkg/storagev2/storagetest/chunkstore.go
  pkg/storagev2/storagetest/storage.go
Labels: in progress, pull-request

#3257 fix: statestore migration schema update
  pkg/statestore/leveldb/migration.go
  version.go
Labels: pull-request

#3261 fix: make chain-backend available before technical debug is mounted
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/node/devnode.go
  pkg/node/node.go
Labels: pull-request

#3253 fix: interrupt mining
  cmd/bee/cmd/start.go
  pkg/node/node.go
Labels: ready for review, pull-request

#3259 fix: documentation for required header param in bytes and soc
  openapi/Swarm.yaml
Labels: pull-request

#3264 chore: add depthmonitor guard rail post release testing
  pkg/topology/depthmonitor/depthmonitor.go
Labels: pull-request

#3271 fix: make wallet endpoint avaiable only when swap-enabled is set to true
  pkg/api/router.go
Labels: ready for review, pull-request

#3269 fix: set stamps expiration field after batch sync completes
  pkg/node/node.go
  pkg/postage/interface.go
  pkg/postage/mock/service.go
  pkg/postage/service.go
Labels: pull-request

#3270 feat: tests for benchmarking code
  pkg/storagev2/inmemchunkstore/inmemchunkstore_test.go
  pkg/storagev2/inmemstore/inmemstore_test.go
  pkg/storagev2/leveldbstore/store_test.go
  pkg/storagev2/storagetest/benchmark.go
  pkg/storagev2/storagetest/benchmark_test.go
  pkg/storagev2/storagetest/storage.go
Labels: pull-request

#3248 feat(api): expose readiness and health endpoints
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/health.go
  pkg/api/health_test.go
  pkg/api/probe.go
  pkg/api/readiness.go
  pkg/api/readiness_test.go
  pkg/api/router.go
  pkg/node/devnode.go
  pkg/node/node.go
Labels: ready for review, pull-request

#3244 docs: add Open API spec question checkbox to the PR template
  .github/pull_request_template.md
Labels: ready for review, pull-request

#3284 feat(lint): enable goheader
  .golangci.yml
  cmd/bee/cmd/timebomb.go
  pkg/accounting/export_test.go
  pkg/api/tag_debug.go
  pkg/config/chain.go
  pkg/localstore/migration.go
  pkg/localstore/migration_test.go
  pkg/localstore/mode_get_multi.go
  pkg/localstore/schema.go
  pkg/statestore/leveldb/migration.go
  pkg/statestore/leveldb/migration_test.go
Labels: ready for review, pull-request

#3236 feat: add pinning store
  pkg/localstorev2/internal/pinning/export_test.go
  pkg/localstorev2/internal/pinning/pinning.go
  pkg/localstorev2/internal/pinning/pinning_test.go
  pkg/localstorev2/localstore.go
Labels: pull-request

#3274 fix: sharky release leak when context is canceled
  pkg/localstore/mode_put.go
Labels: ready for review

#3281 feat(lint): add all rules that are currently compliant with the code
  .github/workflows/go.yml
  .golangci.yml
  Makefile
Labels: ready for review, pull-request

#3289 fix: set stamp expiration to false if batch exists
  pkg/postage/mock/service.go
  pkg/postage/service.go
  pkg/postage/stampissuer.go
Labels: ready for review, pull-request

#3295 chore: bump api version
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
Labels: pull-request

#3294 chore: add missing file header
  pkg/cac/cac.go
  pkg/cac/cac_test.go
  pkg/storage/mock/storer_test.go
  pkg/transaction/backend_test.go
Labels: pull-request

#3292 fix: log messages with a missing or extra key
  pkg/p2p/libp2p/libp2p.go
  pkg/settlement/swap/swapprotocol/swapprotocol.go
Labels: pull-request

#3304 feat(lint): enable goconst
  .golangci.yml
  pkg/api/api.go
  pkg/api/bytes.go
  pkg/api/bzz.go
  pkg/api/chunk.go
  pkg/api/chunk_stream.go
  pkg/api/dirs.go
  pkg/api/feed.go
  pkg/api/router.go
  pkg/api/soc.go
  pkg/storage/store.go
Labels: ready for review, pull-request

#3305 feat(lint): enable wastedassign
  .golangci.yml
  cmd/bee/cmd/deploy.go
  pkg/file/pipeline/feeder/feeder.go
  pkg/localstore/mode_set.go
  pkg/log/formatter.go
  pkg/log/formatter_test.go
Labels: ready for review, pull-request

#3298 feat(lint): enable prealloc
  .golangci.yml
  pkg/api/api.go
  pkg/api/transaction.go
  pkg/hive/hive_test.go
  pkg/node/node.go
  pkg/p2p/protobuf/protobuf_test.go
  pkg/pingpong/pingpong_test.go
  pkg/resolver/multiresolver/config.go
  pkg/retrieval/retrieval_test.go
Labels: ready for review, pull-request

#3297 feat(lint): enable exportloopref
  .golangci.yml
  pkg/pullsync/pullstorage/pullstorage_test.go
Labels: ready for review, pull-request

#3299 feat(lint): enable noctx
  .golangci.yml
  pkg/api/api_test.go
  pkg/api/cors_test.go
Labels: ready for review, pull-request

#3296 feat(lint): enable errname
  .golangci.yml
  pkg/file/loadsave/export_test.go
  pkg/file/loadsave/loadsave.go
  pkg/file/loadsave/loadsave_test.go
  pkg/log/formatter_test.go
Labels: ready for review, pull-request

#3301 feat(lint): enable forbidigo
  .golangci.yml
Labels: ready for review, pull-request

#3310 feat(lint): enable errorlint
  .golangci.yml
  pkg/addressbook/addressbook.go
  pkg/addressbook/addressbook_test.go
  pkg/api/chequebook.go
  pkg/api/chunk_stream_test.go
  pkg/api/dirs.go
  pkg/bitvector/bitvector_test.go
  pkg/encryption/mock/mock_test.go
  pkg/file/buffer_test.go
  pkg/file/file_test.go
  pkg/file/joiner/joiner.go
  pkg/file/joiner/joiner_test.go
  pkg/file/pipeline/builder/builder.go
  pkg/file/splitter/splitter.go
  pkg/hive/hive.go
  pkg/intervalstore/store_test.go
  pkg/jsonhttp/jsonhttptest/jsonhttptest_test.go
  pkg/localstore/export.go
  pkg/localstore/subscription_pull.go
  pkg/log/logger.go
  pkg/node/devnode.go
  pkg/node/node.go
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/internal/blocklist/blocklist.go
  pkg/p2p/libp2p/internal/breaker/breaker_test.go
  pkg/p2p/libp2p/internal/handshake/handshake_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/stream.go
  pkg/p2p/libp2p/welcome_message_test.go
  pkg/p2p/protobuf/protobuf.go
  pkg/p2p/protobuf/protobuf_test.go
  pkg/p2p/streamtest/streamtest.go
  pkg/p2p/streamtest/streamtest_test.go
  pkg/pingpong/pingpong.go
  pkg/postage/service_test.go
  pkg/pricing/pricing_test.go
  pkg/puller/puller.go
  pkg/retrieval/retrieval_test.go
  pkg/settlement/swap/addressbook.go
  pkg/settlement/swap/chequebook/chequebook.go
  pkg/settlement/swap/chequebook/chequestore.go
  pkg/settlement/swap/chequebook/init.go
  pkg/settlement/swap/swap.go
  pkg/shed/field_struct_test.go
  pkg/statestore/leveldb/migration_test.go
  pkg/storage/inmemstore/store_test.go
  pkg/storage/mock/storer_test.go
  pkg/topology/kademlia/kademlia_test.go
  pkg/util/ioutil/ioutil_test.go
Labels: ready for review, pull-request

#3308 feat(lint): enable dogsled
  .golangci.yml
  pkg/pricer/headerutils/utilities_test.go
Labels: ready for review, pull-request

#3279 feat: localstore batching
  pkg/storagev2/batch.go
  pkg/storagev2/inmemstore/inmembatch.go
  pkg/storagev2/inmemstore/inmemstore.go
  pkg/storagev2/inmemstore/inmemstore_test.go
  pkg/storagev2/leveldbstore/batch.go
  pkg/storagev2/leveldbstore/store.go
  pkg/storagev2/leveldbstore/store_test.go
  pkg/storagev2/storage.go
  pkg/storagev2/storagetest/batch.go
  pkg/storagev2/storagetest/benchmark.go
  pkg/storagev2/storagetest/storage.go
Labels: ready for review, pull-request

#3318 feat(lint): enable durationcheck
  .golangci.yml
Labels: ready for review, pull-request

#3317 feat(lint): enable govet linters
  .golangci.yml
  pkg/postage/batchstore/store.go
  pkg/resolver/cidv1/cidv1.go
Labels: ready for review, pull-request

#3280 feat(lint): use single linting rules
  .github/workflows/go.yml
  .golangci.local.yml
  .golangci.style.yml
  Makefile
Labels: ready for review, pull-request

#3230 fix: appreciate gas price set by user
  pkg/settlement/swap/chequebook/init.go
Labels: ready for review, pull-request

#3322 fix: reserve size to return chunks with po greater than and equal to storage radius
  pkg/localstore/reserve.go
  pkg/localstore/reserve_test.go
  pkg/topology/depthmonitor/depthmonitor.go
  pkg/topology/depthmonitor/depthmonitor_test.go
Labels: ready for review, pull-request

#3327 refactor(libp2p): make the headers read/write timeout an option
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/export_test.go
  pkg/p2p/libp2p/headers.go
  pkg/p2p/libp2p/libp2p.go
Labels: ready for review, pull-request

#3250 feat: add upload store
  pkg/storagev2/chunkstore.go
  pkg/storagev2/internal/internal.go
  pkg/storagev2/internal/upload/export_test.go
  pkg/storagev2/internal/upload/uploadstore.go
  pkg/storagev2/internal/upload/uploadstore_test.go
  pkg/storagev2/leveldbstore/store.go
Labels: ready for review, pull-request

#3328 refactor(depthmonitor): pass the wakeup interval for manage method
  pkg/node/node.go
  pkg/topology/depthmonitor/depthmonitor.go
  pkg/topology/depthmonitor/depthmonitor_test.go
  pkg/topology/depthmonitor/export_test.go
Labels: ready for review, pull-request

#3336 chore: bump version to 1.8.3
  version.go
Labels: ready for review, pull-request

#3229 fix: response for slash in website index document
  pkg/api/bzz.go
  pkg/api/bzz_test.go
Labels: pull-request

#3334 feat(lint): enable tparallel
  .golangci.yml
Labels: ready for review, pull-request

#3306 feat(lint): enable predeclared
  .golangci.yml
  pkg/log/logger.go
  pkg/log/registry.go
  pkg/topology/kademlia/internal/metrics/metrics.go
Labels: ready for review, pull-request

#3333 chore(lint): version bump
  .golangci.yml
  Makefile
  pkg/accounting/mock/accounting.go
  pkg/api/stewardship.go
  pkg/bigint/bigint.go
  pkg/cac/cac_test.go
  pkg/feeds/epochs/finder.go
  pkg/feeds/getter.go
  pkg/feeds/sequence/sequence.go
  pkg/file/pipeline/builder/builder_test.go
  pkg/file/pipeline/doc.go
  pkg/file/pipeline/hashtrie/hashtrie.go
  pkg/file/splitter/internal/job.go
  pkg/jsonhttp/jsonhttptest/jsonhttptest.go
  pkg/localstore/doc.go
  pkg/localstore/mode_put.go
  pkg/localstore/mode_set.go
  pkg/localstore/subscription_pull_test.go
  pkg/log/formatter_test.go
  pkg/pushsync/pushsync_test.go
  pkg/swarm/distance.go
  pkg/topology/kademlia/doc.go
Labels: ready for review, pull-request

#3330 refactor: batchedstore tests and bench cleanup
  pkg/storagev2/batch.go
  pkg/storagev2/inmemstore/inmemstore_test.go
  pkg/storagev2/leveldbstore/store_test.go
  pkg/storagev2/storage.go
  pkg/storagev2/storagetest/batch.go
  pkg/storagev2/storagetest/benchmark.go
  pkg/storagev2/storagetest/benchmark_test.go
  pkg/storagev2/storagetest/storage.go
Labels: pull-request

#3329 style(kademlia/metrics): fix copied method comment
  pkg/topology/kademlia/internal/metrics/metrics.go
Labels: pull-request

#3348 fix: depth monitor default wakeup interval
  pkg/topology/depthmonitor/depthmonitor.go
Labels: pull-request

#3307 feat(lint): enable gochecknoinits
  .golangci.yml
  cmd/bee/cmd/cmd.go
  pkg/api/api_test.go
  pkg/bmtpool/bmtpool.go
  pkg/encryption/encryption_test.go
  pkg/file/pipeline/encryption/encryption_test.go
  pkg/file/pipeline/hashtrie/hashtrie_test.go
  pkg/file/span.go
  pkg/localstore/localstore.go
  pkg/localstore/localstore_test.go
  pkg/manifest/mantaray/marshal.go
  pkg/manifest/mantaray/marshal_test.go
  pkg/manifest/mantaray/node.go
  pkg/p2p/libp2p/libp2p.go
  pkg/pullsync/pullsync_test.go
  pkg/storage/testing/chunk.go
  pkg/topology/kademlia/kademlia_test.go
Labels: ready for review, pull-request

#3335 feat: reserve commitment sampler
  pkg/api/rchash.go
  pkg/api/router.go
  pkg/localstore/sampler.go
  pkg/localstore/sampler_test.go
  pkg/storage/inmemstore/store.go
  pkg/storage/mock/storer.go
  pkg/storage/store.go
Labels: ready for review, pull-request

#3349 fix: disabled parallel tests in TestPssSend
  pkg/api/pss_test.go
Labels: ready for review, pull-request

#3350 chore(lint): make test to execute in parallel (part #4)
  .golangci.yml
  pkg/auth/auth_test.go
  pkg/encryption/elgamal/encryption_test.go
  pkg/encryption/encryption_test.go
  pkg/encryption/mock/mock_test.go
  pkg/flipflop/falling_edge_test.go
  pkg/retrieval/retrieval_test.go
  pkg/storage/testing/chunk.go
Labels: ready for review, pull-request

#3353 docs: remove Open API spec question checkbox from the PR template
  .github/pull_request_template.md
Labels: pull-request

#3354 docs: add Open API spec section to the PR template
  .github/pull_request_template.md
Labels: pull-request

#3315 feat(localstorev2): add chunkstore
  pkg/localstorev2/internal/chunkstore/chunkstore.go
  pkg/localstorev2/internal/chunkstore/chunkstore_test.go
  pkg/localstorev2/internal/chunkstore/export_test.go
  pkg/postage/stamp.go
  pkg/storagev2/storagetest/storage.go
Labels: pull-request

#3351 refactor: improve api pss test execution time
  pkg/api/pss_test.go
Labels: ready for review, pull-request

#3358 chore: incentives feature flag
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/start.go
  pkg/node/node.go
Labels: ready for review, pull-request

#3362 refactor(depthmonitor): avoid configuration using global vars
  pkg/topology/depthmonitor/depthmonitor.go
  pkg/topology/depthmonitor/depthmonitor_test.go
  pkg/topology/depthmonitor/export_test.go
Labels: ready for review, pull-request

#3341 feat(stakingAgent): implemented api and contract comm for staking
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/export_test.go
  pkg/api/router.go
  pkg/api/staking.go
  pkg/api/staking_test.go
  pkg/config/chain.go
  pkg/node/devnode.go
  pkg/node/node.go
  pkg/staking/stakingcontract/contract.go
  pkg/staking/stakingcontract/mock/contract.go
Labels: ready for review, pull-request

#3347 feat: storage incentives agent
  pkg/storageincentives/agent.go
  pkg/storageincentives/events.go
  pkg/storageincentives/events_test.go
  pkg/storageincentives/export_test.go
  pkg/storageincentives/incentives_test.go
  pkg/topology/depthmonitor/depthmonitor.go
Labels: pull-request
