Repository ethersphere/bee, pull requests merged in 2022-11, with the labels that each got.

#3480 fix: TestReplicateBeforeReceipt flaky test
  pkg/pushsync/pushsync_test.go
Labels: ready for review, pull-request

#3474 fix: stream related metrics
  pkg/p2p/libp2p/connections_test.go
  pkg/p2p/libp2p/export_test.go
  pkg/p2p/libp2p/libp2p.go
  pkg/p2p/libp2p/metrics.go
  pkg/p2p/libp2p/stream.go
  pkg/postage/batchservice/batchservice.go
Labels: ready for review, pull-request

#3481 chore(lint): pushsync parallel tests
  .golangci.yml
  pkg/pushsync/pushsync_test.go
Labels: ready for review, pull-request

#3489 feat: initial deposit zero
  cmd/bee/cmd/cmd.go
  packaging/bee.yaml
  packaging/homebrew-amd64/bee.yaml
  packaging/homebrew-arm64/bee.yaml
  packaging/scoop/bee.yaml
Labels: ready for review, pull-request

#3466 fix(api): direct upload
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/bytes.go
  pkg/api/bytes_test.go
  pkg/api/bzz.go
  pkg/api/bzz_test.go
  pkg/api/chunk.go
  pkg/api/chunk_test.go
  pkg/api/export_test.go
  pkg/api/feed.go
  pkg/api/feed_test.go
  pkg/node/devnode.go
Labels: ready for review, pull-request

#3487 chore: log sharky recovery
  pkg/localstore/localstore.go
Labels: pull-request

#3491 fix: sampler log regression
  pkg/localstore/sampler.go
Labels: pull-request

#3497 chore: boost all agent calls
  pkg/postage/postagecontract/contract.go
  pkg/postage/postagecontract/contract_test.go
  pkg/settlement/swap/chequebook/cashout.go
  pkg/settlement/swap/chequebook/chequebook.go
  pkg/settlement/swap/chequebook/factory.go
  pkg/settlement/swap/erc20/erc20.go
  pkg/storageincentives/redistribution/redistribution.go
  pkg/storageincentives/redistribution/redistribution_test.go
  pkg/storageincentives/staking/contract.go
  pkg/storageincentives/staking/contract_test.go
  pkg/transaction/mock/transaction.go
  pkg/transaction/transaction.go
  pkg/transaction/transaction_test.go
Labels: pull-request

#3495 chore: remove unnesesery sleep
  pkg/hive/hive.go
  pkg/p2p/libp2p/libp2p.go
  pkg/postage/listener/listener_test.go
  pkg/pricing/pricing.go
  pkg/retrieval/retrieval.go
  pkg/settlement/pseudosettle/pseudosettle.go
Labels: ready for review, pull-request

#3501 fix(puller): missing po assignment in new sync peer
  pkg/puller/puller.go
  pkg/puller/puller_test.go
Labels: pull-request

#3496 chore: adjust gas limits
  pkg/postage/postagecontract/contract.go
  pkg/settlement/swap/chequebook/cashout.go
  pkg/storageincentives/redistribution/redistribution.go
Labels: pull-request

#3506 fix: cancel and resend to use new gas price
  pkg/transaction/transaction.go
  pkg/transaction/transaction_test.go
Labels: pull-request

#3508 fix(puller): flaky tests
  pkg/puller/puller_test.go
Labels: pull-request

#3507 chore(agent): renable test
  pkg/storageincentives/agent_test.go
Labels: pull-request

#3510 chore: compact chain config
  pkg/config/chain.go
Labels: pull-request

#3512 fix: agent unit test
  pkg/storageincentives/agent_test.go
Labels: pull-request

#3467 refactor: keyval pairs for logger in accounting
  pkg/accounting/accounting.go
Labels: pull-request

#3513 chore: account disconnect reason for blocklistig
  pkg/accounting/accounting.go
  pkg/accounting/accounting_test.go
Labels: pull-request

#3477 feat: add commit round argument
  pkg/config/chain.go
  pkg/storageincentives/agent.go
  pkg/storageincentives/agent_test.go
  pkg/storageincentives/redistribution/redistribution.go
  pkg/storageincentives/redistribution/redistributionABI.go
  pkg/storageincentives/redistribution/redistribution_test.go
Labels: pull-request

#3509 fix(sampler, redist): varius adjustment for the storage incentives
  pkg/localstore/sampler.go
  pkg/storageincentives/redistribution/redistribution.go
Labels: pull-request

#3515 fix(puller): increment from value on successful sync only and sleep only on connection error
  pkg/node/node.go
  pkg/puller/puller.go
  pkg/pullsync/pullsync.go
Labels: pull-request

#3511 feat: removed hardcoded chain ids
  cmd/bee/cmd/start.go
  pkg/api/api_test.go
  pkg/api/wallet_test.go
  pkg/config/chain.go
  pkg/settlement/swap/chequebook/init.go
Labels: ready for review, pull-request

#3517 docs: move staking endpoint to debug api
  openapi/Swarm.yaml
  openapi/SwarmDebug.yaml
Labels: pull-request

#3518 chore: more logs to pullsync and pullstorage
  pkg/node/node.go
  pkg/pullsync/pullstorage/pullstorage.go
  pkg/pullsync/pullstorage/pullstorage_test.go
  pkg/pullsync/pullsync.go
Labels: pull-request

#3521 fix: serialise amount into string
  pkg/api/staking.go
  pkg/api/staking_test.go
Labels: pull-request

#3525 fix: disable beekeeper gc test
  .github/workflows/beekeeper.yml
Labels: pull-request

#3523 feat: stamps expiry loop
  .github/workflows/beekeeper.yml
  pkg/node/node.go
  pkg/postage/postagecontract/contract.go
  pkg/postage/postagecontract/contract_test.go
  pkg/postage/postagecontract/mock/contract.go
  pkg/postage/postagecontract/postageContractAbi.go
  pkg/storageincentives/agent.go
  pkg/storageincentives/agent_test.go
Labels: pull-request

#3537 chore: rename swap oracle to avoid confusion
  pkg/config/chain.go
  pkg/node/chain.go
  pkg/node/node.go
Labels: pull-request

#3502 refactor: transactions
  openapi/SwarmCommon.yaml
  pkg/api/transaction.go
  pkg/api/transaction_test.go
  pkg/node/devnode.go
  pkg/transaction/transaction.go
Labels: pull-request

#3540 chore: update goerli smart contracts addresses and abis
  pkg/config/chain.go
  pkg/postage/postagecontract/abi.go
  pkg/postage/postagecontract/postageContractAbi.go
  pkg/storageincentives/redistribution/abi.go
  pkg/storageincentives/staking/abi.go
Labels: pull-request

#3544 fix: goerli postage stamp start block number
  pkg/config/chain.go
Labels: pull-request

#3554 fix: use the correct hash
  pkg/api/transaction.go
Labels: pull-request

#3558 fix: increase reveal gas limit
  pkg/storageincentives/redistribution/redistribution.go
Labels: pull-request

#3555 fix: pullsync will only return an error if the interval needs to be retried
  pkg/puller/puller.go
  pkg/pullsync/pullsync.go
  pkg/pullsync/pullsync_test.go
Labels: pull-request

#3559 fix: larger tip on cancellation
  pkg/transaction/transaction.go
  pkg/transaction/transaction_test.go
Labels: pull-request

#3562 fix: boost gas fee cap as well
  pkg/storageincentives/redistribution/redistribution.go
  pkg/transaction/transaction.go
  pkg/transaction/transaction_test.go
Labels: pull-request

#3561 chore: disable puller logs
  pkg/puller/puller.go
  pkg/pullsync/pullstorage/pullstorage.go
  pkg/pullsync/pullsync.go
Labels: pull-request

#3536 ci: bump k3s version, use custom beekeeper and beelocal branch
  .github/workflows/beekeeper.yml
  Makefile
Labels: in progress, pull-request, devops

#3567 chore: more logs for the sampler
  pkg/localstore/sampler.go
Labels: pull-request

#3565 fix: do not skip eviction of batches with higher radius
  pkg/postage/batchstore/reserve.go
  pkg/postage/batchstore/reserve_test.go
Labels: pull-request

#3535 fix: add transaction hash
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  pkg/api/postage.go
  pkg/api/postage_test.go
  pkg/node/devnode.go
  pkg/postage/postagecontract/contract.go
  pkg/postage/postagecontract/contract_test.go
  pkg/postage/postagecontract/mock/contract.go
Labels: ready for review, pull-request

#3574 ci: set prepare action for make beelocal
  .github/workflows/beekeeper.yml
Labels: pull-request

#3572 chore: explicit error messages from put sync
  pkg/localstore/mode_put.go
  pkg/localstore/mode_set.go
  pkg/pullsync/pullsync.go
  pkg/topology/depthmonitor/depthmonitor.go
Labels: pull-request

#3566 fix: relax reserve eviction during GC
  pkg/localstore/gc.go
  pkg/localstore/gc_test.go
  pkg/localstore/localstore.go
  pkg/node/node.go
Labels: pull-request

#3571 feat: add wallet address
  openapi/SwarmCommon.yaml
  pkg/api/wallet.go
  pkg/api/wallet_test.go
Labels: ready for review, pull-request

#3564 chore: enable puller test
  pkg/puller/puller_test.go
Labels: pull-request

#3573 feat(staking): add tx hash
  openapi/SwarmDebug.yaml
  pkg/api/postage.go
  pkg/api/staking.go
  pkg/api/staking_test.go
  pkg/node/devnode.go
  pkg/postage/postagecontract/contract.go
  pkg/storageincentives/staking/contract.go
  pkg/storageincentives/staking/contract_test.go
  pkg/storageincentives/staking/mock/contract.go
Labels: ready for review, pull-request

#3578 chore: reduce verbosity of chainsync
  pkg/chainsyncer/chainsyncer.go
Labels: pull-request

#3582 fix: use gas estimate
  pkg/postage/postagecontract/contract.go
  pkg/storageincentives/redistribution/redistribution.go
  pkg/storageincentives/staking/contract.go
  pkg/transaction/transaction.go
Labels: pull-request

#3577 fix: save stamp issuer data after usage not service close
  pkg/api/api.go
  pkg/api/postage.go
  pkg/api/pss.go
  pkg/api/soc.go
  pkg/postage/mock/service.go
  pkg/postage/postagecontract/contract_test.go
  pkg/postage/service.go
  pkg/postage/service_test.go
Labels: pull-request

#3584 fix: unreserve batch to start from bin 0
  pkg/localstore/reserve.go
  pkg/localstore/reserve_test.go
  pkg/node/node.go
Labels: pull-request

#3579 fix(localstore): remove reserve calculation from localstore
  pkg/localstore/gc.go
  pkg/localstore/gc_test.go
  pkg/localstore/index_test.go
  pkg/localstore/localstore.go
  pkg/localstore/localstore_test.go
  pkg/localstore/mode_put.go
  pkg/localstore/mode_put_test.go
  pkg/localstore/mode_set.go
  pkg/localstore/pin_test.go
  pkg/localstore/reserve.go
  pkg/localstore/reserve_test.go
  pkg/localstore/sampler_test.go
  pkg/localstore/subscription_pull_test.go
  pkg/node/node.go
  pkg/pullsync/pullstorage/pullstorage_test.go
  pkg/pullsync/pullsync.go
Labels: pull-request

#3585 fix: gc to continue on retrieval error
  pkg/localstore/gc.go
Labels: pull-request

#3587 fix: add missing and some new metrics
  pkg/localstore/reserve.go
  pkg/sharky/metrics.go
  pkg/sharky/store.go
Labels: pull-request

#3589 fix: ignore overwrite errors for syncing
  pkg/localstore/mode_put.go
  pkg/localstore/mode_put_test.go
Labels: pull-request

#3516 feat: add go leak check
  go.mod
  go.sum
  pkg/accounting/main_test.go
  pkg/addressbook/main_test.go
  pkg/api/main_test.go
  pkg/auth/main_test.go
  pkg/blocker/blocker_test.go
  pkg/bmt/main_test.go
  pkg/chainsync/main_test.go
  pkg/chainsyncer/main_test.go
  pkg/feeds/epochs/main_test.go
  pkg/feeds/sequence/main_test.go
  pkg/file/main_test.go
  pkg/file/pipeline/builder/main_test.go
  pkg/file/pipeline/hashtrie/main_test.go
  pkg/file/splitter/main_test.go
  pkg/flipflop/main_test.go
  pkg/hive/main_test.go
  pkg/intervalstore/main_test.go
  pkg/localstore/main_test.go
  pkg/log/main_test.go
  pkg/manifest/main_test.go
  pkg/netstore/main_test.go
  pkg/node/main_test.go
  pkg/p2p/libp2p/internal/reacher/main_test.go
  pkg/p2p/libp2p/main_test.go
  pkg/p2p/protobuf/main_test.go
  pkg/p2p/streamtest/main_test.go
  pkg/pingpong/main_test.go
  pkg/pinning/main_test.go
  pkg/postage/batchstore/main_test.go
  pkg/postage/listener/main_test.go
  pkg/postage/main_test.go
  pkg/postage/postagecontract/main_test.go
  pkg/pss/main_test.go
  pkg/puller/main_test.go
  pkg/pullsync/main_test.go
  pkg/pullsync/pullstorage/main_test.go
  pkg/pusher/main_test.go
  pkg/pushsync/main_test.go
  pkg/retrieval/main_test.go
  pkg/settlement/pseudosettle/main_test.go
  pkg/settlement/swap/main_test.go
  pkg/settlement/swap/priceoracle/main_test.go
  pkg/sharky/main_test.go
  pkg/statestore/leveldb/main_test.go
  pkg/steward/main_test.go
  pkg/storageincentives/main_test.go
  pkg/tags/main_test.go
  pkg/topology/depthmonitor/main_test.go
  pkg/topology/kademlia/kademlia_test.go
  pkg/topology/kademlia/main_test.go
  pkg/topology/lightnode/main_test.go
  pkg/tracing/main_test.go
  pkg/transaction/main_test.go
  pkg/traversal/main_test.go
  pkg/util/ioutil/main_test.go
Labels: ready for review, pull-request

#3548 fix(intervalstore): go leak enabled
  go.sum
  pkg/intervalstore/main_test.go
Labels: ready for review, pull-request

#3547 fix(batchstore): go leak check enabled
  pkg/postage/batchstore/main_test.go
Labels: ready for review, pull-request

#3549 fix(localstore): go leak enabled
  pkg/localstore/main_test.go
Labels: ready for review, pull-request

#3586 chore(node): go leak enabled
  pkg/node/main_test.go
Labels: ready for review, pull-request

#3546 fix(statestore/leveldb): go leak
  pkg/statestore/leveldb/main_test.go
Labels: ready for review

#3528 fix(accounting): goroutine leak
  pkg/accounting/accounting_test.go
  pkg/accounting/main_test.go
Labels: ready for review, pull-request

#3591 fix: simplify gc size calculation
  pkg/localstore/gc.go
  pkg/localstore/metrics.go
  pkg/localstore/reserve.go
Labels: pull-request

#3590 fix: nuke statestore to remove sync intervals
  pkg/puller/puller.go
  pkg/statestore/leveldb/migration.go
Labels: pull-request

#3594 chore(node): ignore leaky goroutine
  pkg/node/main_test.go
Labels: pull-request

#3597 revert: leak detection
  go.mod
  go.sum
  pkg/accounting/accounting_test.go
  pkg/accounting/main_test.go
  pkg/addressbook/main_test.go
  pkg/api/main_test.go
  pkg/auth/main_test.go
  pkg/blocker/blocker_test.go
  pkg/bmt/main_test.go
  pkg/chainsync/main_test.go
  pkg/chainsyncer/main_test.go
  pkg/feeds/epochs/main_test.go
  pkg/feeds/sequence/main_test.go
  pkg/file/main_test.go
  pkg/file/pipeline/builder/main_test.go
  pkg/file/pipeline/hashtrie/main_test.go
  pkg/file/splitter/main_test.go
  pkg/flipflop/main_test.go
  pkg/hive/main_test.go
  pkg/intervalstore/main_test.go
  pkg/localstore/main_test.go
  pkg/log/main_test.go
  pkg/manifest/main_test.go
  pkg/netstore/main_test.go
  pkg/node/main_test.go
  pkg/p2p/libp2p/internal/reacher/main_test.go
  pkg/p2p/libp2p/main_test.go
  pkg/p2p/protobuf/main_test.go
  pkg/p2p/streamtest/main_test.go
  pkg/pingpong/main_test.go
  pkg/pinning/main_test.go
  pkg/postage/batchstore/main_test.go
  pkg/postage/listener/main_test.go
  pkg/postage/main_test.go
  pkg/postage/postagecontract/main_test.go
  pkg/pss/main_test.go
  pkg/puller/main_test.go
  pkg/pullsync/main_test.go
  pkg/pullsync/pullstorage/main_test.go
  pkg/pusher/main_test.go
  pkg/pushsync/main_test.go
  pkg/retrieval/main_test.go
  pkg/settlement/pseudosettle/main_test.go
  pkg/settlement/swap/main_test.go
  pkg/settlement/swap/priceoracle/main_test.go
  pkg/sharky/main_test.go
  pkg/statestore/leveldb/main_test.go
  pkg/steward/main_test.go
  pkg/storageincentives/main_test.go
  pkg/tags/main_test.go
  pkg/topology/depthmonitor/main_test.go
  pkg/topology/kademlia/kademlia_test.go
  pkg/topology/kademlia/main_test.go
  pkg/topology/lightnode/main_test.go
  pkg/tracing/main_test.go
  pkg/transaction/main_test.go
  pkg/traversal/main_test.go
  pkg/util/ioutil/main_test.go
Labels: pull-request

#3596 fix: compute reserve to start from po 0
  pkg/localstore/gc_test.go
  pkg/localstore/localstore_test.go
  pkg/localstore/reserve.go
  pkg/localstore/reserve_test.go
  pkg/localstore/sampler_test.go
  pkg/topology/depthmonitor/depthmonitor.go
  pkg/topology/depthmonitor/depthmonitor_test.go
Labels: pull-request

#3595 fix: new localstore migration to reset gcSize
  pkg/localstore/migration.go
  pkg/localstore/migration_gc_reset.go
  pkg/localstore/schema.go
Labels: pull-request

#3599 revert: compute reserve to start from po 0 (#3596)
  pkg/localstore/gc_test.go
  pkg/localstore/localstore_test.go
  pkg/localstore/reserve.go
  pkg/localstore/reserve_test.go
  pkg/localstore/sampler_test.go
  pkg/topology/depthmonitor/depthmonitor.go
  pkg/topology/depthmonitor/depthmonitor_test.go
Labels: pull-request

#3600 fix: reset sync interval for the new lower bin
  pkg/puller/puller.go
  pkg/puller/puller_test.go
Labels: pull-request

#3605 revert: nuke statestore to remove sync intervals (#3590)
  pkg/statestore/leveldb/migration.go
Labels: pull-request

#3603 fix: padded bin str to avoid unintentionally deleting different bins
  pkg/localstore/mode_put.go
  pkg/puller/puller.go
  pkg/puller/puller_test.go
Labels: pull-request
