Repository ethersphere/bee, pull requests merged in 2023-05, with the labels that each got.

#4027 fix(localstorev2): metrics fix and cleanups
  pkg/node/node.go
  pkg/storer/metrics.go
  pkg/storer/pinstore.go
  pkg/storer/reserve.go
  pkg/storer/reserve_test.go
Labels: pull-request

#4021 feat: add chunk type information to reserve
  pkg/storage/testing/chunk.go
  pkg/storer/internal/reserve/items.go
  pkg/storer/internal/reserve/reserve.go
  pkg/storer/internal/reserve/reserve_test.go
  pkg/swarm/swarm.go
Labels: ready for review, pull-request

#4044 fix(retrieval): select peer before go routine push attempt
  pkg/retrieval/retrieval.go
Labels: pull-request

#4045 fix(kademlia): new prune log, oversaturation check fix, and more aggressive balance connector
  pkg/topology/kademlia/kademlia.go
Labels: pull-request

#4052 fix(kad): race cond
  pkg/topology/kademlia/kademlia.go
Labels: pull-request

#4050 fix: race condition in commit event handler
  pkg/storageincentives/agent.go
Labels: ready for review, pull-request

#4049 chore(reserve): sample data improvements
  pkg/storageincentives/agent.go
  pkg/storageincentives/agent_test.go
  pkg/storageincentives/export_test.go
  pkg/storageincentives/proof.go
  pkg/storageincentives/proof_test.go
  pkg/storer/mock/mockreserve.go
  pkg/storer/reserve.go
  pkg/storer/reserve_test.go
  pkg/swarm/swarm.go
Labels: ready for review, pull-request

#4053 fix(storer): misc fixes from testing
  pkg/node/node.go
  pkg/postage/service.go
  pkg/pusher/pusher.go
  pkg/storer/internal/reserve/reserve.go
  pkg/topology/kademlia/kademlia.go
Labels: pull-request

#4062 fix: last played round
  pkg/storageincentives/agent.go
Labels: pull-request

#4055 feat(sample): exclude batches with low balance
  pkg/api/api_test.go
  pkg/node/node.go
  pkg/storageincentives/agent.go
  pkg/storageincentives/agent_test.go
  pkg/storageincentives/proof_test.go
  pkg/storageincentives/redistributionstate.go
  pkg/storageincentives/redistributionstate_test.go
  pkg/storer/mock/mockreserve.go
  pkg/storer/reserve.go
  pkg/storer/reserve_test.go
  pkg/storer/storer.go
Labels: pull-request

#4042 fix: status api to return batchstore commitment
  openapi/SwarmCommon.yaml
  pkg/api/postage.go
  pkg/api/status.go
  pkg/api/status_test.go
  pkg/p2p/libp2p/internal/handshake/pb/handshake.pb.go
  pkg/postage/batchstore/mock/store.go
  pkg/postage/batchstore/reserve.go
  pkg/postage/batchstore/store.go
  pkg/postage/interface.go
  pkg/postage/noop.go
  pkg/status/internal/pb/status.pb.go
  pkg/status/internal/pb/status.proto
  pkg/status/status.go
  pkg/status/status_test.go
Labels: pull-request

#4065 chore: switch back to the beekeeper master branch
  .github/workflows/beekeeper.yml
Labels: pull-request

#4064 fix(pushsync): include self in the case no neighbor can be found
  pkg/pushsync/pushsync.go
Labels: pull-request

#4056 feat(salud): new health service
  openapi/SwarmCommon.yaml
  pkg/api/api_test.go
  pkg/node/node.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/salud/metrics.go
  pkg/salud/salud.go
  pkg/salud/salud_test.go
  pkg/storageincentives/agent.go
  pkg/storageincentives/agent_test.go
  pkg/topology/kademlia/export_test.go
  pkg/topology/kademlia/internal/metrics/metrics.go
  pkg/topology/kademlia/internal/metrics/metrics_test.go
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
  pkg/topology/kademlia/mock/kademlia.go
  pkg/topology/mock/mock.go
  pkg/topology/topology.go
Labels: pull-request

#4075 fix: state store adapter iterator
  pkg/statestore/test/store.go
  pkg/storage/statestore.go
Labels: pull-request

#4070 refactor: use leveldb in stamper
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/main_test.go
  pkg/api/pss.go
  pkg/node/devnode.go
  pkg/node/node.go
  pkg/node/statestore.go
  pkg/postage/service.go
  pkg/postage/stamp_test.go
  pkg/postage/stamper.go
  pkg/postage/stamper_test.go
  pkg/postage/stampissuer.go
Labels: pull-request

#4030 fix(cac): data and span size validation
  pkg/cac/cac.go
  pkg/cac/cac_test.go
  pkg/cac/export_test.go
Labels: ready for review, pull-request

#4077 fix(pusher, retrieval, salud): panic and leak fix
  pkg/pusher/metrics.go
  pkg/pusher/pusher.go
  pkg/retrieval/retrieval.go
  pkg/salud/salud.go
  pkg/status/status.go
Labels: pull-request

#4093 chore(puller, pullsync): remove 24 wait period for puller, new metrics, cleanup
  pkg/node/node.go
  pkg/puller/metrics.go
  pkg/puller/puller.go
  pkg/puller/puller_test.go
  pkg/pullsync/metrics.go
  pkg/pullsync/pullsync.go
  pkg/pullsync/pullsync_test.go
Labels: pull-request

#4094 fix: transaction bookeeping memory leak
  pkg/storage/inmemchunkstore/transaction.go
  pkg/storage/inmemstore/transaction.go
  pkg/storage/leveldbstore/transaction.go
  pkg/storage/transaction.go
Labels: pull-request

#4082 ci: upgrade actions and fix soon to deprecated gorelaser options
  .github/workflows/release.yaml
  .goreleaser.yml
Labels: pull-request

#4108 chore(storer): add more metrics
  pkg/storer/cachestore.go
  pkg/storer/internal/stampindex/stampindex.go
  pkg/storer/metrics.go
  pkg/storer/reserve.go
  pkg/storer/storer.go
Labels: pull-request

#4105 chore: add benchmark for cache putter
  pkg/storage/storagetest/benchmark.go
  pkg/storer/cachestore_test.go
  pkg/storer/internal/cache/cache.go
Labels: pull-request

#4104 fix: debug api version in health endpoint
  Makefile
  pkg/api/health.go
  pkg/api/version.go
Labels: pull-request

#4051 perf(skippers): further optimizations
  pkg/skippeers/skippeers.go
Labels: pull-request

#4109 chore(api): headers cleanup
  pkg/api/api.go
  pkg/api/auth_test.go
  pkg/api/bytes.go
  pkg/api/bytes_test.go
  pkg/api/bzz.go
  pkg/api/bzz_test.go
  pkg/api/chequebook_test.go
  pkg/api/chunk.go
  pkg/api/chunk_stream_test.go
  pkg/api/cors_test.go
  pkg/api/dirs.go
  pkg/api/dirs_test.go
  pkg/api/export_test.go
  pkg/api/pin_test.go
  pkg/api/postage_test.go
  pkg/api/redistribution_test.go
  pkg/api/staking_test.go
  pkg/api/subdomain_test.go
  pkg/api/tag_test.go
  pkg/api/topology.go
Labels: pull-request

#4112 chore(api): simplify header assertions
  pkg/api/api_test.go
  pkg/api/bzz_test.go
  pkg/api/cors_test.go
  pkg/api/feed_test.go
  pkg/api/tag_test.go
  pkg/jsonhttp/jsonhttptest/jsonhttptest.go
  pkg/jsonhttp/jsonhttptest/jsonhttptest_test.go
Labels: pull-request

#4113 fix(storer): tags bug and encrypted ref handling
  pkg/storage/storagetest/storage.go
  pkg/storer/internal/pinning/pinning.go
  pkg/storer/internal/pinning/pinning_test.go
  pkg/storer/internal/upload/uploadstore.go
  pkg/storer/subscribe_push.go
  pkg/storer/uploadstore.go
  pkg/swarm/swarm.go
Labels: pull-request

#4083 refactor: add reserve subcommands to db export and import
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/db.go
  cmd/bee/cmd/db_test.go
  pkg/node/node.go
  pkg/storer/reserve.go
  pkg/storer/storer.go
Labels: pull-request

#4117 fix(hive): change transaction field to nonce
  pkg/bzz/address.go
  pkg/bzz/utilities_test.go
  pkg/hive/hive.go
  pkg/hive/hive_test.go
  pkg/hive/pb/hive.pb.go
  pkg/hive/pb/hive.proto
Labels: pull-request, localstoreV2-release

#4115 fix(puller): added new mtx locking to interval state storing
  pkg/puller/puller.go
Labels: pull-request

#4110 feat(salud): self health check based on reserve size
  pkg/node/node.go
  pkg/salud/main_test.go
  pkg/salud/metrics.go
  pkg/salud/salud.go
  pkg/salud/salud_test.go
Labels: pull-request

#4092 feat(kademlia): prune out of depth oversaturated bins based on peer health
  pkg/api/status.go
  pkg/api/status_test.go
  pkg/chainsyncer/chainsyncer.go
  pkg/node/bootstrap.go
  pkg/puller/puller.go
  pkg/pushsync/pushsync.go
  pkg/retrieval/retrieval.go
  pkg/salud/salud.go
  pkg/status/status.go
  pkg/status/status_test.go
  pkg/topology/depthmonitor/depthmonitor.go
  pkg/topology/depthmonitor/depthmonitor_test.go
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
  pkg/topology/kademlia/mock/kademlia.go
  pkg/topology/mock/mock.go
  pkg/topology/topology.go
Labels: pull-request
