Repository ethersphere/bee, pull requests merged in 2023-06, with the labels that each got.

#4123 fix(storer): handle eviction on light and bootnodes
  pkg/storer/reserve.go
Labels: pull-request

#4124 fix(puller): nil pointer on Close
  pkg/puller/puller.go
Labels: pull-request

#4126 fix: transaction return a contex.Canceled error when the parent context is canceled
  pkg/storage/transaction.go
Labels: pull-request

#4127 fix(storer): cleanup reserve and cache synchronization
  cmd/bee/cmd/db.go
  cmd/bee/cmd/db_test.go
  pkg/pullsync/pullsync.go
  pkg/pusher/pusher.go
  pkg/pusher/pusher_test.go
  pkg/pushsync/pushsync.go
  pkg/pushsync/pushsync_test.go
  pkg/storer/debug_test.go
  pkg/storer/internal/cache/cache.go
  pkg/storer/internal/cache/cache_test.go
  pkg/storer/internal/cache/export_test.go
  pkg/storer/internal/reserve/reserve.go
  pkg/storer/mock/mockreserve.go
  pkg/storer/reserve.go
  pkg/storer/reserve_test.go
  pkg/storer/storer.go
Labels: pull-request

#4132 fix: transaction rollback logic
  pkg/storage/inmemchunkstore/transaction.go
  pkg/storage/inmemstore/transaction.go
  pkg/storage/leveldbstore/transaction.go
  pkg/storage/storagetest/transaction.go
  pkg/storage/transaction.go
  pkg/storer/internal/chunkstore/transaction.go
Labels: pull-request

#4116 fix(hive): do not gossip private CIDRs unless explicitly allowed
  pkg/hive/hive.go
Labels: pull-request

#4133 refactor: improve errors
  pkg/storage/inmemstore/inmemstore.go
  pkg/storage/leveldbstore/store.go
  pkg/storage/leveldbstore/transaction.go
  pkg/storage/repository.go
  pkg/storer/cachestore.go
  pkg/storer/internal/chunkstamp/chunkstamp.go
  pkg/storer/internal/chunkstore/chunkstore.go
  pkg/storer/internal/internal.go
  pkg/storer/pinstore.go
  pkg/storer/reporter.go
  pkg/storer/reserve.go
  pkg/storer/storer.go
  pkg/storer/uploadstore.go
Labels: pull-request

#4090 refactor: Added information for redistributionState endpoint
  openapi/SwarmCommon.yaml
  pkg/api/redistribution.go
  pkg/storageincentives/agent.go
  pkg/storageincentives/redistributionstate.go
Labels: pull-request

#4134 chore(agent): show sample duration in endpoint, cleanup, reduce required min funds slightly
  openapi/SwarmCommon.yaml
  pkg/api/redistribution.go
  pkg/storageincentives/agent.go
  pkg/storageincentives/redistributionstate.go
  pkg/storageincentives/redistributionstate_test.go
Labels: pull-request

#4130 feat: add db nuke and db info cmd
  cmd/bee/cmd/db.go
  cmd/bee/cmd/db_test.go
  pkg/storage/statestore.go
Labels: pull-request

#4139 feat: ph3 sample
  pkg/storageincentives/proof.go
  pkg/storer/export_test.go
  pkg/storer/reserve.go
Labels: pull-request

#4140 feat(sample): validate stamp
  pkg/postage/stamp.go
  pkg/storer/reserve.go
  pkg/storer/reserve_test.go
  pkg/storer/storer.go
Labels: pull-request

#4146 fix(status): get radius before calculations
  pkg/api/status_test.go
  pkg/node/node.go
  pkg/status/status.go
  pkg/status/status_test.go
  pkg/storer/reserve.go
  pkg/storer/storer.go
Labels: pull-request

#4118 feat: salud to record peer latency
  pkg/node/bootstrap.go
  pkg/node/node.go
  pkg/salud/salud.go
  pkg/topology/kademlia/kademlia.go
  pkg/topology/kademlia/kademlia_test.go
  pkg/topology/kademlia/metrics.go
  pkg/topology/kademlia/mock/kademlia.go
  pkg/topology/mock/mock.go
  pkg/topology/topology.go
Labels: pull-request, localstoreV2-release

#4144 chore: export methods
  pkg/bmt/bmt.go
  pkg/postage/export_test.go
  pkg/postage/stamp.go
  pkg/postage/stamp_test.go
  pkg/postage/stampissuer.go
  pkg/soc/export_test.go
  pkg/soc/soc.go
  pkg/soc/validator.go
Labels: pull-request

#4155 chore(storer): sampling perfromace improvements
  pkg/storer/internal/reserve/reserve.go
  pkg/storer/reserve.go
  pkg/storer/reserve_test.go
  pkg/storer/sample.go
  pkg/storer/sample_test.go
Labels: pull-request

#4151 fix(storer): refactor upload and pinning putters
  pkg/api/tag.go
  pkg/sharky/recovery.go
  pkg/storage/storageutil/storageutil.go
  pkg/storer/epoch_migration.go
  pkg/storer/epoch_migration_test.go
  pkg/storer/export_test.go
  pkg/storer/internal/internal.go
  pkg/storer/internal/pinning/export_test.go
  pkg/storer/internal/pinning/pinning.go
  pkg/storer/internal/pinning/pinning_test.go
  pkg/storer/internal/reserve/reserve.go
  pkg/storer/internal/reserve/reserve_test.go
  pkg/storer/internal/upload/export_test.go
  pkg/storer/internal/upload/uploadstore.go
  pkg/storer/internal/upload/uploadstore_test.go
  pkg/storer/mock/mockstorer.go
  pkg/storer/mock/mockstorer_test.go
  pkg/storer/netstore.go
  pkg/storer/pinstore.go
  pkg/storer/reserve.go
  pkg/storer/storer.go
  pkg/storer/subscribe_push.go
  pkg/storer/uploadstore.go
  pkg/storer/uploadstore_test.go
Labels: pull-request

#4157 chore(sampling): stats improvements
  pkg/storer/reserve.go
  pkg/storer/sample.go
  pkg/storer/sample_test.go
Labels: pull-request

#4137 refactor(api): improve vagueness of 'minimumFunds' label
  openapi/SwarmCommon.yaml
  pkg/api/redistribution.go
Labels: pull-request

#4158 fix(agent): check frozen status before neighborhood selection and remove some logs
  pkg/storageincentives/agent.go
Labels: pull-request

#4159 fix(batchstore,reserve): cleanup mtx locks
  pkg/node/devnode.go
  pkg/node/node.go
  pkg/postage/batchstore/store.go
  pkg/postage/batchstore/store_test.go
  pkg/storer/internal/reserve/reserve.go
Labels: pull-request

#4154 feat(statestore): move adapter code and add migration
  cmd/bee/cmd/db.go
  pkg/node/statestore.go
  pkg/statestore/storeadapter/migration.go
  pkg/statestore/storeadapter/storeadapter.go
  pkg/statestore/storeadapter/storeadapter_test.go
  pkg/storage/leveldbstore/store.go
  pkg/storage/statestore.go
  pkg/storer/epoch_migration.go
Labels: pull-request

#4149 fix(direct-upload): use same concurrency as deferred upload
  pkg/pusher/pusher.go
  pkg/storer/export_test.go
  pkg/storer/netstore.go
  pkg/storer/storer.go
Labels: pull-request

#4165 fix: read chunk data during migration
  pkg/storer/epoch_migration.go
Labels: pull-request

#4163 fix: restart always systemd service
  packaging/bee.service
Labels: pull-request

#4167 fix: retry on shallow receipt for direct upload
  pkg/pusher/pusher.go
  pkg/storer/netstore.go
  pkg/storer/netstore_test.go
Labels: pull-request

#4166 chore(openapi): update and bump versions
  openapi/Swarm.yaml
  openapi/SwarmCommon.yaml
  openapi/SwarmDebug.yaml
  pkg/api/api_test.go
  pkg/api/chunk_stream.go
  pkg/api/chunk_stream_test.go
  pkg/api/chunk_test.go
  pkg/api/router.go
  pkg/api/soc.go
  pkg/api/soc_test.go
  pkg/p2p/libp2p/internal/handshake/handshake.go
  pkg/topology/kademlia/kademlia.go
Labels: pull-request

#4168 chore: temp migration for testnet
  pkg/statestore/storeadapter/migration.go
Labels: pull-request

#4169 fix(puller): histsync timeout should be higher than makeoffer
  pkg/puller/puller.go
  pkg/statestore/storeadapter/migration.go
Labels: pull-request

#4150 feat: move stamp issuer to stamperstore
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/bytes.go
  pkg/api/bzz.go
  pkg/api/chunk.go
  pkg/api/chunk_stream.go
  pkg/api/feed.go
  pkg/api/postage.go
  pkg/api/postage_test.go
  pkg/api/soc.go
  pkg/api/soc_test.go
  pkg/node/node.go
  pkg/node/statestore.go
  pkg/node/statestore_test.go
  pkg/postage/batchservice/batchservice.go
  pkg/postage/batchservice/batchservice_test.go
  pkg/postage/batchstore/store.go
  pkg/postage/interface.go
  pkg/postage/mock/service.go
  pkg/postage/service.go
  pkg/postage/service_test.go
  pkg/postage/stampissuer.go
  pkg/postage/stampissuer_test.go
Labels: pull-request

#4171 fix: ignore not found entries for expiry event
  pkg/postage/service.go
Labels: pull-request

#4170 fix(storer): metric fix
  pkg/storer/metrics.go
Labels: pull-request

#4172 fix: issues with direct upload and stamper cleanup
  pkg/api/api.go
  pkg/api/postage.go
  pkg/api/pss.go
  pkg/api/stewardship.go
  pkg/postage/export_test.go
  pkg/postage/mock/service.go
  pkg/postage/service.go
  pkg/postage/service_test.go
  pkg/pusher/pusher.go
Labels: pull-request

#4175 fix: allow tx rollback on context deadline exceeded error
  pkg/storage/transaction.go
Labels: pull-request

#4176 fix: mutable batches resets index buckets
  pkg/postage/export_test.go
  pkg/postage/stampissuer.go
  pkg/postage/stampissuer_test.go
  pkg/storer/internal/upload/uploadstore.go
Labels: pull-request

#4161 feat: tx crash recovery mechanism
  pkg/statestore/leveldb/leveldb.go
  pkg/statestore/leveldb/migration.go
  pkg/statestore/storeadapter/storeadapter.go
  pkg/storage/inmemchunkstore/transaction.go
  pkg/storage/inmemstore/inmemstore.go
  pkg/storage/inmemstore/transaction.go
  pkg/storage/leveldbstore/batch.go
  pkg/storage/leveldbstore/recovery.go
  pkg/storage/leveldbstore/recovery_test.go
  pkg/storage/leveldbstore/store.go
  pkg/storage/leveldbstore/transaction.go
  pkg/storage/storage.go
  pkg/storage/transaction.go
  pkg/storer/epoch_migration.go
  pkg/storer/internal/chunkstore/chunkstore.go
  pkg/storer/internal/chunkstore/recovery.go
  pkg/storer/internal/chunkstore/recovery_test.go
  pkg/storer/internal/chunkstore/transaction.go
  pkg/storer/internal/chunkstore/transaction_test.go
  pkg/storer/internal/reserve/reserve.go
  pkg/storer/sample_test.go
  pkg/storer/storer.go
Labels: pull-request

#4178 fix: check stampissuer saved index
  pkg/postage/export_test.go
  pkg/postage/stamper.go
  pkg/postage/stamper_test.go
  pkg/postage/stampissuer.go
  pkg/storer/internal/upload/uploadstore.go
Labels: pull-request

#4177 feat: statestore cache
  cmd/bee/cmd/cmd.go
  cmd/bee/cmd/db.go
  cmd/bee/cmd/deploy.go
  cmd/bee/cmd/init.go
  cmd/bee/cmd/start.go
  go.mod
  go.sum
  pkg/node/node.go
  pkg/node/statestore.go
  pkg/node/statestore_test.go
  pkg/pushsync/pushsync.go
  pkg/retrieval/retrieval.go
  pkg/storage/cache/cache.go
  pkg/storage/cache/cache_test.go
  pkg/storage/cache/metrics.go
Labels: pull-request

#4180 fix: move eviction to the end of batch expiration handling
  pkg/postage/batchstore/store.go
Labels: pull-request

#4181 refactor(cache): cleanup
  pkg/node/statestore.go
  pkg/storage/cache/cache.go
  pkg/storage/cache/cache_test.go
  pkg/storage/cache/metrics.go
Labels: pull-request

#4135 fix(reserve): best attempt to remove all related items
  pkg/postage/stampissuer.go
  pkg/pushsync/pushsync.go
  pkg/storer/internal/reserve/reserve.go
Labels: on hold, pull-request, localstoreV2-release

#4182 perf: remove leveldb sync true option
  pkg/storage/leveldbstore/transaction.go
Labels: pull-request

#4183 fix: best effort cleanup bug
  pkg/storer/internal/chunkstamp/chunkstamp.go
Labels: pull-request

#4184 fix: wait for network radius
  pkg/pusher/pusher.go
  pkg/salud/salud.go
Labels: pull-request

#4186 fix(pullsync): panic on reading from closed channel
  pkg/pullsync/pullsync.go
  pkg/pullsync/pullsync_test.go
Labels: pull-request

#4185 fix(reserve): must call set radius to notify kademlia
  pkg/storer/reserve.go
Labels: pull-request

#4188 perf(leveldb): disable seek compaction
  cmd/bee/cmd/cmd.go
Labels: pull-request

#4187 perf: reduce locking context during evictions
  pkg/storer/internal/reserve/reserve.go
  pkg/storer/internal/reserve/reserve_test.go
  pkg/storer/reserve.go
Labels: pull-request

#4190 refactor: ignore error not found in getter metrics
  pkg/storer/metrics.go
Labels: pull-request

#4192 refactor(listener): use atomic pointer for chain state and add extra log line
  pkg/postage/batchstore/store.go
  pkg/postage/listener/listener.go
Labels: pull-request

#4189 feat: periodic cleanup of expired chunks from the reserve
  pkg/storer/reserve.go
  pkg/storer/sample.go
Labels: pull-request

#4195 fix: metrics
  pkg/pullsync/pullsync.go
Labels: pull-request

#4191 fix: pass ctx to stop puller
  pkg/node/node.go
  pkg/puller/mock/puller.go
  pkg/puller/puller.go
  pkg/puller/puller_test.go
  pkg/storer/reserve.go
  pkg/storer/reserve_test.go
  pkg/storer/storer.go
Labels: ready for review, pull-request

#4197 fix(reserve): optimizing the cleanup worker
  cmd/bee/cmd/cmd.go
  pkg/postage/batchstore/mock/store.go
  pkg/storage/metrics.go
  pkg/storer/internal/reserve/reserve.go
  pkg/storer/metrics.go
  pkg/storer/reserve.go
Labels: pull-request
